security:
  ip-address: ${SOME_IP_ADDRESS}

scheduler:
  market-data-cron: "0 0 0 * * *" # Every day at midnight UTC
  news-recommendations-cron: "0 30 8 * * *" # Every day one hour before the market opens

spring:
  application:
    name: server
  profiles:
    active: ${SPRING_PROFILE}
  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}
    admin: ${ADMIN_USERS}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

ai:
  deployments:
    one:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_ONE}
      temperature: 0
      max-tokens: 8000
    two:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_TWO}
      temperature: 0
      max-tokens: 8000
    three:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_THREE}
      temperature: 0
      max-tokens: 4000
    four:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_FOUR}
      temperature: 0
      max-tokens: 4000
    five:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_FIVE}
      temperature: 0
      max-tokens: 8000
    six:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_SIX}
      temperature: 0
      max-tokens: 8000
    seven:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_SEVEN}
      temperature: 0
      max-tokens: 8000
    eight:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_EIGHT}
      temperature: 0
      max-tokens: 8000
    nine:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_NINE}
      temperature: 0
      max-tokens: 8000
    ten:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_TEN}
      temperature: 0
      max-tokens: 8000
    eleven:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_ELEVEN}
      temperature: 0
      max-tokens: 8000
    twelve:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_TWELVE}
      temperature: 0
      max-tokens: 4000
    thirteen:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_THIRTEEN}
      temperature: 0
      max-tokens: 8000
    fourteen:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_FOURTEEN}
      temperature: 0
      max-tokens: 8000
    fifteen:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_FIFTEEN}
      temperature: 0
      max-tokens: 8000
    sixteen:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MODEL_SIXTEEN}
      temperature: 0
      max-tokens: 80008000

finnhub:
  api-key: ${FINNHUB_KEY}
  endpoint: ${FINNHUB_ENDPOINT}

twelve-data:
  api-key: ${TWELVE_DATA_KEY}
  endpoint: ${TWELVE_DATA_ENDPOINT}

sentiment:
  url: ${SENTIMENT_URL}
