spring:
  security:
    jwt:
      secret: ${SPRING_JWT_SECRET}
      secure: false
  flyway:
    enabled: false
  docker:
    compose:
      enabled: true
      file: ./docker/dev/compose.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080
  ssl:
    enabled: false
    key-store: classpath:certificates/keystore.jks
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
