security:
  ip-address: ${SOME_IP_ADDRESS}

scheduler:
  daily-cron: "0 0 2 * * *" # Every day at 2 AM UTC

spring:
  application:
    name: server
  profiles:
    active: ${SPRING_PROFILE}
  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}
    admin: ${ADMIN_USERS}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    azure:
      openai:
        api-key: ${OPENAI_KEY}
        endpoint: ${OPENAI_ENDPOINT}
        embedding:
          options:
            deployment-name: ${OPENAI_EMBEDDINGS_MODEL}
        chat:
          options:
            deployment-name: ${OPENAI_MODEL}
            secondary-deployment-name: ${OPENAI_SECONDARY_MODEL}
            llm-deployment-name: ${LLM}
            temperature: 0.2
            max-tokens: 8000
    model:
      chat: azure-openai

finnhub:
  api-key: ${FINNHUB_KEY}
  endpoint: ${FINNHUB_ENDPOINT}

twelve-data:
  api-key: ${TWELVE_DATA_KEY}
  endpoint: ${TWELVE_DATA_ENDPOINT}

language:
  api-key: ${LANGUAGE_API_KEY}
  endpoint: ${LANGUAGE_ENDPOINT}

sentiment:
  url: ${SENTIMENT_URL}
