spring:
  application:
    name: web app
  IPAddress: <address1>, <address2>
  security:
    user:
      name: <username>
      password: <password>
  datasource:
    url: jdbc:<server>://<address>:<port>/<database>;<options>
    username: <username>
    password: <password>
    driver-class-name: <package>.<class>

server:
  port: 8443
