security:
  ip-address: ${SOME_IP_ADDRESS}

scheduler:
  daily-cron: "0 0 21 * * *" # Every day at 21:00 UTC

spring:
  application:
    name: server
  profiles:
    active: ${SPRING_PROFILE}
  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}
    admin: ${ADMIN_USERS}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  ai:
    azure:
      openai:
        api-key: ${OPENAI_KEY}
        endpoint: ${OPENAI_ENDPOINT}
        embedding:
          options:
            deployment-name: ${OPENAI_EMBEDDINGS_MODEL}
        chat:
          options:
            deployment-name: ${OPENAI_MODEL}
            temperature: 0.2
            maxTokens: 1024
    model:
      chat: azure-openai

alphavantage:
  api-key: ${ALPHAVANTAGE_KEY}
  endpoint: ${ALPHAVANTAGE_ENDPOINT}

finnhub:
  api-key: ${FINNHUB_KEY}
  endpoint: ${FINNHUB_ENDPOINT}

twelve-data:
  api-key: ${TWELVE_DATA_KEY}
  endpoint: ${TWELVE_DATA_ENDPOINT}
