security:
  ip-address: ${SOME_IP_ADDRESS}

scheduler:
  market-data-cron: "0 0 0 * * *" # Every day at midnight UTC
  news-recommendations-cron: "0 0 12 * * *" # Every day at noon UTC

spring:
  application:
    name: server
  profiles:
    active: ${SPRING_PROFILE}
  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}
    admin: ${ADMIN_USERS}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

ai:
  deployments:
    one:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_41}
      temperature: 0
      max-tokens: 8000
    two:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_4O}
      temperature: 0
      max-tokens: 8000
    three:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${DEEPSEEK_MODEL}
      temperature: 0
      max-tokens: 4000
    four:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${GROK_MODEL}
      temperature: 0
      max-tokens: 4000
    five:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_41_MINI}
      temperature: 0
      max-tokens: 8000
    six:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_41_NANO}
      temperature: 0
      max-tokens: 8000
    seven:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_4O_MINI}
      temperature: 0
      max-tokens: 8000
    eight:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${AI21_MINI}
      temperature: 0
      max-tokens: 8000
    nine:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${LLAMA_31}
      temperature: 0
      max-tokens: 8000
    ten:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${MISTRAL_2501}
      temperature: 0
      max-tokens: 8000
    eleven:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${PHI_35_MINI}
      temperature: 0
      max-tokens: 8000
    twelve:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${PHI_4}
      temperature: 0
      max-tokens: 8000
    thirteen:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${PHI_4_MINI}
      temperature: 0
      max-tokens: 8000
    fourteen:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${PHI_4_REASONING}
      temperature: 0
      max-tokens: 8000

finnhub:
  api-key: ${FINNHUB_KEY}
  endpoint: ${FINNHUB_ENDPOINT}

twelve-data:
  api-key: ${TWELVE_DATA_KEY}
  endpoint: ${TWELVE_DATA_ENDPOINT}

sentiment:
  url: ${SENTIMENT_URL}
