security:
  ip-address: ${SOME_IP_ADDRESS}

scheduler:
  daily-cron: "0 0 8 * * *" # Every day at 8 AM UTC

spring:
  application:
    name: server
  profiles:
    active: ${SPRING_PROFILE}
  security:
    user:
      name: ${SPRING_USER}
      password: ${SPRING_PASSWORD}
    admin: ${ADMIN_USERS}
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

ai:
  deployments:
    first:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_MODEL}
      temperature: 0
      max-tokens: 8000
    second:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${GROK_MODEL}
      temperature: 0
      max-tokens: 4000
    third:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${DEEPSEEK_MODEL}
      temperature: 0
      max-tokens: 4000
    fourth:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_SECONDARY_MODEL}
      temperature: 0
      max-tokens: 8000
    fifth:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_THIRD_MODEL}
      temperature: 0
      max-tokens: 4000
    sixth:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_FOURTH_MODEL}
      temperature: 0
      max-tokens: 4000
    seventh:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${OPENAI_FIFTH_MODEL}
      temperature: 0
      max-tokens: 4000
    eighth:
      api-key: ${GITHUB_KEY}
      url: ${GITHUB_URL}
      model: ${LLAMA_MODEL}
      temperature: 0
      max-tokens: 8000

finnhub:
  api-key: ${FINNHUB_KEY}
  endpoint: ${FINNHUB_ENDPOINT}

twelve-data:
  api-key: ${TWELVE_DATA_KEY}
  endpoint: ${TWELVE_DATA_ENDPOINT}

sentiment:
  url: ${SENTIMENT_URL}
