services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080" ]
      interval: 1s
      timeout: 5s
      retries: 3

  mosquitto:
    image: eclipse-mosquitto
    environment:
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
    command: >
      /bin/sh -c "
        if [ ! -f /mosquitto/config/passwords ]; then
          touch /mosquitto/config/passwords
          mosquitto_passwd -b /mosquitto/config/passwords $MQTT_USER $MQTT_PASSWORD;
          chmod 600 /mosquitto/config/passwords;
        fi;
        exec /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf -v
      "

volumes:
  postgres:
