INSERT INTO "algorithm_mappings"
("corner_algorithm", "corner_technique", "corner_type", "edge_algorithm", "edge_technique", "edge_type",
 "first_sticker", "parity_algorithm", "parity_technique", "parity_type", "second_sticker")
VALUES (NULL, NULL, NULL, NULL, 'UNDEF', 'NULL', 2, NULL, NULL, NULL, 2),
       (NULL, NULL, NULL, 'r U R'' U'' r'' U2 R U R U'' R2 U2 R', 'UNDEF', 'TWIST', 2, NULL, NULL, NULL, 3),
       (NULL, NULL, NULL, 'M2 U M U2 M'' U M2 ', '4M', 'U101', 2, NULL, NULL, NULL, 4),
       (NULL, NULL, NULL, 'S'' r U'' r'' S r U r'' ', '8S', 'U81', 2, NULL, NULL, NULL, 5),
       (NULL, NULL, NULL, 'U M2 U M U2 M'' U M2 U''', '4M', 'U101', 2, NULL, NULL, NULL, 6),
       (NULL, NULL, NULL, 'r'' U'' R U M'' U'' R'' U R ', '8M', 'U81', 2, NULL, NULL, NULL, 7),
       (NULL, NULL, NULL, 'U2 R'' U'' R'' U'' R U R U R U', 'R/L,U', 'U92a', 2, NULL, NULL, NULL, 8),
       (NULL, NULL, NULL, 'U L E'' L'' U L E L'' U2 ', '8E', 'U92a', 2, NULL, NULL, NULL, 9),
       (NULL, NULL, NULL, 'U2 L U L U L U'' L'' U'' L'' U', 'R/L,U', 'U82b', 2, NULL, NULL, NULL, 10),
       (NULL, NULL, NULL, 'U'' R'' E R U R'' E'' R ', '8E', 'U82a', 2, NULL, NULL, NULL, 11),
       (NULL, NULL, NULL, 'M U2 M U M'' U2 M'' U'' ', 'M,U/D', 'U82d', 2, NULL, NULL, NULL, 12),
       (NULL, NULL, NULL, 'r U'' R'' U M U'' R U R'' ', '8M', 'U82e', 2, NULL, NULL, NULL, 13),
       (NULL, NULL, NULL, 'U R'' U'' R U R U R U'' R'' U2 ', 'R/L,U', 'U82d', 2, NULL, NULL, NULL, 14),
       (NULL, NULL, NULL, 'U'' R E R'' U R E'' R'' ', '8E', 'U82e', 2, NULL, NULL, NULL, 15),
       (NULL, NULL, NULL, 'U'' L'' U'' L U L U L U'' L'' ', 'R/L,U', 'U82f', 2, NULL, NULL, NULL, 16),
       (NULL, NULL, NULL, 'U L'' E'' L U L'' E L U2 ', '8E', 'U82g', 2, NULL, NULL, NULL, 17),
       (NULL, NULL, NULL, 'R U R'' U'' M U2 M'' U'' R U'' R'' ', '4M', 'U82f', 2, NULL, NULL, NULL, 18),
       (NULL, NULL, NULL, 'U M U M'' U M U M'' ', 'M,U/D', 'U82g', 2, NULL, NULL, NULL, 19),
       (NULL, NULL, NULL, 'R U R U R U'' R'' U'' R'' U''', 'R/L,U', 'U82a', 2, NULL, NULL, NULL, 20),
       (NULL, NULL, NULL, 'U L'' E L U L'' E'' L U2 ', '8E', 'U82b', 2, NULL, NULL, NULL, 21),
       (NULL, NULL, NULL, 'L'' U'' L'' U'' L U L U L U''', 'R/L,U', 'U82c', 2, NULL, NULL, NULL, 22),
       (NULL, NULL, NULL, 'U'' R E'' R'' U R E R'' ', '8E', 'U82c', 2, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'r U R'' U'' r'' U2 R U R U'' R2 U2 R', 'UNDEF', 'TWIST', 3,
        'U L'' U'' r U r'' U'' L U r U'' r'' L'' U L', NULL, NULL, 2),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 3, 'S'' U'' R U l'' U'' l U R'' U'' l'' U l R U'' R'' S', NULL,
        NULL, 3),
       ('R'' D'' R D R'' D'' R U'' R'' D R D'' R'' D R U', 'UNDEF', 'TWIST', 'l'' U l S l'' U'' l S'' ', '8S', 'U81', 3,
        'U'' R U l'' U'' l U R'' U'' l'' U l R U'' R''', NULL, NULL, 4),
       ('U'' R'' D'' R D R'' D'' R U R'' D R D'' R'' D R', 'UNDEF', 'TWIST', 'M U'' M'' U2 M U'' M'' ', '4M', 'U91a', 3,
        NULL, NULL, NULL, 5),
       ('l R D2 R'' U'' R D2 R'' U l''', 'l', 'A91a', 'U'' M'' U'' M U2 M'' U'' M U ', '4M', 'U91a', 3,
        'U'' R U R'' U'' l'' U l R U'' R'' U'' R U R'' F'' U', NULL, NULL, 6),
       ('U'' R2 D R'' U R D'' R'' U'' R'' U', 'URD+', 'Pure1b', 'R U R'' U'' M'' U R U'' r'' ', '8M', 'U81', 3, NULL,
        NULL, NULL, 7),
       ('U'' R'' U2 R'' D'' R U2 R'' D R2 U', 'URD+', 'A91c', 'M'' U'' L E'' L'' U'' L E L'' U2 M', '8E', 'U102c', 3,
        NULL, NULL, NULL, 8),
       ('R'' D'' U'' R'' D R U'' R'' D'' R D U2 R', 'URD+', 'A91a', 'S'' U L E'' L'' U'' L E L'' S ', '8E', 'U92a', 3,
        NULL, NULL, NULL, 9),
       ('U'' R2 D R'' U2 R D'' R'' U2 R'' U', 'URD+', 'A91c', 'U'' l'' U'' M U2 M'' U'' l U ', '4M', 'U102a', 3, NULL,
        NULL, NULL, 10),
       ('U'' R'' U'' R'' D'' R U R'' D R2 U', 'URD+', 'Pure1b', 'L'' M U'' M'' U2 M U'' M'' L ', '4M', 'U82b', 3, NULL,
        NULL, NULL, 11),
       ('R'' U'' l D2 l'' U R U'' F2 U', '4ins', 'A91b', 'D l'' U l S'' l'' U'' l S D'' ', '8S', 'U82i', 3, NULL, NULL,
        NULL, 12),
       ('R'' D R U'' R'' D'' R U', 'URD', 'Pure1b', 'M2 R U R'' U'' M U R U'' r'' ', '8M', 'U82h', 3, NULL, NULL, NULL,
        13),
       ('D R'' D'' R U'' R'' D R D'' U', 'URD+', 'Pure1a', 'l'' U l S'' l'' U'' l S ', '8S', 'U82h', 3, NULL, NULL,
        NULL, 14),
       ('D R D'' R2 D R U'' R'' D'' R U R D R'' D''', 'URD+', 'A91b', 'U'' S'' l U'' l'' S l U l'' U ', '8S', 'U82i', 3,
        NULL, NULL, NULL, 15),
       ('D'' R'' D R U'' R'' D'' R D U', 'URD+', 'Pure1a', 'l'' U l'' S l U'' l'' S'' l2 ', '8S', 'U92c', 3, NULL, NULL,
        NULL, 16),
       ('R'' D'' R U'' R'' D R U', 'URD', 'Pure1b', 'U S r U'' r'' S'' r U r'' U'' ', '8S', 'U82j', 3, NULL, NULL, NULL,
        17),
       ('R D'' R2 D R U'' R'' D'' R U R D R''', 'URD+', 'Pure2c', 'M R U R'' U'' M2 U R U'' r'' ', '8M', 'U82j', 3,
        NULL, NULL, NULL, 18),
       ('U'' R D R'' U'' R D'' R'' U2', 'URD+', 'Pure2a', 'M'' U'' M'' U'' M U'' M'' U'' M2 ', 'M,U/D', 'U92c', 3, NULL,
        NULL, NULL, 19),
       ('D'' R'' D'' R U'' R'' D R D U', 'URD+', 'Pure2b', 'U r'' U'' M'' U2 M U'' r U'' ', '4M', 'U102a', 3, NULL,
        NULL, NULL, 20),
       ('R'' D'' R2 U'' R'' D R U R'' D'' R'' D R', 'URD+', 'Pure2c', 'S'' U L'' E L U'' L'' E'' L S ', '8E', 'U82a', 3,
        NULL, NULL, NULL, 21),
       ('D R'' D R U'' R'' D'' R U D''', 'URD+', 'Pure2b', 'M'' U R E'' R'' U'' R E r'' ', '8E', 'U102b', 3, NULL, NULL,
        NULL, 22),
       ('U'' R D'' R'' U'' R D R'' U2', 'URD+', 'Pure2a', 'l U'' M'' U2 M U'' l'' ', '4M', 'U92b', 3, NULL, NULL, NULL,
        23),
       (NULL, NULL, NULL, 'M2 U'' M U2 M'' U'' M2 ', '4M', 'U101', 4, 'r B'' U2 R'' l'' U R U'' l U2 r'' U L U L''',
        NULL, NULL, 2),
       ('U'' R'' D'' R D R'' D'' R U R'' D R D'' R'' D R', 'UNDEF', 'TWIST', 'S l'' U l S'' l'' U'' l ', '8S', 'U81', 4,
        'U2 R'' F r2 U2 l'' U l U2 r'' L'' U L U'' r'' F'' R U2', NULL, NULL, 3),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 4, NULL, NULL, NULL, 4),
       ('R'' D'' R D R'' D'' R U'' R'' D R D'' R'' D R U', 'UNDEF', 'TWIST', 'l'' U'' L U l U2 L'' U'' L'' U L2 U2 L''',
        'UNDEF', 'TWIST', 4, NULL, NULL, NULL, 5),
       ('R2 D R'' U2 R D'' R'' U2 R''', 'URD+', 'A91c', 'U'' M2 U'' M U2 M'' U'' M2 U ', '4M', 'U101', 4, NULL, NULL,
        NULL, 6),
       ('R D'' U R'' D'' R U2 R'' D R U D R''', 'URD+', 'A91b', 'l U L'' U'' M'' U L U'' L'' ', '8M', 'U81', 4, NULL,
        NULL, NULL, 7),
       ('R'' U'' R2 D'' R2 D R2 U R2 D'' R2 D R''', '5ins', 'Cyclic', 'U2 R'' U'' R'' U'' R'' U R U R U''', 'R/L,U',
        'U82b', 4, NULL, NULL, NULL, 8),
       ('l'' R'' D2 R U2 R'' D2 R U2 l', 'l', 'A91b', 'U L E'' L'' U'' L E L'' ', '8E', 'U82a', 4, NULL, NULL, NULL, 9),
       ('l'' U'' R D'' R'' U2 R D R'' U'' l', 'l', 'A91c', 'U2 L U L U L'' U'' L'' U'' L'' U''', 'R/L,U', 'U92a', 4,
        NULL, NULL, NULL, 10),
       ('R U R'' D U R D R'' U2 R D'' R'' U D'' R U'' R''', 'URD+', 'Cyclic', 'U'' R'' E R U'' R'' E'' R U2 ', '8E',
        'U92a', 4, NULL, NULL, NULL, 11),
       ('D'' R2 D'' R'' U2 R D R'' U2 R'' D', 'URD+', 'A91b', 'M U2 M U'' M'' U2 M'' U ', 'M,U/D', 'U82d', 4, NULL,
        NULL, NULL, 12),
       ('R'' D F2 D'' R D l'' U2 l D''', '4ins', 'Cyclic', 'l'' U L U'' M U L'' U'' L ', '8M', 'U82e', 4, NULL, NULL,
        NULL, 13),
       ('R U R'' D R U2 R'' D'' R U R''', 'URD+', 'A91c', 'U R U R'' U'' R'' U'' R'' U R ', 'R/L,U', 'U82f', 4, NULL,
        NULL, NULL, 14),
       ('R'' D R D2 R U'' R'' D2 R U R2 D'' R', 'URD+', 'Cyclic', 'U'' R E R'' U'' R E'' R'' U2 ', '8E', 'U82g', 4,
        NULL, NULL, NULL, 15),
       ('D'' R'' D F2 D'' R D l'' U2 l', '4ins', 'A91b', 'U'' L U L'' U'' L'' U'' L'' U L U2 ', 'R/L,U', 'U82d', 4,
        NULL, NULL, NULL, 16),
       ('l'' R'' D'' R U2 R'' D R U2 l', 'l', 'A91c', 'U L'' E'' L U'' L'' E L ', '8E', 'U82e', 4, NULL, NULL, NULL,
        17),
       ('D R2 D'' R'' U2 R D R'' U2 R'' D''', 'URD+', 'Column', 'L'' U'' L U M U2 M'' U L'' U L ', '4M', 'U82f', 4,
        NULL, NULL, NULL, 18),
       ('l'' U'' R D R'' U2 R D'' R'' U'' l', 'l', 'A92', 'U'' M U'' M'' U'' M U'' M'' ', 'M,U/D', 'U82g', 4, NULL,
        NULL, NULL, 19),
       ('R U R'' D'' R U2 R'' D R U R''', 'URD+', 'A92', 'R U R U R'' U'' R'' U'' R'' U', 'R/L,U', 'U82c', 4, NULL,
        NULL, NULL, 20),
       ('R2 D'' R'' U2 R D R'' U2 R''', 'URD+', 'A92', 'U L'' E L U'' L'' E'' L ', '8E', 'U82c', 4, NULL, NULL, NULL,
        21),
       ('D R'' D F2 D'' R D l'' U2 l D2', '4ins', 'Column', 'L'' U'' L'' U'' L'' U L U L U', 'R/L,U', 'U82a', 4, NULL,
        NULL, NULL, 22),
       ('l'' R'' D R U2 R'' D'' R U2 l', 'l', 'A92', 'U'' R E'' R'' U'' R E R'' U2 ', '8E', 'U82b', 4, NULL, NULL, NULL,
        23),
       (NULL, NULL, NULL, 'r U'' r'' S'' r U r'' S ', '8S', 'U81', 5, 'L'' U R'' U'' R L U2 R'' U'' R U2', NULL, NULL,
        2),
       ('R'' D'' R D R'' D'' R U'' R'' D R D'' R'' D R U', 'UNDEF', 'TWIST', 'M U M'' U2 M U M'' ', '4M', 'U91a', 5,
        'U2 R2 r2 U2 l'' U l U2 r'' L'' U L U'' r'' R2 U2', NULL, NULL, 3),
       ('U'' R'' D'' R D R'' D'' R U R'' D R D'' R'' D R', 'UNDEF', 'TWIST', 'l'' U'' L U l U2 L'' U'' L'' U L2 U2 L''',
        'UNDEF', 'TWIST', 5, NULL, NULL, NULL, 4),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 5, NULL, NULL, NULL, 5),
       ('R'' U'' R'' D'' R U R'' D R2', 'URD+', 'Pure1b', 'U M'' U M U2 M'' U M U''', '4M', 'U91a', 5, NULL, NULL, NULL,
        6),
       ('R'' U L U'' R U L'' U''', 'LUR', 'Pure1a', 'L'' U'' L U M'' U'' L'' U l ', '8M', 'U81', 5, NULL, NULL, NULL,
        7),
       ('U'' R'' D U R D R'' U2 R D'' R'' U D'' R U', 'URD+', 'A91b', 'U r U M U2 M'' U r'' U'' ', '4M', 'U102a', 5,
        NULL, NULL, NULL, 8),
       ('U'' R D'' U R'' D'' R U2 R'' D R D U R'' U', 'URD+', 'A91b', 'R M U M'' U2 M U M'' R'' ', '4M', 'U82b', 5,
        NULL, NULL, NULL, 9),
       ('U'' R'' U L U'' R U L''', 'LUR', 'Pure1a', 'M'' U R'' E R U R'' E'' R U2 M', '8E', 'U102c', 5, NULL, NULL,
        NULL, 10),
       ('l U'' R'' D R U R'' D'' x', 'l', 'Pure1b', 'S U'' R'' E R U R'' E'' R S'' ', '8E', 'U92a', 5, NULL, NULL, NULL,
        11),
       ('U'' R'' U R U'' R'' D R U R'' D'' U'' R U', 'URD+', 'A91a', 'D'' r U'' r'' S r U r'' S'' D ', '8S', 'U82i', 5,
        NULL, NULL, NULL, 12),
       ('R'' U'' D R U R'' D'' R U'' R'' U R', 'URD+', 'Pure1b', 'M2 L'' U'' L U M U'' L'' U l ', '8M', 'U82h', 5, NULL,
        NULL, NULL, 13),
       ('D R'' U'' D'' R U R'' D R U'' R'' U R D''', 'URD+', 'A91c', 'r U'' r S'' r'' U r S r2 ', '8S', 'U92c', 5, NULL,
        NULL, NULL, 14),
       ('R U'' R2 D'' R U2 R'' D R U2 R U R''', 'URD+', 'A91c', 'U'' S'' l'' U l S l'' U'' l U ', '8S', 'U82j', 5, NULL,
        NULL, NULL, 15),
       ('R U L U'' R'' U L'' U''', 'LUR', 'Pure1b', 'r U'' r'' S r U r'' S'' ', '8S', 'U82h', 5, NULL, NULL, NULL, 16),
       ('R'' U'' D'' R U R'' D R U'' R'' U R', 'URD+', 'A91a', 'U S r'' U r S'' r'' U'' r U'' ', '8S', 'U82i', 5, NULL,
        NULL, NULL, 17),
       ('R U'' R'' D R'' U R D'' R'' U'' R2 U R''', 'URD+', 'Pure2c', 'M L'' U'' L U M2 U'' L'' U l ', '8M', 'U82j', 5,
        NULL, NULL, NULL, 18),
       ('R'' U'' R'' D'' R U2 R'' D R U'' R', 'URD+', 'Pure2b', 'M'' U M'' U M U M'' U M2 ', 'M,U/D', 'U92c', 5, NULL,
        NULL, NULL, 19),
       ('R2 U2 R D R'' U R D'' R'' U R2', 'URD+', 'Pure2a', 'M'' U'' L'' E L U L'' E'' l ', '8E', 'U102b', 5, NULL,
        NULL, NULL, 20),
       ('R2 D2 R U'' R'' D R U R'' D R2', 'URD+', 'Pure2a', 'r'' U M'' U2 M U r ', '4M', 'U92b', 5, NULL, NULL, NULL,
        21),
       ('l U2 R'' D R U2 R'' D'' x', 'l', 'Pure2b', 'U'' l U M'' U2 M U l'' U ', '4M', 'U102a', 5, NULL, NULL, NULL,
        22),
       ('U'' R U'' D'' R'' U R D R'' U'' R U R'' U', 'URD+', 'Pure2c', 'S U'' R E'' R'' U R E R'' S'' ', '8E', 'U82a',
        5, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'U M2 U'' M U2 M'' U'' M2 U''', '4M', 'U101', 6,
        'R U l'' U'' l U R'' U'' l'' U l R U'' R'' U''', NULL, NULL, 2),
       ('l U'' R D2 R'' U R D2 R'' l''', 'l', 'A91a', 'U'' M'' U M U2 M'' U M U ', '4M', 'U91a', 6,
        'S'' U'' R'' U2 R U2 l'' U l U R'' U'' l'' U'' l R S', NULL, NULL, 3),
       ('R U2 R D R'' U2 R D'' R2', 'URD+', 'A91c', 'U'' M2 U M U2 M'' U M2 U', '4M', 'U101', 6,
        'U'' R'' U2 R U2 l'' U l U R'' U'' l'' U'' l R', NULL, NULL, 4),
       ('R2 D'' R U'' R'' D R U R', 'URD+', 'Pure1b', 'U M'' U'' M U2 M'' U'' M U''', '4M', 'U91a', 6, NULL, NULL, NULL,
        5),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 6, 'R'' U'' F'' R U R'' U'' l'' U l R U'' R'' U'' R U R'' U R',
        NULL, NULL, 6),
       ('R D R'' D'' R D R'' U'' R D'' R'' D R D'' R'' U', 'UNDEF', 'TWIST', 'M'' U M'' U M'' U2 M U M U M U2', 'UNDEF',
        'TWIST', 6, NULL, NULL, NULL, 7),
       ('U'' R D R'' D'' R D R'' U R D'' R'' D R D'' R''', 'UNDEF', 'TWIST', 'R'' U S'' U2 S U R', '4S', 'U82i', 6,
        NULL, NULL, NULL, 8),
       ('l'' R'' D2 R U R'' D2 R U'' l', 'l', 'A91a', 'U L E'' L'' U2 L E L'' U ', '8E', 'U82d', 6, NULL, NULL, NULL,
        9),
       ('R U R D R'' U'' R D'' R2', 'URD+', 'Pure1b', 'L U'' S U2 S'' U'' L''', '4S', 'U82i', 6, NULL, NULL, NULL, 10),
       ('R2 D'' R U2 R'' D R U2 R', 'URD+', 'A91c', 'U'' R'' E R U2 R'' E'' R U'' ', '8E', 'U82d', 6, NULL, NULL, NULL,
        11),
       ('x'' D2 R U R'' D2 R U'' l''', 'l', 'Pure2c', 'U2 M'' U2 M ', '4M', 'U82n', 6, NULL, NULL, NULL, 12),
       ('R'' D R U R'' D'' R U''', 'URD', 'Pure2b', 'U M U'' M U2 M'' U'' M'' U'' ', '4M', 'U82o', 6, NULL, NULL, NULL,
        13),
       ('D R'' D'' R U R'' D R U'' D''', 'URD+', 'Pure2a', 'U S'' U2 S U', '4S', 'U82m', 6, NULL, NULL, NULL, 14),
       ('U'' R'' D R2 D'' R'' U R D R'' U'' R'' D'' R U', 'URD+', 'A91b', 'U'' R E R'' U2 R E'' R'' U'' ', '8E', 'U82k',
        6, NULL, NULL, NULL, 15),
       ('D'' R'' D R U R'' D'' R D U''', 'URD+', 'Pure1b', 'U'' S U2 S'' U''', '4S', 'U82m', 6, NULL, NULL, NULL, 16),
       ('R'' D'' R U R'' D R U''', 'URD', 'Pure1a', 'U L'' E'' L U2 L'' E L U ', '8E', 'U82k', 6, NULL, NULL, NULL, 17),
       ('U R D'' R'' U'' R'' D R U R'' D'' R2 D R'' U''', 'URD+', 'A91b', 'M U2 M'' U2 ', '4M', 'U82n', 6, NULL, NULL,
        NULL, 18),
       ('U'' R D R'' U R D'' R''', 'URD', 'Pure1a', 'U'' M'' U'' M'' U2 M U'' M U ', '4M', 'U82o', 6, NULL, NULL, NULL,
        19),
       ('U'' D R D'' R'' U R D R'' D''', 'URD+', 'Pure1b', 'R U S'' U2 S U R''', '4S', 'U82i', 6, NULL, NULL, NULL, 20),
       ('l'' U'' R D2 R'' U R D2 x''', 'l', 'Pure2c', 'U L'' E L U2 L'' E'' L U ', '8E', 'U82d', 6, NULL, NULL, NULL,
        21),
       ('D'' U'' R D R'' U R D'' R'' D', 'URD+', 'Pure2a', 'L'' U'' S U2 S'' U'' L', '4S', 'U82i', 6, NULL, NULL, NULL,
        22),
       ('U'' R D'' R'' U R D R''', 'URD', 'Pure2b', 'U'' R E'' R'' U2 R E R'' U'' ', '8E', 'U82d', 6, NULL, NULL, NULL,
        23),
       (NULL, NULL, NULL, 'R'' U'' R U M U'' R'' U r ', '8M', 'U81', 7, 'U R U'' R'' U2 L R U'' R'' U L'' U', NULL,
        NULL, 2),
       ('U'' R U R D R'' U'' R D'' R2 U', 'URD+', 'Pure1b', 'r U R'' U'' M U R U'' R'' ', '8M', 'U81', 7,
        'U R'' U r2 U2 l'' U l U2 r'' L'' U L U'' r'' U'' R U''', NULL, NULL, 3),
       ('R D'' U'' R'' D'' R U2 R'' D R U'' D R''', 'URD+', 'A91b', 'L U L'' U'' M U L U'' l'' ', '8M', 'U81', 7, NULL,
        NULL, NULL, 4),
       ('U L U'' R'' U L'' U'' R', 'LUR', 'Pure1a', 'l'' U'' L U M U'' L'' U L ', '8M', 'U81', 7, NULL, NULL, NULL, 5),
       ('U'' R D R'' D'' R D R'' U R D'' R'' D R D'' R''', 'UNDEF', 'TWIST', 'M'' U M'' U M'' U2 M U M U M U2', 'UNDEF',
        'TWIST', 7, NULL, NULL, NULL, 6),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 7, NULL, NULL, NULL, 7),
       ('R D R'' D'' R D R'' U'' R D'' R'' D R D'' R'' U', 'UNDEF', 'TWIST', 'U'' R U M U'' R'' U M'' ', '8M', 'U82h',
        7, NULL, NULL, NULL, 8),
       ('R'' D U'' R D R'' U2 R D'' R'' U'' D'' R', 'URD+', 'A91b', 'M'' U R U'' M U R'' U'' ', '8M', 'U82e', 7, NULL,
        NULL, NULL, 9),
       ('U R2 D'' R U'' R'' D R U R U''', 'URD+', 'Pure1b', 'U L'' U'' M U L U'' M'' ', '8M', 'U82h', 7, NULL, NULL,
        NULL, 10),
       ('R U'' L'' U R'' U'' L U', 'LUR', 'Pure1a', 'M'' U'' L'' U M U'' L U ', '8M', 'U82e', 7, NULL, NULL, NULL, 11),
       ('r D2 L'' U2 L D2 L'' U2 x''', 'r', 'Pure2c', 'U S l'' U'' l S'' l'' U l U'' ', '8S', 'U82o', 7, NULL, NULL,
        NULL, 12),
       ('R'' D U R U'' R'' D'' R U R'' U'' R', 'URD+', 'Pure2a', 'U'' l'' U'' l S l'' U l S'' U ', '8S', 'U92d', 7,
        NULL, NULL, NULL, 13),
       ('U L'' U'' R'' U L U'' R', 'LUR', 'Pure2b', 'R'' U'' R'' U M U'' R U r ', '8M', 'U82l', 7, NULL, NULL, NULL,
        14),
       ('U R'' U'' R U R'' D'' R U'' R'' D U R U''', 'URD+', 'A91c', 'r U R U'' M U R'' U'' R'' ', '8M', 'U82l', 7,
        NULL, NULL, NULL, 15),
       ('D'' R'' U D R U'' R'' D'' R U R'' U'' R D', 'URD+', 'A91a', 'L U L U'' M U L'' U'' l'' ', '8M', 'U82l', 7,
        NULL, NULL, NULL, 16),
       ('R'' D'' U R U'' R'' D R U R'' U'' R', 'URD+', 'Pure1b', 'l'' U'' L'' U M U'' L U L ', '8M', 'U82l', 7, NULL,
        NULL, NULL, 17),
       ('D R U'' R'' U R D'' R'' U'' R D U R'' D''', 'URD+', 'A91a', 'U S l U l'' S'' l U'' l'' U'' ', '8S', 'U92d', 7,
        NULL, NULL, NULL, 18),
       ('U'' R U D R'' U'' R D'' R'' U R U'' R'' U', 'URD+', 'A91c', 'U'' l U l'' S l U'' l'' S'' U ', '8S', 'U82o', 7,
        NULL, NULL, NULL, 19),
       ('R U'' R'' U R D R'' U'' R U D'' R''', 'URD+', 'Pure1b', 'U'' R'' U M U'' R U M'' ', '8M', 'U82e', 7, NULL,
        NULL, NULL, 20),
       ('R U'' R'' U R D'' R'' U'' R U D R''', 'URD+', 'Pure2a', 'M'' U R'' U'' M U R U'' ', '8M', 'U82h', 7, NULL,
        NULL, NULL, 21),
       ('x'' U2 L'' D2 L U2 L'' D2 r', 'r', 'Pure2c', 'U L U'' M U L'' U'' M'' ', '8M', 'U82e', 7, NULL, NULL, NULL,
        22),
       ('R U'' L U R'' U'' L'' U', 'LUR', 'Pure2b', 'M'' U'' L U M U'' L'' U ', '8M', 'U82h', 7, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'U'' R'' U'' R'' U'' R'' U R U R U2', 'R/L,U', 'U92a', 8,
        'U R'' U R U'' B r'' U L U2 R U'' R'' U x', NULL, NULL, 2),
       ('U'' R2 D'' R U2 R'' D R U2 R U', 'URD+', 'A91c', 'M'' U2 L E'' L'' U L E L'' U M', '8E', 'U102c', 8,
        'U R U F r2 U2 l'' U l U2 r'' L'' U L U'' r'' F'' U'' R'' U''', NULL, NULL, 3),
       ('R D'' R2 D R2 U'' R2 D'' R2 D R2 U R', '5ins', 'Cyclic', 'U R'' U'' R'' U'' R U R U R U2', 'R/L,U', 'U82b', 8,
        NULL, NULL, NULL, 4),
       ('U'' R'' D U'' R D R'' U2 R D'' R'' U'' D'' R U', 'URD+', 'A91b', 'U r U'' M U2 M'' U'' r'' U'' ', '4M',
        'U102a', 8, NULL, NULL, NULL, 5),
       ('R D R'' D'' R D R'' U'' R D'' R'' D R D'' R'' U', 'UNDEF', 'TWIST', 'R'' U'' S'' U2 S U'' R', '4S', 'U82i', 8,
        NULL, NULL, NULL, 6),
       ('U'' R D R'' D'' R D R'' U R D'' R'' D R D'' R''', 'UNDEF', 'TWIST', 'M U'' R U M'' U'' R'' U ', '8M', 'U82h',
        8, NULL, NULL, NULL, 7),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 8, NULL, NULL, NULL, 8),
       ('U R D'' U'' R'' D'' R U2 R'' D R U'' D R'' U''', 'URD+', 'A91b', 'R r U R'' U'' r'' U2 R U R U'' R2 U2',
        'UNDEF', 'TWIST', 8, NULL, NULL, NULL, 9),
       ('R U R2 D R2 D'' R2 U'' R2 D R2 D'' R', '5ins', 'Cyclic', 'R'' U'' R E R2 E'' R U R ', '4E', 'U91a', 8, NULL,
        NULL, NULL, 10),
       ('U R U2 R D R'' U2 R D'' R2 U''', 'URD+', 'A91c', 'R U'' R'' E R U R'' E'' ', '8E', 'U81', 8, NULL, NULL, NULL,
        11),
       ('U'' R2 D R U2 R'' D'' R U2 R U', 'URD+', 'Column', 'U R U M'' U2 M U R'' U'' ', '4M', 'U91a', 8, NULL, NULL,
        NULL, 12),
       ('U R U'' R'' D R U2 R'' D'' R U'' R'' U''', 'URD+', 'A92', 'M'' U'' R U M U'' R'' U ', '8M', 'U81', 8, NULL,
        NULL, NULL, 13),
       ('U D'' R U2 R D'' R'' U2 R D R2 D U''', 'URD+', 'A92', 'U R'' U'' R'' U R U R U R'' U2 ', 'R/L,U', 'U82b', 8,
        NULL, NULL, NULL, 14),
       ('U l'' U2 l D'' R'' D F2 D'' R D U''', '4ins', 'Cyclic', 'D'' M'' U'' R U M U'' R'' U D ', '8M', 'U102a', 8,
        NULL, NULL, NULL, 15),
       ('U'' R'' U'' R D R'' U2 R D'' R'' U'' R U', 'URD+', 'A91c', 'U L E'' L2 E L U'' ', '4E', 'U92b', 8, NULL, NULL,
        NULL, 16),
       ('U'' l U R'' D'' R U2 R'' D R U l'' U', 'l', 'A91b', 'D M'' U'' R U M U'' R'' U D'' ', '8M', 'U102b', 8, NULL,
        NULL, NULL, 17),
       ('U l'' U R D R'' U2 R D'' R'' U l U''', 'l', 'A91b', 'U R U'' M U2 M'' U'' R'' U'' ', '4M', 'U82j', 8, NULL,
        NULL, NULL, 18),
       ('U R U'' R'' D'' R U2 R'' D R U'' R'' U''', 'URD+', 'A91c', 'U2 M U R U'' M'' U R'' U ', '8M', 'U92c', 8, NULL,
        NULL, NULL, 19),
       ('U'' D R D'' B2 D R'' D'' l U2 l'' U', '4ins', 'Cyclic', 'U R'' S R2 S'' R'' U'' ', '4S', 'U82i', 8, NULL, NULL,
        NULL, 20),
       ('U'' D R2 D R U2 R'' D'' R U2 R D'' U', 'URD+', 'A92', 'R U'' R'' E'' R U R'' E ', '8E', 'U82h', 8, NULL, NULL,
        NULL, 21),
       ('U'' R'' U'' R D'' R'' U2 R D R'' U'' R U', 'URD+', 'A92', 'R'' U'' R'' E'' R2 E R'' U R ', '4E', 'U82j', 8,
        NULL, NULL, NULL, 22),
       ('U R U2 R D'' R'' U2 R D R2 U''', 'URD+', 'Column', 'R U'' R E'' R'' U R E R2 ', '8E', 'U92c', 8, NULL, NULL,
        NULL, 23),
       (NULL, NULL, NULL, 'U2 L E'' L'' U'' L E L'' U'' ', '8E', 'U92a', 9,
        'U2 F R U'' R'' U'' R U l'' U'' l U R'' U'' l'' U l F'' U2', NULL, NULL, 2),
       ('R'' U2 D'' R'' D R U R'' D'' R U D R', 'URD+', 'A91a', 'S'' L E'' L'' U L E L'' U'' S ', '8E', 'U92a', 9,
        'S'' L'' U2 L U2 R U'' L'' U R'' U R U'' L U R'' S', NULL, NULL, 3),
       ('l'' U2 R'' D2 R U2 R'' D2 R l', 'l', 'A91b', 'L E'' L'' U L E L'' U'' ', '8E', 'U82a', 9,
        'L'' U2 L U2 R U'' L'' U R'' U R U'' L U R''', NULL, NULL, 4),
       ('U'' R U'' D'' R'' D'' R U2 R'' D R U'' D R'' U', 'URD+', 'A91b', 'R M U'' M'' U2 M U'' M'' R'' ', '4M', 'U82b',
        9, NULL, NULL, NULL, 5),
       ('l'' U R'' D2 R U'' R'' D2 R l', 'l', 'A91a', 'U'' L E'' L'' U2 L E L'' U'' ', '8E', 'U82d', 9,
        'R U R'' U R U l'' U'' l U R'' U'' l'' U l R U'' R'' U2 R U'' R'' U2', NULL, NULL, 6),
       ('R'' D U R D R'' U2 R D'' R'' U D'' R', 'URD+', 'A91b', 'U R U'' M'' U R'' U'' M ', '8M', 'U82e', 9, NULL, NULL,
        NULL, 7),
       ('U R D'' U R'' D'' R U2 R'' D R U D R'' U''', 'URD+', 'A91b', 'R r U R'' U'' r'' U2 R U R U'' R2 U2', 'UNDEF',
        'TWIST', 9, NULL, NULL, NULL, 8),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 9, NULL, NULL, NULL, 9),
       ('U2 R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R', 'UNDEF', 'TWIST', 'E'' L'' U L E L'' U'' L ', '8E', 'U81', 9,
        NULL, NULL, NULL, 10),
       ('R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R U2', 'UNDEF', 'TWIST', 'u'' U2 R S R2 S'' R U2 u', '4S', 'U101',
        9, NULL, NULL, NULL, 11),
       ('l D'' l'' U'' R D R'' U2 R D'' R'' U'' l D l''', '2l', 'Special', 'u'' U'' M2 U R'' U'' M2 U R u ', '8M',
        'U101', 9, NULL, NULL, NULL, 12),
       ('R'' D R U2 R'' D'' R U2', 'URD', 'Pure3', 'M2 U R U'' M U R'' U'' M ', '8M', 'U81', 9, NULL, NULL, NULL, 13),
       ('D'' U'' R D'' R'' U2 R D R'' U'' D', 'URD+', 'Pure3', 'u U2 R'' E R2 E'' R'' U2 u'' ', '4E', 'U82b', 9, NULL,
        NULL, NULL, 14),
       ('R'' D R D'' R'' U R D2 R'' U'' R D'' R'' D'' R', 'URD+', 'Column', 'R'' U'' S U R U'' S'' U ', '?', 'U82a', 9,
        NULL, NULL, NULL, 15),
       ('D U'' R D R'' U2 R D'' R'' U'' D''', 'URD+', 'Pure2c', 'u'' U2 L'' E L2 E'' L'' U2 u ', '4E', 'U82c', 9, NULL,
        NULL, NULL, 16),
       ('R'' D'' R U2 R'' D R U2', 'URD', 'Pure2c', 'S L E'' L'' U L E L'' U'' S''', '8E', 'U82c', 9, NULL, NULL, NULL,
        17),
       ('R D'' R2 D R U2 R'' D'' R U2 R D R''', 'URD+', 'Special', 'M U R U'' M2 U R'' U'' M ', '8M', 'U82f', 9, NULL,
        NULL, NULL, 18),
       ('U'' R D R'' U2 R D'' R'' U''', 'URD+', 'Pure3', 'U M U'' L E'' L'' U L E l'' U'' ', '8E', 'U82g', 9, NULL,
        NULL, NULL, 19),
       ('D U'' R D'' R'' U2 R D R'' U'' D''', 'URD+', 'Pure3', 'E R'' U'' R E'' R'' U R ', '8E', 'U82e', 9, NULL, NULL,
        NULL, 20),
       ('R2 D'' B2 D R'' D'' l U2 l'' D R''', '4ins', 'Column', 'M'' U'' R'' S R2 S'' R'' U M', '4S', 'U82d', 9, NULL,
        NULL, NULL, 21),
       ('D'' U'' R D R'' U2 R D'' R'' U'' D', 'URD+', 'Pure2c', 'L2 E'' L'' U L E L'' U'' L'' ', '8E', 'U82g', 9, NULL,
        NULL, NULL, 22),
       ('U'' R D'' R'' U2 R D R'' U''', 'URD+', 'Pure2c', 'l R U'' M'' U2 M U'' R'' l'' ', '4M', 'U82f', 9, NULL, NULL,
        NULL, 23),
       (NULL, NULL, NULL, 'U'' L U L U L'' U'' L'' U'' L'' U2', 'R/L,U', 'U82b', 10,
        'U R'' U'' R U l'' U'' l U R'' U'' l'' U l R U2', NULL, NULL, 2),
       ('U'' R U2 R D R'' U2 R D'' R2 U', 'URD+', 'A91c', 'U'' l'' U M U2 M'' U l U ', '4M', 'U102a', 10,
        'U2 R'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' R U2', NULL, NULL, 3),
       ('l'' U R D'' R'' U2 R D R'' U l', 'l', 'A91c', 'U L U L U L U'' L'' U'' L'' U2', 'R/L,U', 'U92a', 10, NULL,
        NULL, NULL, 4),
       ('L U'' R'' U L'' U'' R U', 'LUR', 'Pure1a', 'M'' U2 R'' E R U'' R'' E'' R U'' M', '8E', 'U102c', 10, NULL, NULL,
        NULL, 5),
       ('R2 D R'' U R D'' R'' U'' R''', 'URD+', 'Pure1b', 'L U S U2 S'' U L''', '4S', 'U82i', 10, NULL, NULL, NULL, 6),
       ('U R'' U'' R'' D'' R U R'' D R2 U''', 'URD+', 'Pure1b', 'M U L'' U'' M'' U L U'' ', '8M', 'U82h', 10, NULL,
        NULL, NULL, 7),
       ('R'' D R2 D'' R2 U R2 D R2 D'' R2 U'' R''', '5ins', 'Cyclic', 'R'' U'' R'' E R2 E'' R'' U R ', '4E', 'U91a', 10,
        NULL, NULL, NULL, 8),
       ('R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R U2', 'UNDEF', 'TWIST', 'L'' U L E'' L'' U'' L E ', '8E', 'U81',
        10, NULL, NULL, NULL, 9),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 10, NULL, NULL, NULL, 10),
       ('U2 R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R', 'UNDEF', 'TWIST', 'L'' l'' U'' L U l U2 L'' U'' L'' U L2 U2',
        'UNDEF', 'TWIST', 10, NULL, NULL, NULL, 11),
       ('D'' R2 D'' R'' U R D R'' U'' R'' D', 'URD+', 'Pure3', 'U'' L'' U'' M'' U2 M U'' L U ', '4M', 'U91a', 10, NULL,
        NULL, NULL, 12),
       ('U R'' U'' R'' D R U R'' D'' R2 U''', 'URD+', 'Pure3', 'M'' U L'' U'' M U L U'' ', '8M', 'U81', 10, NULL, NULL,
        NULL, 13),
       ('R U R'' D R U R'' D'' R U2 R''', 'URD+', 'Orth', 'U'' R'' E R2 E'' R'' U ', '4E', 'U92b', 10, NULL, NULL, NULL,
        14),
       ('D2 R2 D'' R'' U R D R'' U'' R'' D2', 'URD+', 'A92', 'D'' M'' U L'' U'' M U L U'' D ', '8M', 'U102b', 10, NULL,
        NULL, NULL, 15),
       ('R U R2 D'' R U'' R'' D R U R U'' R''', 'URD+', 'Pure2b', 'U'' L U L U'' L'' U'' L'' U'' L U2 ', 'R/L,U',
        'U82b', 10, NULL, NULL, NULL, 16),
       ('l'' D2 R U R'' D2 R U'' x''', 'l', 'Pure2a', 'D M'' U L'' U'' M U L U'' D'' ', '8M', 'U102a', 10, NULL, NULL,
        NULL, 17),
       ('D R2 D'' R'' U R D R'' U'' R'' D''', 'URD+', 'Pure3', 'U'' L'' U M U2 M'' U L U ', '4M', 'U82j', 10, NULL,
        NULL, NULL, 18),
       ('U'' R2 U'' R'' D'' R U R'' D R'' U', 'URD+', 'Pure3', 'U2 M U'' L'' U M'' U'' L U'' ', '8M', 'U92c', 10, NULL,
        NULL, NULL, 19),
       ('R U R'' D'' R U R'' D R U2 R''', 'URD+', 'Orth', 'R U'' R'' E R2 E'' R'' U R'' ', '4E', 'U82j', 10, NULL, NULL,
        NULL, 20),
       ('R2 D'' R'' U R D R'' U'' R''', 'URD+', 'Pure2b', 'L'' U L'' E L U'' L'' E'' L2 ', '8E', 'U92c', 10, NULL, NULL,
        NULL, 21),
       ('U D R'' U'' R'' D R U R'' D'' R2 D'' U''', 'URD+', 'A92', 'U'' L S'' L2 S L U ', '4S', 'U82i', 10, NULL, NULL,
        NULL, 22),
       ('R D'' R D R'' U R D'' R'' U'' D R''', 'URD+', 'Pure2a', 'L'' U L E L'' U'' L E'' ', '8E', 'U82h', 10, NULL,
        NULL, NULL, 23),
       (NULL, NULL, NULL, 'R'' E R U'' R'' E'' R U ', '8E', 'U82a', 11, 'L U L'' U'' r U r'' U'' L U r U'' r'' L'' U',
        NULL, NULL, 2),
       ('U'' R2 D'' R U'' R'' D R U R U', 'URD+', 'Pure1b', 'L'' M U M'' U2 M U M'' L ', '4M', 'U82b', 11,
        'U R2 U r2 U2 l'' U l U2 r'' L'' U L U'' r'' U'' R2 U''', NULL, NULL, 3),
       ('R U R'' D U'' R D R'' U2 R D'' R'' U'' D'' R U'' R''', 'URD+', 'Cyclic', 'U2 R'' E R U R'' E'' R U ', '8E',
        'U92a', 11, NULL, NULL, NULL, 4),
       ('x'' D R U'' R'' D'' R U l''', 'l', 'Pure1b', 'S R'' E R U'' R'' E'' R U S'' ', '8E', 'U92a', 11, NULL, NULL,
        NULL, 5),
       ('R'' U2 R'' D'' R U2 R'' D R2', 'URD+', 'A91c', 'U R'' E R U2 R'' E'' R U ', '8E', 'U82d', 11, NULL, NULL, NULL,
        6),
       ('U'' L'' U R U'' L U R''', 'LUR', 'Pure1a', 'U'' L'' U M'' U'' L U M ', '8M', 'U82e', 11, NULL, NULL, NULL, 7),
       ('U R2 D R'' U2 R D'' R'' U2 R'' U''', 'URD+', 'A91c', 'E R U'' R'' E'' R U R'' ', '8E', 'U81', 11, NULL, NULL,
        NULL, 8),
       ('U2 R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R', 'UNDEF', 'TWIST', 'u'' U2 R'' S R2 S'' R'' U2 u', '4S',
        'U101', 11, NULL, NULL, NULL, 9),
       ('R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R U2', 'UNDEF', 'TWIST', 'L'' l'' U'' L U l U2 L'' U'' L'' U L2 U2',
        'UNDEF', 'TWIST', 11, NULL, NULL, NULL, 10),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 11, NULL, NULL, NULL, 11),
       ('U'' R2 D R U'' R'' D'' R U R U', 'URD+', 'Pure3', 'u'' U'' M2 U R U'' M2 U R'' u ', '8M', 'U101', 11, NULL,
        NULL, NULL, 12),
       ('l U'' l'' U R'' D R U'' R'' D'' R l U l''', 'URD+', 'Orth', 'M2 U'' L'' U M U'' L U M ', '8M', 'U81', 11, NULL,
        NULL, NULL, 13),
       ('D R2 U R D R'' U'' R D'' R D''', 'URD+', 'Pure3', 'u U2 R E'' R2 E R U2 u'' ', '4E', 'U82c', 11, NULL, NULL,
        NULL, 14),
       ('U'' D'' R2 D R U'' R'' D'' R U R D U', 'URD+', 'A92', 'S'' R'' E R U'' R'' E'' R U S', '8E', 'U82c', 11, NULL,
        NULL, NULL, 15),
       ('U'' R'' U'' R D R'' U'' R D'' R'' U2 R U', 'URD+', 'Pure2a', 'u'' U2 L E'' L2 E L U2 u ', '4E', 'U82b', 11,
        NULL, NULL, NULL, 16),
       ('R2 U R D R'' U'' R D'' R', 'URD+', 'Pure2b', 'L U S'' U'' L'' U S U'' ', '?', 'U82a', 11, NULL, NULL, NULL,
        17),
       ('U R D'' R U'' R'' D R U R2 U''', 'URD+', 'Pure3', 'M U'' L'' U M2 U'' L U M ', '8M', 'U82f', 11, NULL, NULL,
        NULL, 18),
       ('R'' U2 R'' D'' R U'' R'' D R U'' R', 'URD+', 'Orth', 'U'' M U R'' E R U'' R'' E'' r U ', '8E', 'U82g', 11,
        NULL, NULL, NULL, 19),
       ('D'' R2 U R D R'' U'' R D'' R D', 'URD+', 'Pure3', 'R2 E R U'' R'' E'' R U R ', '8E', 'U82g', 11, NULL, NULL,
        NULL, 20),
       ('R2 U D'' R'' U'' R D R'' U R U'' R2', 'URD+', 'Pure2b', 'r'' L'' U M'' U2 M U L r ', '4M', 'U82f', 11, NULL,
        NULL, NULL, 21),
       ('x'' U L'' D2 L U'' L'' D2 r', 'r', 'Pure2a', 'E'' L U L'' E L U'' L'' ', '8E', 'U82e', 11, NULL, NULL, NULL,
        22),
       ('U2 R U R D'' R'' U'' R D R2 U2', 'URD+', 'A92', 'M'' U L S'' L2 S L U'' M', '4S', 'U82d', 11, NULL, NULL, NULL,
        23),
       (NULL, NULL, NULL, 'U M U2 M U'' M'' U2 M'' ', 'M,U/D', 'U82d', 12, 'U'' F2 l2 U R U'' l U2 r'' U L U', NULL,
        NULL, 2),
       ('U'' F2 U R'' U'' l D2 l'' U R', '4ins', 'A91b', 'D S'' l'' U l S l'' U'' l D'' ', '8S', 'U82i', 12,
        'U2 F'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' F U2', NULL, NULL, 3),
       ('D'' R U2 R D'' R'' U2 R D R2 D', 'URD+', 'A91b', 'U'' M U2 M U M'' U2 M'' ', 'M,U/D', 'U82d', 12, NULL, NULL,
        NULL, 4),
       ('U'' R'' U D R U'' R'' D'' R U R'' U'' R U', 'URD+', 'A91a', 'D'' S r U'' r'' S'' r U r'' D ', '8S', 'U82i', 12,
        NULL, NULL, NULL, 5),
       ('l U R'' D2 R U'' R'' D2 x', 'l', 'Pure2c', 'M'' U2 M U2 ', '4M', 'U82n', 12, NULL, NULL, NULL, 6),
       ('x U2 L D2 L'' U2 L D2 r''', 'r', 'Pure2c', 'U l'' U'' l S l'' U l S'' U'' ', '8S', 'U82o', 12, NULL, NULL,
        NULL, 7),
       ('U'' R'' U2 R'' D R U2 R'' D'' R2 U', 'URD+', 'Column', 'U R U'' M'' U2 M U'' R'' U'' ', '4M', 'U91a', 12, NULL,
        NULL, NULL, 8),
       ('l D'' l'' U R D R'' U2 R D'' R'' U l D l''', '2l', 'Special', 'u'' R'' U'' M2 U R U'' M2 U u ', '8M', 'U101',
        12, NULL, NULL, NULL, 9),
       ('D'' R U R D'' R'' U'' R D R2 D', 'URD+', 'Pure3', 'U'' L'' U M'' U2 M U L U ', '4M', 'U91a', 12, NULL, NULL,
        NULL, 10),
       ('U'' R'' U'' R'' D R U R'' D'' R2 U', 'URD+', 'Pure3', 'u'' R U'' M2 U R'' U'' M2 U u ', '8M', 'U101', 12, NULL,
        NULL, NULL, 11),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 12, NULL, NULL, NULL, 12),
       ('R'' D R U R'' U'' R U R'' D'' R U'' R'' U R U''', 'UNDEF', 'TWIST', 'U M U M U2 M'' U M'' U M'' U2 M', 'UNDEF',
        'TWIST', 12, NULL, NULL, NULL, 13),
       ('U R'' U'' R U R'' D R U'' R'' U R U'' R'' D'' R', 'UNDEF', 'TWIST', 'l'' U l S'' l'' U2 l S l'' U l ', '8S',
        'U82d', 12, NULL, NULL, NULL, 14),
       ('U'' R'' U R D R U'' R'' D'' R U R2 U'' R U', 'URD+', 'A91b', 'l'' U'' S'' U2 S U'' l', '4S', 'U82i', 12, NULL,
        NULL, NULL, 15),
       ('l D2 l'' U R U'' F2 U R'' U''', '4ins', 'A91b', 'r U'' r'' S r U2 r'' S'' r U'' r'' ', '8S', 'U82d', 12, NULL,
        NULL, NULL, 16),
       ('R D R'' D'' R U R'' D R U'' D'' R''', 'URD+', 'A91a', 'r U S U2 S'' U r''', '4S', 'U82i', 12, NULL, NULL, NULL,
        17),
       ('R U'' R'' D2 R'' U R D2 R'' U'' R2 U R''', '4ins', 'Special', 'D2 M D2 M'' ', '4M', 'U82n', 12, NULL, NULL,
        NULL, 18),
       ('U'' R'' U R'' D R U'' R'' D'' R2 U', 'URD+', 'Pure3', 'D'' S'' l D l'' S l D'' l'' D ', '8S', 'U82o', 12, NULL,
        NULL, NULL, 19),
       ('D'' R U'' R D'' R'' U R D R2 D', 'URD+', 'Pure3', 'U R'' U'' M'' U2 M U'' R U'' ', '4M', 'U82k', 12, NULL,
        NULL, NULL, 20),
       ('x U2 L D L'' U2 L D'' r''', 'r', 'Pure2c', 'r U'' S'' U2 S U'' r''', '4S', 'U82m', 12, NULL, NULL, NULL, 21),
       ('l U2 R'' D2 R U2 R'' D2 x', 'l', 'Pure2c', 'U'' L U M'' U2 M U L'' U ', '4M', 'U82k', 12, NULL, NULL, NULL,
        22),
       ('R D R'' D'' R U R'' D2 R U'' R'' D'' R D'' R''', 'URD+', 'Column', 'l'' U S U2 S'' U l', '4S', 'U82m', 12,
        NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'R U'' R'' U M'' U'' R U r'' ', '8M', 'U82e', 13,
        'D U R U'' R U l'' U'' l U R'' U'' l'' U l R U'' R2 U'' D''', NULL, NULL, 2),
       ('U'' R'' D R U R'' D'' R', 'URD', 'Pure1b', 'r U R'' U'' M'' U R U'' R'' M2 ', '8M', 'U82h', 13,
        'U2 D2 R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' D2 U2', NULL, NULL, 3),
       ('D l'' U2 l D'' R'' D F2 D'' R', '4ins', 'Cyclic', 'L'' U L U'' M'' U L'' U'' l ', '8M', 'U82e', 13, NULL, NULL,
        NULL, 4),
       ('R'' U'' R U R'' D R U'' R'' D'' U R', 'URD+', 'Pure1b', 'l'' U'' L U M'' U'' L'' U L M2 ', '8M', 'U82h', 13,
        NULL, NULL, NULL, 5),
       ('U R'' D R U'' R'' D'' R', 'URD', 'Pure2b', 'U M U M U2 M'' U M'' U'' ', '4M', 'U82o', 13, NULL, NULL, NULL, 6),
       ('R'' U R U'' R'' D R U R'' U'' D'' R', 'URD+', 'Pure2a', 'U'' S l'' U'' l S'' l'' U l U ', '8S', 'U92d', 13,
        NULL, NULL, NULL, 7),
       ('U R U R'' D R U2 R'' D'' R U R'' U''', 'URD+', 'A92', 'U'' R U M'' U'' R'' U M ', '8M', 'U81', 13, NULL, NULL,
        NULL, 8),
       ('U2 R'' D R U2 R'' D'' R', 'URD', 'Pure3', 'M'' U R U'' M'' U R'' U'' M2 ', '8M', 'U81', 13, NULL, NULL, NULL,
        9),
       ('U R2 D R U'' R'' D'' R U R U''', 'URD+', 'Pure3', 'U L'' U'' M'' U L U'' M ', '8M', 'U81', 13, NULL, NULL,
        NULL, 10),
       ('l U'' l'' R'' D R U R'' D'' R U'' l U l''', 'URD+', 'Orth', 'M'' U'' L'' U M'' U'' L U M2 ', '8M', 'U81', 13,
        NULL, NULL, NULL, 11),
       ('U R'' U'' R U R'' D R U'' R'' U R U'' R'' D'' R', 'UNDEF', 'TWIST', 'U M U M U2 M'' U M'' U M'' U2 M', 'UNDEF',
        'TWIST', 13, NULL, NULL, NULL, 12),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 13, NULL, NULL, NULL, 13),
       ('R'' D R U R'' U'' R U R'' D'' R U'' R'' U R U''', 'UNDEF', 'TWIST', 'R U'' R U M'' U'' R'' U r'' ', '8M',
        'U82h', 13, NULL, NULL, NULL, 14),
       ('R'' D R D2 R U R'' D2 R U'' R2 D'' R', 'URD+', 'A91c', 'U'' S'' l'' U'' l S l'' U l U ', '8S', 'U82e', 13,
        NULL, NULL, NULL, 15),
       ('D U R U'' R'' D'' R U R'' U''', 'URD+', 'Pure1a', 'L'' U L'' U'' M'' U L U'' l ', '8M', 'U82h', 13, NULL, NULL,
        NULL, 16),
       ('U R'' D R U'' R'' D2 R U R'' D R U''', 'URD+', 'A91c', 'U S r U r'' S'' r U'' r'' U'' ', '8S', 'U82e', 13,
        NULL, NULL, NULL, 17),
       ('U R D R U'' R'' D'' R U R2 U''', 'URD+', 'Pure3', 'D l D l'' S'' l D'' l'' S D'' ', '8S', 'U92d', 13, NULL,
        NULL, NULL, 18),
       ('U D R U'' R'' D2 R U R'' D U''', 'URD+', 'Pure3', 'U M'' U'' M U2 M U M'' U ', 'M,U/D', 'U82o', 13, NULL, NULL,
        NULL, 19),
       ('R'' D R'' U'' R D R'' U R D2 R', 'URD+', 'Orth', 'U'' R'' U M'' U'' R U M ', '8M', 'U82l', 13, NULL, NULL,
        NULL, 20),
       ('D U R U'' F2 U R'' U'' l D2 l'' D''', '4ins', 'A92', 'M'' U R'' U'' M'' U R U'' M2 ', '8M', 'U82l', 13, NULL,
        NULL, NULL, 21),
       ('U L'' U'' L D L'' U L D'' U''', 'ULD+', 'Pure2a', 'U L U'' M'' U L'' U'' M ', '8M', 'U82l', 13, NULL, NULL,
        NULL, 22),
       ('R'' D R D R U R'' D'' R U'' R2 D'' R', 'URD+', 'Pure2b', 'M'' U'' L U M'' U'' L'' U M2 ', '8M', 'U82l', 13,
        NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'U2 R U R'' U'' R'' U'' R'' U R U'' ', 'R/L,U', 'U82d', 14,
        'L'' U L'' U'' r U r'' U'' L U r U'' r'' L'' U L2', NULL, NULL, 2),
       ('U'' D R'' D'' R U R'' D R D''', 'URD+', 'Pure1a', 'S'' l'' U l S l'' U'' l ', '8S', 'U82h', 14,
        'U2 D r2 U2 l'' U l U2 r'' L'' U L U'' r'' D'' U2', NULL, NULL, 3),
       ('R U'' R'' D R U2 R'' D'' R U'' R''', 'URD+', 'A91c', 'R'' U'' R U R U R U'' R'' U'' ', 'R/L,U', 'U82f', 14,
        NULL, NULL, NULL, 4),
       ('D R'' U'' R U R'' D'' R U'' R'' D U R D''', 'URD+', 'A91c', 'r2 S'' r'' U'' r S r'' U r'' ', '8S', 'U92c', 14,
        NULL, NULL, NULL, 5),
       ('D U R'' D'' R U'' R'' D R D''', 'URD+', 'Pure2a', 'U'' S'' U2 S U''', '4S', 'U82m', 14, NULL, NULL, NULL, 6),
       ('R'' U L'' U'' R U L U''', 'LUR', 'Pure2b', 'r'' U'' R'' U M'' U'' R U R ', '8M', 'U82l', 14, NULL, NULL, NULL,
        7),
       ('U D'' R2 D'' R'' U2 R D R'' U2 R'' D U''', 'URD+', 'A92', 'U2 R U'' R'' U'' R'' U'' R U R U'' ', 'R/L,U',
        'U82b', 14, NULL, NULL, NULL, 8),
       ('D'' U R D'' R'' U2 R D R'' U D', 'URD+', 'Pure3', 'u U2 R E R2 E'' R U2 u'' ', '4E', 'U82b', 14, NULL, NULL,
        NULL, 9),
       ('R U2 R'' D R U'' R'' D'' R U'' R''', 'URD+', 'Orth', 'U'' R E R2 E'' R U ', '4E', 'U92b', 14, NULL, NULL, NULL,
        10),
       ('D R'' D R'' U R D'' R'' U'' R2 D''', 'URD+', 'Pure3', 'u U2 R'' E'' R2 E R'' U2 u'' ', '4E', 'U82c', 14, NULL,
        NULL, NULL, 11),
       ('R'' D R U R'' U'' R U R'' D'' R U'' R'' U R U''', 'UNDEF', 'TWIST', 'l'' U'' l S'' l'' U2 l S l'' U'' l ',
        '8S', 'U82d', 14, NULL, NULL, NULL, 12),
       ('U R'' U'' R U R'' D R U'' R'' U R U'' R'' D'' R', 'UNDEF', 'TWIST', 'r U'' R U M U'' R'' U R'' ', '8M', 'U82h',
        14, NULL, NULL, NULL, 13),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 14, NULL, NULL, NULL, 14),
       ('R U'' R2 D R U2 R'' D'' R U2 R U R''', 'URD+', 'Cyclic', 'D'' U M U M U2 M'' U M'' U M'' U2 M D', 'UNDEF',
        'TWIST', 14, NULL, NULL, NULL, 15),
       ('R U L'' U'' R'' U L U''', 'LUR', 'Pure1b', 'D M D2 M'' D ', '4M', 'U82m', 14, NULL, NULL, NULL, 16),
       ('D R U R'' D'' R U'' R''', 'URD', 'Pure1b', 'S r'' D'' r S'' r'' D r ', '8S', 'U82l', 14, NULL, NULL, NULL, 17),
       ('D R2 D'' R'' U'' R D R'' U R'' D''', 'URD+', 'Pure3', 'U R2 U'' M U2 M'' U'' R2 U'' ', '4M', 'U82f', 14, NULL,
        NULL, NULL, 18),
       ('R D2 R'' U'' R D'' R'' U R D'' R''', 'URD+', 'Orth', 'U2 M U R2 U'' M'' U R2 U ', '8M', 'U92c', 14, NULL, NULL,
        NULL, 19),
       ('L'' U L D2 L'' U'' L D2', 'ULD', 'Pure3', 'R'' U R U R U R'' U'' R'' U'' ', 'R/L,U', 'U82c', 14, NULL, NULL,
        NULL, 20),
       ('l'' D R'' D'' R U'' R'' D R U D'' l', 'l', 'Pure2a', 'u'' R'' E'' R2 E R'' u ', '4E', 'U92b', 14, NULL, NULL,
        NULL, 21),
       ('D'' R D'' R'' U'' R D2 R'' U R D'' R'' D', 'URD+', 'A92', 'U'' R'' E'' R2 E R'' U ', '4E', 'U93', 14, NULL,
        NULL, NULL, 22),
       ('L'' U L D L'' U'' L D''', 'ULD', 'Pure2b', 'u'' R E R2 E'' R u ', '4E', 'U93', 14, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'R E R'' U'' R E'' R'' U ', '8E', 'U82e', 15, 'D'' U'' F2 l2 U R U'' l U2 r'' U L U D', NULL,
        NULL, 2),
       ('D R D'' R'' U'' R'' D R U R'' D'' R2 D R'' D''', 'URD+', 'A91b', 'U'' l U'' l'' S'' l U l'' S U ', '8S',
        'U82i', 15, 'U2 F'' R'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' R F U2', NULL, NULL, 3),
       ('R'' D R2 U'' R'' D2 R U R'' D2 R'' D'' R', 'URD+', 'Cyclic', 'U2 R E R'' U R E'' R'' U ', '8E', 'U82g', 15,
        NULL, NULL, NULL, 4),
       ('R U'' R'' U2 R'' D'' R U2 R'' D R2 U R''', 'URD+', 'A91c', 'U'' l'' U l S'' l'' U'' l S U ', '8S', 'U82j', 15,
        NULL, NULL, NULL, 5),
       ('U'' R'' D R U R D'' R'' U'' R D R2 D'' R U', 'URD+', 'A91b', 'U R E R'' U2 R E'' R'' U ', '8E', 'U82k', 15,
        NULL, NULL, NULL, 6),
       ('U R'' U'' D'' R U R'' D R U'' R'' U R U''', 'URD+', 'A91c', 'R U R U'' M'' U R'' U'' r'' ', '8M', 'U82l', 15,
        NULL, NULL, NULL, 7),
       ('U D'' R'' D F2 D'' R D l'' U2 l U''', '4ins', 'Cyclic', 'D'' U'' R U M'' U'' R'' U M D ', '8M', 'U102a', 15,
        NULL, NULL, NULL, 8),
       ('R'' D R D R'' U R D2 R'' U'' R D R'' D'' R', 'URD+', 'Column', 'U'' S U R'' U'' S'' U R ', '?', 'U82a', 15,
        NULL, NULL, NULL, 9),
       ('D2 R U R D'' R'' U'' R D R2 D2', 'URD+', 'A92', 'D'' U L'' U'' M'' U L U'' M D ', '8M', 'U102b', 15, NULL,
        NULL, NULL, 10),
       ('U'' D'' R'' U'' R'' D R U R'' D'' R2 D U', 'URD+', 'A92', 'S'' U'' R'' E R U R'' E'' R S', '8E', 'U82c', 15,
        NULL, NULL, NULL, 11),
       ('U'' R'' U R2 U'' R'' D R U R'' D'' R'' U'' R U', 'URD+', 'A91b', 'l'' U S'' U2 S U l', '4S', 'U82i', 15, NULL,
        NULL, NULL, 12),
       ('R'' D R2 U R'' D2 R U'' R'' D2 R'' D'' R', 'URD+', 'A91c', 'U'' l'' U'' l S'' l'' U l S U ', '8S', 'U82e', 15,
        NULL, NULL, NULL, 13),
       ('R U'' R'' U2 R'' D R U2 R'' D'' R2 U R''', 'URD+', 'Cyclic', 'D'' U M U M U2 M'' U M'' U M'' U2 M D', 'UNDEF',
        'TWIST', 15, NULL, NULL, NULL, 14),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 15, NULL, NULL, NULL, 15),
       ('R'' D'' R U R'' U'' R U R'' D R U'' R'' U R U''', 'UNDEF', 'TWIST', 'l D l'' S'' l D'' l'' S ', '8S', 'U82l',
        15, NULL, NULL, NULL, 16),
       ('U R'' U'' R U R'' D'' R U'' R'' U R U'' R'' D R', 'UNDEF', 'TWIST', 'M'' D'' M'' D2 M D'' M ', '4M', 'U82k',
        15, NULL, NULL, NULL, 17),
       ('D R U'' R2 U R D'' R'' U'' R D R U R'' D''', 'URD+', 'A91b', 'U'' S l'' D l S'' l'' D'' l U ', '8S', 'U82j',
        15, NULL, NULL, NULL, 18),
       ('D'' l D2 l'' U R U'' F2 U R'' U'' D', '4ins', 'Cyclic', 'M D'' M'' D'' M D'' M'' D'' ', 'M,U/D', 'U82g', 15,
        NULL, NULL, NULL, 19),
       ('D'' R D R'' D'' R U R'' D R U'' D'' R'' D', 'URD+', 'A91c', 'D'' U'' R'' U M'' U'' R U M D ', '8M', 'U102b',
        15, NULL, NULL, NULL, 20),
       ('R U'' R'' U R D'' R'' U2 R D R'' U R U R''', 'URD+', 'Column', 'U'' S U R U'' S'' U R'' ', '?', 'U82a', 15,
        NULL, NULL, NULL, 21),
       ('D'' U'' R'' U R'' D R U'' R'' D'' R2 U D', 'URD+', 'A92', 'D'' U L U'' M'' U L'' U'' M D ', '8M', 'U103', 15,
        NULL, NULL, NULL, 22),
       ('D2 R U'' R D'' R'' U R D R2 D2', 'URD+', 'A92', 'S'' U'' R E'' R'' U R E R'' S', '8E', 'U93', 15, NULL, NULL,
        NULL, 23),
       (NULL, NULL, NULL, 'L U L'' U'' L'' U'' L'' U L U ', 'R/L,U', 'U82f', 16,
        'U R U'' R U l'' U'' l U R'' U'' l'' U l R U'' R2 U''', NULL, NULL, 2),
       ('U'' D'' R'' D R U R'' D'' R D', 'URD+', 'Pure1a', 'l2 S l U l'' S'' l U'' l ', '8S', 'U92c', 16,
        'U2 D R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' D'' U2', NULL, NULL, 3),
       ('l'' U2 l D'' R'' D F2 D'' R D', '4ins', 'A91b', 'U2 L'' U'' L U L U L U'' L'' U ', 'R/L,U', 'U82d', 16, NULL,
        NULL, NULL, 4),
       ('U L U'' R U L'' U'' R''', 'LUR', 'Pure1b', 'S r U'' r'' S'' r U r'' ', '8S', 'U82h', 16, NULL, NULL, NULL, 5),
       ('U D'' R'' D R U'' R'' D'' R D', 'URD+', 'Pure1b', 'U S U2 S'' U', '4S', 'U82m', 16, NULL, NULL, NULL, 6),
       ('D'' R'' U R U'' R'' D R U R'' D'' U'' R D', 'URD+', 'A91a', 'l U L U'' M'' U L'' U'' L'' ', '8M', 'U82l', 16,
        NULL, NULL, NULL, 7),
       ('U'' R'' U R D R'' U2 R D'' R'' U R U', 'URD+', 'A91c', 'U L'' E'' L2 E L'' U'' ', '4E', 'U92b', 16, NULL, NULL,
        NULL, 8),
       ('D U R D R'' U2 R D'' R'' U D''', 'URD+', 'Pure2c', 'u'' U2 L E L2 E'' L U2 u ', '4E', 'U82c', 16, NULL, NULL,
        NULL, 9),
       ('R U R'' U'' R'' D'' R U R'' D R2 U'' R''', 'URD+', 'Pure2b', 'U2 L'' U L U L U L'' U'' L'' U ', 'R/L,U',
        'U82b', 16, NULL, NULL, NULL, 10),
       ('U'' R'' U2 R D R'' U R D'' R'' U R U', 'URD+', 'Pure2a', 'u'' U2 L'' E'' L2 E L'' U2 u ', '4E', 'U82b', 16,
        NULL, NULL, NULL, 11),
       ('U R U'' F2 U R'' U'' l D2 l''', '4ins', 'A91b', 'r U r'' S r U2 r'' S'' r U r'' ', '8S', 'U82d', 16, NULL,
        NULL, NULL, 12),
       ('U R U'' R'' D R U R'' U'' D''', 'URD+', 'Pure1a', 'l'' U L'' U'' M U L U'' L ', '8M', 'U82h', 16, NULL, NULL,
        NULL, 13),
       ('U L'' U'' R U L U'' R''', 'LUR', 'Pure1b', 'D'' M D2 M'' D'' ', '4M', 'U82m', 16, NULL, NULL, NULL, 14),
       ('U R'' U'' R U R'' D'' R U'' R'' U R U'' R'' D R', 'UNDEF', 'TWIST', 'S'' l D l'' S l D'' l'' ', '8S', 'U82l',
        16, NULL, NULL, NULL, 15),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 16, NULL, NULL, NULL, 16),
       ('R'' D'' R U R'' U'' R U R'' D R U'' R'' U R U''', 'UNDEF', 'TWIST', 'D U M U M U2 M'' U M'' U M'' U2 M D''',
        'UNDEF', 'TWIST', 16, NULL, NULL, NULL, 17),
       ('U R U'' D'' R'' D R U R'' D'' R D R'' U''', 'URD+', 'A91a', 'U'' L2 U M U2 M'' U L2 U ', '4M', 'U82f', 16,
        NULL, NULL, NULL, 18),
       ('U R U'' R'' D'' R U R'' D U''', 'URD+', 'Pure1b', 'U2 M U'' L2 U M'' U'' L2 U'' ', '8M', 'U92c', 16, NULL,
        NULL, NULL, 19),
       ('D R D R'' U'' R D2 R'' U R D R'' D''', 'URD+', 'A91c', 'U L E L2 E'' L U'' ', '4E', 'U93', 16, NULL, NULL,
        NULL, 20),
       ('R'' D'' R2 U R'' D R U'' R'' D'' R'' D R', 'URD+', 'Pure2b', 'u L'' E'' L2 E L'' u'' ', '4E', 'U93', 16, NULL,
        NULL, NULL, 21),
       ('U D'' L'' U'' L D2 L'' U L D'' U''', 'ULD+', 'Pure2c', 'L U'' L'' U'' L'' U'' L U L U ', 'R/L,U', 'U82c', 16,
        NULL, NULL, NULL, 22),
       ('D R D R'' U'' R D R'' U R D2 R'' D''', 'URD+', 'Pure2a', 'u L E L2 E'' L u'' ', '4E', 'U92b', 16, NULL, NULL,
        NULL, 23),
       (NULL, NULL, NULL, 'U2 L'' E'' L U'' L'' E L U'' ', '8E', 'U82g', 17,
        'U2 R U'' R'' U'' R U l'' U'' l U R'' U'' l'' U l U2', NULL, NULL, 2),
       ('U'' R'' D'' R U R'' D R', 'URD', 'Pure1b', 'U r U'' r'' S r U r'' S'' U'' ', '8S', 'U82j', 17,
        'U2 r2 U2 l'' U l U2 r'' L'' U L U'' r'' U2', NULL, NULL, 3),
       ('l'' U2 R'' D'' R U2 R'' D R l', 'l', 'A91c', 'L'' E'' L U L'' E L U'' ', '8E', 'U82e', 17, NULL, NULL, NULL,
        4),
       ('R'' U'' R U R'' D'' R U'' R'' D U R', 'URD+', 'A91a', 'U r'' U r S r'' U'' r S'' U'' ', '8S', 'U82i', 17, NULL,
        NULL, NULL, 5),
       ('U R'' D'' R U'' R'' D R', 'URD', 'Pure1a', 'U'' L'' E'' L U2 L'' E L U'' ', '8E', 'U82k', 17, NULL, NULL, NULL,
        6),
       ('R'' U R U'' R'' D'' R U R'' U'' D R', 'URD+', 'Pure1b', 'L'' U'' L'' U M'' U'' L U l ', '8M', 'U82l', 17, NULL,
        NULL, NULL, 7),
       ('U'' l U'' R'' D'' R U2 R'' D R U'' l'' U', 'l', 'A91b', 'D U'' R U M'' U'' R'' U M D'' ', '8M', 'U102b', 17,
        NULL, NULL, NULL, 8),
       ('U2 R'' D'' R U2 R'' D R', 'URD', 'Pure2c', 'S U L E'' L'' U'' L E L'' S''', '8E', 'U82c', 17, NULL, NULL, NULL,
        9),
       ('x U R'' D2 R U'' R'' D2 l', 'l', 'Pure2a', 'D U L'' U'' M'' U L U'' M D'' ', '8M', 'U102a', 17, NULL, NULL,
        NULL, 10),
       ('R'' D R'' U R D'' R'' U'' R2', 'URD+', 'Pure2b', 'U S'' U'' L U S U'' L'' ', '?', 'U82a', 17, NULL, NULL, NULL,
        11),
       ('R D U R'' D'' R U'' R'' D R D'' R''', 'URD+', 'A91a', 'r U'' S U2 S'' U'' r''', '4S', 'U82i', 17, NULL, NULL,
        NULL, 12),
       ('U R'' D'' R U'' R'' D2 R U R'' D'' R U''', 'URD+', 'A91c', 'U r U r'' S r U'' r'' S'' U'' ', '8S', 'U82e', 17,
        NULL, NULL, NULL, 13),
       ('R U R'' D R U'' R'' D''', 'URD', 'Pure1b', 'r'' D'' r S r'' D r S'' ', '8S', 'U82l', 17, NULL, NULL, NULL, 14),
       ('R'' D'' R U R'' U'' R U R'' D R U'' R'' U R U''', 'UNDEF', 'TWIST', 'M'' D M'' D2 M D M ', '4M', 'U82k', 17,
        NULL, NULL, NULL, 15),
       ('U R'' U'' R U R'' D'' R U'' R'' U R U'' R'' D R', 'UNDEF', 'TWIST', 'D U M U M U2 M'' U M'' U M'' U2 M D''',
        'UNDEF', 'TWIST', 17, NULL, NULL, NULL, 16),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 17, NULL, NULL, NULL, 17),
       ('D l'' D'' R U R'' D2 R U'' R'' D'' l D''', 'l', 'A91b', 'U S'' r D'' r'' S r D r'' U'' ', '8S', 'U82j', 17,
        NULL, NULL, NULL, 18),
       ('R D'' U R'' D R U'' R'' D'' R D R''', 'URD+', 'Pure1b', 'M D M'' D M D M'' D ', 'M,U/D', 'U82g', 17, NULL,
        NULL, NULL, 19),
       ('R U R'' D'' R U'' R'' D', 'URD', 'Pure1a', 'D U'' R'' U M'' U'' R U M D'' ', '8M', 'U103', 17, NULL, NULL,
        NULL, 20),
       ('R2 D'' R'' U'' R D R'' U R''', 'URD+', 'Pure2b', 'S U L'' E L U'' L'' E'' L S''', '8E', 'U93', 17, NULL, NULL,
        NULL, 21),
       ('l U2 R'' D'' R U2 R'' D x', 'l', 'Pure2a', 'D U L U'' M'' U L'' U'' M D'' ', '8M', 'U102b', 17, NULL, NULL,
        NULL, 22),
       ('R U R'' D2 R U'' R'' D2', 'URD', 'Pure2c', 'U S'' U'' L'' U S U'' L ', '?', 'U82a', 17, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'R U R'' U M U2 M'' U R U'' R'' ', '4M', 'U82f', 18,
        'U R2 U'' R U l'' U'' l U R'' U'' l'' U l R U'' R U''', NULL, NULL, 2),
       ('R D'' R'' U'' R'' D R U R'' D'' R2 D R''', 'URD+', 'Pure2c', 'r U R'' U'' M2 U R U'' R'' M'' ', '8M', 'U82j',
        18, 'U2 R2 F r2 U2 l'' U l U2 r'' L'' U L U'' r'' F'' R2 U2', NULL, NULL, 3),
       ('D R U2 R D'' R'' U2 R D R2 D''', 'URD+', 'Column', 'L'' U'' L U'' M U2 M'' U'' L'' U L ', '4M', 'U82f', 18,
        NULL, NULL, NULL, 4),
       ('R U'' R2 U R D R'' U'' R D'' R U R''', 'URD+', 'Pure2c', 'l'' U'' L U M2 U'' L'' U L M'' ', '8M', 'U82j', 18,
        NULL, NULL, NULL, 5),
       ('U R D'' R2 D R U'' R'' D'' R U R D R'' U''', 'URD+', 'A91b', 'U2 M U2 M'' ', '4M', 'U82n', 18, NULL, NULL,
        NULL, 6),
       ('D R U'' D'' R'' U R D R'' U'' R U R'' D''', 'URD+', 'A91a', 'U l U l'' S l U'' l'' S'' U'' ', '8S', 'U92d', 18,
        NULL, NULL, NULL, 7),
       ('U l'' U'' R D R'' U2 R D'' R'' U'' l U''', 'l', 'A91b', 'U R U M U2 M'' U R'' U'' ', '4M', 'U82j', 18, NULL,
        NULL, NULL, 8),
       ('R D'' R'' U2 R'' D R U2 R'' D'' R2 D R''', 'URD+', 'Special', 'M'' U R U'' M2 U R'' U'' M'' ', '8M', 'U82f',
        18, NULL, NULL, NULL, 9),
       ('D R U R D'' R'' U'' R D R2 D''', 'URD+', 'Pure3', 'U'' L'' U'' M U2 M'' U'' L U ', '4M', 'U82j', 18, NULL,
        NULL, NULL, 10),
       ('U R2 U'' R'' D'' R U R'' D R'' U''', 'URD+', 'Pure3', 'M'' U'' L'' U M2 U'' L U M'' ', '8M', 'U82f', 18, NULL,
        NULL, NULL, 11),
       ('R U'' R2 U R D2 R'' U'' R D2 R U R''', '4ins', 'Special', 'M D2 M'' D2 ', '4M', 'U82n', 18, NULL, NULL, NULL,
        12),
       ('U R2 U'' R'' D R U R'' D'' R'' U''', 'URD+', 'Pure3', 'D S'' l D l'' S l D'' l'' D'' ', '8S', 'U92d', 18, NULL,
        NULL, NULL, 13),
       ('D R U'' R D'' R'' U R D R2 D''', 'URD+', 'Pure3', 'U R2 U M U2 M'' U R2 U'' ', '4M', 'U82f', 18, NULL, NULL,
        NULL, 14),
       ('D R U'' R'' D'' R'' U R D R'' U'' R2 U R'' D''', 'URD+', 'A91b', 'U'' l'' D l S l'' D'' l S'' U ', '8S',
        'U82j', 18, NULL, NULL, NULL, 15),
       ('U R D'' R'' D R U'' R'' D'' R D U R'' U''', 'URD+', 'A91a', 'U'' L2 U'' M U2 M'' U'' L2 U ', '4M', 'U82f', 18,
        NULL, NULL, NULL, 16),
       ('D l'' D R U R'' D2 R U'' R'' D l D''', 'l', 'A91b', 'U r D'' r'' S'' r D r'' S U'' ', '8S', 'U82j', 18, NULL,
        NULL, NULL, 17),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 18, NULL, NULL, NULL, 18),
       ('U R U'' R'' D'' R U R'' U'' R U R'' D R U'' R''', 'UNDEF', 'TWIST', 'U'' M'' U M'' U2 M U M U M U2 M'' U2',
        'UNDEF', 'TWIST', 18, NULL, NULL, NULL, 19),
       ('R U R'' D'' R U'' R'' U R U'' R'' D R U R'' U''', 'UNDEF', 'TWIST', 'U R'' U M U2 M'' U R U'' ', '4M', 'U82j',
        18, NULL, NULL, NULL, 20),
       ('R U'' R2 U R D'' R'' U'' R D R U R''', 'URD+', 'Pure2c', 'M'' U R'' U'' M2 U R U'' M'' ', '8M', 'U82f', 18,
        NULL, NULL, NULL, 21),
       ('U R2 U'' R'' D2 R U R'' D2 R'' U''', 'URD+', 'Column', 'U'' L U'' M U2 M'' U'' L'' U ', '4M', 'U82j', 18, NULL,
        NULL, NULL, 22),
       ('R D'' R'' U R'' D R U'' R'' D'' R2 D R''', 'URD+', 'Pure2c', 'M'' U'' L U M2 U'' L'' U M'' ', '8M', 'U82f', 18,
        NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'M U'' M'' U'' M U'' M'' U'' ', 'M,U/D', 'U82g', 19,
        'U2 R2 U'' R'' U'' R U l'' U'' l U R'' U'' R'' F U2', NULL, NULL, 2),
       ('U2 R D R'' U R D'' R'' U', 'URD+', 'Pure2a', 'M2 U M U M'' U M U M ', 'M,U/D', 'U92c', 19,
        'U2 R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' U2', NULL, NULL, 3),
       ('l'' U R D R'' U2 R D'' R'' U l', 'l', 'A92', 'M U M'' U M U M'' U ', 'M,U/D', 'U82g', 19, NULL, NULL, NULL, 4),
       ('R'' U R'' D'' R U2 R'' D R U R', 'URD+', 'Pure2b', 'M2 U'' M U'' M'' U'' M U'' M ', 'M,U/D', 'U92c', 19, NULL,
        NULL, NULL, 5),
       ('R D R'' U'' R D'' R'' U', 'URD', 'Pure1a', 'U'' M'' U M'' U2 M U M U ', '4M', 'U82o', 19, NULL, NULL, NULL, 6),
       ('U'' R U R'' U'' R D R'' U R D'' U'' R'' U', 'URD+', 'A91c', 'U'' S l U l'' S'' l U'' l'' U ', '8S', 'U82o', 19,
        NULL, NULL, NULL, 7),
       ('U R U R'' D'' R U2 R'' D R U R'' U''', 'URD+', 'A91c', 'U'' R U'' M U R'' U'' M'' U2 ', '8M', 'U92c', 19, NULL,
        NULL, NULL, 8),
       ('U R D R'' U2 R D'' R'' U', 'URD+', 'Pure3', 'U l E'' L'' U'' L E L'' U M'' U'' ', '8E', 'U82g', 19, NULL, NULL,
        NULL, 9),
       ('U'' R D'' R U'' R'' D R U R2 U', 'URD+', 'Pure3', 'U L'' U M U'' L U M'' U2 ', '8M', 'U92c', 19, NULL, NULL,
        NULL, 10),
       ('R'' U R'' D'' R U R'' D R U2 R', 'URD+', 'Orth', 'U'' r'' E R U R'' E'' R U'' M'' U ', '8E', 'U82g', 19, NULL,
        NULL, NULL, 11),
       ('U'' R2 D R U R'' D'' R U'' R U', 'URD+', 'Pure3', 'D'' l D l'' S'' l D'' l'' S D ', '8S', 'U82o', 19, NULL,
        NULL, NULL, 12),
       ('U D'' R U'' R'' D2 R U R'' D'' U''', 'URD+', 'Pure3', 'U'' M U'' M'' U2 M'' U M U'' ', 'M,U/D', 'U82o', 19,
        NULL, NULL, NULL, 13),
       ('R D R'' U'' R D R'' U R D2 R''', 'URD+', 'Orth', 'U'' R2 U'' M U R2 U'' M'' U2 ', '8M', 'U92c', 19, NULL, NULL,
        NULL, 14),
       ('D'' U R U'' F2 U R'' U'' l D2 l'' D', '4ins', 'Cyclic', 'D M D M'' D M D M'' ', 'M,U/D', 'U82g', 19, NULL,
        NULL, NULL, 15),
       ('U D'' R U'' R'' D R U R'' U''', 'URD+', 'Pure1b', 'U L2 U M U'' L2 U M'' U2 ', '8M', 'U92c', 19, NULL, NULL,
        NULL, 16),
       ('R D'' R'' D R U R'' D'' R U'' D R''', 'URD+', 'Pure1b', 'D'' M D'' M'' D'' M D'' M'' ', 'M,U/D', 'U82g', 19,
        NULL, NULL, NULL, 17),
       ('R U R'' D'' R U'' R'' U R U'' R'' D R U R'' U''', 'UNDEF', 'TWIST', 'U'' M'' U M'' U2 M U M U M U2 M'' U2',
        'UNDEF', 'TWIST', 19, NULL, NULL, NULL, 18),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 19, NULL, NULL, NULL, 19),
       ('U R U'' R'' D'' R U R'' U'' R U R'' D R U'' R''', 'UNDEF', 'TWIST', 'U'' R'' U'' M U R U'' M'' U2 ', '8M',
        'U82g', 19, NULL, NULL, NULL, 20),
       ('R2 D2 R U R'' D R U'' R'' D R2', 'URD+', 'Pure2a', 'u r U'' M'' U2 M U'' r'' u'' ', '4M', 'U92c', 19, NULL,
        NULL, NULL, 21),
       ('U'' R'' U'' R D'' R'' U R U D', 'URD+', 'Pure2b', 'U L U M U'' L'' U M'' U2 ', '8M', 'U82g', 19, NULL, NULL,
        NULL, 22),
       ('R D R'' U'' R D2 R'' U R D R''', 'URD+', 'A92', 'u'' l'' U M'' U2 M U l u ', '4M', 'U92c', 19, NULL, NULL,
        NULL, 23),
       (NULL, NULL, NULL, 'U R U R U R'' U'' R'' U'' R''', 'R/L,U', 'U82a', 20,
        'D R D'' U l'' U'' l U R'' U'' l'' U l R U'' R'' U'' R D R'' D''', NULL, NULL, 2),
       ('U'' D'' R'' D'' R U R'' D R D', 'URD+', 'Pure2b', 'U r'' U M'' U2 M U r U'' ', '4M', 'U102a', 20,
        'U2 D'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' D U2', NULL, NULL, 3),
       ('R U'' R'' D'' R U2 R'' D R U'' R''', 'URD+', 'A92', 'U'' R U R U R U'' R'' U'' R''', 'R/L,U', 'U82c', 20, NULL,
        NULL, NULL, 4),
       ('R2 U'' R D R'' U'' R D'' R'' U2 R2', 'URD+', 'Pure2a', 'l'' E L U'' L'' E'' L U M ', '8E', 'U102b', 20, NULL,
        NULL, NULL, 5),
       ('D R D'' R'' U'' R D R'' D'' U', 'URD+', 'Pure1b', 'R U'' S'' U2 S U'' R''', '4S', 'U82i', 20, NULL, NULL, NULL,
        6),
       ('R D U'' R'' U R D'' R'' U'' R U R''', 'URD+', 'Pure1b', 'M U'' R'' U M'' U'' R U ', '8M', 'U82e', 20, NULL,
        NULL, NULL, 7),
       ('U'' l U2 l'' D R D'' B2 D R'' D'' U', '4ins', 'Cyclic', 'U R S R2 S'' R U'' ', '4S', 'U82i', 20, NULL, NULL,
        NULL, 8),
       ('D U R D'' R'' U2 R D R'' U D''', 'URD+', 'Pure3', 'R'' U'' R E R'' U R E'' ', '8E', 'U82e', 20, NULL, NULL,
        NULL, 9),
       ('R U2 R'' D'' R U'' R'' D R U'' R''', 'URD+', 'Orth', 'R U'' R E R2 E'' R U R'' ', '4E', 'U82j', 20, NULL, NULL,
        NULL, 10),
       ('D'' R'' D R'' U R D'' R'' U'' R2 D', 'URD+', 'Pure3', 'R'' U'' R'' E R U R'' E'' R2 ', '8E', 'U82g', 20, NULL,
        NULL, NULL, 11),
       ('D'' R2 D'' R'' U'' R D R'' U R'' D', 'URD+', 'Pure3', 'U R'' U M'' U2 M U R U'' ', '4M', 'U82k', 20, NULL,
        NULL, NULL, 12),
       ('R'' D2 R'' U'' R D'' R'' U R D'' R', 'URD+', 'Orth', 'M'' U'' R'' U M U'' R U ', '8M', 'U82l', 20, NULL, NULL,
        NULL, 13),
       ('D2 L'' U L D2 L'' U'' L', 'ULD', 'Pure3', 'U R U R U'' R'' U'' R'' U'' R ', 'R/L,U', 'U82c', 20, NULL, NULL,
        NULL, 14),
       ('D'' R D U R'' D'' R U'' R'' D R D'' R'' D', 'URD+', 'A91c', 'D'' M'' U'' R'' U M U'' R U D ', '8M', 'U102b',
        20, NULL, NULL, NULL, 15),
       ('D R D'' R'' U'' R D2 R'' U R D'' R'' D''', 'URD+', 'A91c', 'U L'' E L2 E'' L'' U'' ', '4E', 'U93', 20, NULL,
        NULL, NULL, 16),
       ('D'' R U R'' D R U'' R''', 'URD', 'Pure1a', 'D M'' U'' R'' U M U'' R U D'' ', '8M', 'U103', 20, NULL, NULL,
        NULL, 17),
       ('U R U'' R'' D'' R U R'' U'' R U R'' D R U'' R''', 'UNDEF', 'TWIST', 'U R'' U'' M U2 M'' U'' R U'' ', '4M',
        'U82j', 20, NULL, NULL, NULL, 18),
       ('R U R'' D'' R U'' R'' U R U'' R'' D R U R'' U''', 'UNDEF', 'TWIST', 'U2 M U R'' U'' M'' U R U ', '8M', 'U82g',
        20, NULL, NULL, NULL, 19),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 20, NULL, NULL, NULL, 20),
       ('l'' D'' R U R'' D2 R U'' R'' D'' l', 'l', 'A92', 'U2 R'' r'' U'' R U r U2 R'' U'' R'' U R2', 'UNDEF', 'TWIST',
        20, NULL, NULL, NULL, 21),
       ('x'' U'' L'' D2 L U L'' D2 r', 'r', 'Pure2b', 'R U'' R'' E'' R2 E R'' U R'' ', '4E', 'U82k', 20, NULL, NULL,
        NULL, 22),
       ('D'' R U R'' D'' R U'' R'' D2', 'URD+', 'Pure2a', 'R'' U'' R E'' R'' U R E ', '8E', 'U82l', 20, NULL, NULL,
        NULL, 23),
       (NULL, NULL, NULL, 'U2 L'' E L U'' L'' E'' L U'' ', '8E', 'U82b', 21, 'D U'' F2 l2 U R U'' l U2 r'' U L U D''',
        NULL, NULL, 2),
       ('R'' D'' R D R U'' R'' D'' R U R2 D R', 'URD+', 'Pure2c', 'S'' L'' E L U L'' E'' L U'' S ', '8E', 'U82a', 21,
        'U2 D F'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' F D'' U2', NULL, NULL, 3),
       ('R U2 R D'' R'' U2 R D R2', 'URD+', 'A92', 'L'' E L U L'' E'' L U'' ', '8E', 'U82c', 21, NULL, NULL, NULL, 4),
       ('R2 D'' R U'' R'' D'' R U R'' D2 R2', 'URD+', 'Pure2a', 'r'' U'' M'' U2 M U'' r ', '4M', 'U92b', 21, NULL, NULL,
        NULL, 5),
       ('x D2 R'' U'' R D2 R'' U l', 'l', 'Pure2c', 'U'' L'' E L U2 L'' E'' L U'' ', '8E', 'U82d', 21, NULL, NULL, NULL,
        6),
       ('R D'' U'' R'' U R D R'' U'' R U R''', 'URD+', 'Pure2a', 'U R'' U'' M'' U R U'' M ', '8M', 'U82h', 21, NULL,
        NULL, NULL, 7),
       ('U'' D R'' U2 R'' D R U2 R'' D'' R2 D'' U', 'URD+', 'A92', 'E'' R U'' R'' E R U R'' ', '8E', 'U82h', 21, NULL,
        NULL, NULL, 8),
       ('R D'' l U2 l'' D R D'' B2 D R2', '4ins', 'Column', 'M'' U'' R S R2 S'' R U M ', '4S', 'U82d', 21, NULL, NULL,
        NULL, 9),
       ('R U R D'' R'' U'' R D R2', 'URD+', 'Pure2b', 'L2 E L U L'' E'' L U'' L ', '8E', 'U92c', 21, NULL, NULL, NULL,
        10),
       ('R2 U R'' U'' R D'' R'' U R D U'' R2', 'URD+', 'Pure2b', 'r'' L'' U'' M'' U2 M U'' L r ', '4M', 'U82f', 21,
        NULL, NULL, NULL, 11),
       ('r D L'' U2 L D'' L'' U2 x''', 'r', 'Pure2c', 'r U S'' U2 S U r''', '4S', 'U82m', 21, NULL, NULL, NULL, 12),
       ('D l D2 l'' U R U'' F2 U R'' U'' D''', '4ins', 'A92', 'M2 U R'' U'' M U R U'' M ', '8M', 'U82l', 21, NULL, NULL,
        NULL, 13),
       ('l'' D U'' R'' D'' R U R'' D R D'' l', 'l', 'Pure2a', 'u'' R E'' R2 E R u ', '4E', 'U92b', 21, NULL, NULL, NULL,
        14),
       ('R U'' R'' U'' R D'' R'' U2 R D R'' U'' R U R''', 'URD+', 'Column', 'R U'' S U R'' U'' S'' U ', '?', 'U82a', 21,
        NULL, NULL, NULL, 15),
       ('R'' D'' R D R U R'' D'' R U'' R2 D R', 'URD+', 'Pure2b', 'u L E'' L2 E L u'' ', '4E', 'U93', 21, NULL, NULL,
        NULL, 16),
       ('R U'' R D'' R'' U R D R2', 'URD+', 'Pure2b', 'S L'' E L U L'' E'' L U'' S''', '8E', 'U93', 21, NULL, NULL,
        NULL, 17),
       ('R U'' R'' D'' R'' U R D R'' U'' R2 U R''', 'URD+', 'Pure2c', 'M U R'' U'' M2 U R U'' M ', '8M', 'U82f', 21,
        NULL, NULL, NULL, 18),
       ('R2 D'' R U R'' D'' R U'' R'' D2 R2', 'URD+', 'Pure2a', 'u r U M'' U2 M U r'' u'' ', '4M', 'U92c', 21, NULL,
        NULL, NULL, 19),
       ('l'' D R U R'' D2 R U'' R'' D l', 'l', 'A92', 'U2 R'' r'' U'' R U r U2 R'' U'' R'' U R2', 'UNDEF', 'TWIST', 21,
        NULL, NULL, NULL, 20),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 21, NULL, NULL, NULL, 21),
       ('U'' R D'' R'' U R U'' R'' U R D R'' U'' R U R''', 'UNDEF', 'TWIST', 'E L U L'' E'' L U'' L'' ', '8E', 'U82l',
        21, NULL, NULL, NULL, 22),
       ('R U'' R'' U R D'' R'' U'' R U R'' U'' R D R'' U', 'UNDEF', 'TWIST', 'x'' U'' M'' U2 M U'' x ', '4M', 'U82m',
        21, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'U L'' U'' L'' U'' L'' U L U L', 'R/L,U', 'U82c', 22,
        'D'' R D U l'' U'' l U R'' U'' l'' U l R U'' R'' U'' R D'' R'' D', NULL, NULL, 2),
       ('D U'' R'' D R U R'' D'' R D''', 'URD+', 'Pure2b', 'r E'' R'' U R E R'' U'' M ', '8E', 'U102b', 22,
        'U2 D'' R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' D U2', NULL, NULL, 3),
       ('D2 l'' U2 l D'' R'' D F2 D'' R D''', '4ins', 'Column', 'U'' L'' U'' L'' U'' L U L U L', 'R/L,U', 'U82a', 22,
        NULL, NULL, NULL, 4),
       ('x'' D R U2 R'' D'' R U2 l''', 'l', 'Pure2b', 'U'' l U'' M'' U2 M U'' l'' U ', '4M', 'U102a', 22, NULL, NULL,
        NULL, 5),
       ('D'' R D R'' U'' R D'' R'' U D', 'URD+', 'Pure2a', 'L'' U S U2 S'' U L', '4S', 'U82i', 22, NULL, NULL, NULL, 6),
       ('r'' D2 L U2 L'' D2 L U2 x', 'r', 'Pure2c', 'M U L U'' M'' U L'' U'' ', '8M', 'U82e', 22, NULL, NULL, NULL, 7),
       ('U'' R'' U R D'' R'' U2 R D R'' U R U', 'URD+', 'A92', 'R'' U'' R E'' R2 E R U R ', '4E', 'U82j', 22, NULL,
        NULL, NULL, 8),
       ('D'' U R D R'' U2 R D'' R'' U D', 'URD+', 'Pure2c', 'L U L E'' L'' U'' L E L2 ', '8E', 'U82g', 22, NULL, NULL,
        NULL, 9),
       ('U D R2 D R U'' R'' D'' R U R D'' U''', 'URD+', 'A92', 'U'' L'' S'' L2 S L'' U ', '4S', 'U82i', 22, NULL, NULL,
        NULL, 10),
       ('r'' D2 L U L'' D2 L U'' x', 'r', 'Pure2a', 'L U L'' E'' L U'' L'' E ', '8E', 'U82e', 22, NULL, NULL, NULL, 11),
       ('x'' D2 R U2 R'' D2 R U2 l''', 'l', 'Pure2c', 'U'' L U'' M'' U2 M U'' L'' U ', '4M', 'U82k', 22, NULL, NULL,
        NULL, 12),
       ('U D L'' U'' L D'' L'' U L U''', 'ULD+', 'Pure2a', 'M'' U L U'' M U L'' U'' ', '8M', 'U82l', 22, NULL, NULL,
        NULL, 13),
       ('D'' R D R'' U'' R D2 R'' U R D R'' D', 'URD+', 'A92', 'U'' R E'' R2 E R U ', '4E', 'U93', 22, NULL, NULL, NULL,
        14),
       ('D'' U'' R2 D R U R'' D'' R U'' R U D', 'URD+', 'A92', 'D'' M'' U L U'' M U L'' U'' D ', '8M', 'U103', 22, NULL,
        NULL, NULL, 15),
       ('U D L'' U'' L D2 L'' U L D U''', 'ULD+', 'Pure2c', 'U'' L'' U'' L'' U L U L U L'' ', 'R/L,U', 'U82c', 22, NULL,
        NULL, NULL, 16),
       ('x'' D'' R U2 R'' D R U2 l''', 'l', 'Pure2a', 'D M'' U L U'' M U L'' U'' D'' ', '8M', 'U102b', 22, NULL, NULL,
        NULL, 17),
       ('U R D2 R U'' R'' D2 R U R2 U''', 'URD+', 'Column', 'U'' L U M U2 M'' U L'' U ', '4M', 'U82j', 22, NULL, NULL,
        NULL, 18),
       ('D'' U'' R'' U'' R D R'' U R U', 'URD+', 'Pure2b', 'U2 M U'' L U M'' U'' L'' U'' ', '8M', 'U82g', 22, NULL,
        NULL, NULL, 19),
       ('r'' D2 L U'' L'' D2 L U x', 'r', 'Pure2b', 'R U'' R E'' R2 E R U R'' ', '4E', 'U82k', 22, NULL, NULL, NULL,
        20),
       ('R U'' R'' U R D'' R'' U'' R U R'' U'' R D R'' U', 'UNDEF', 'TWIST', 'L U L'' E L U'' L'' E'' ', '8E', 'U82l',
        22, NULL, NULL, NULL, 21),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 22, NULL, NULL, NULL, 22),
       ('U'' R D'' R'' U R U'' R'' U R D R'' U'' R U R''', 'UNDEF', 'TWIST', 'U2 L l U L'' U'' l'' U2 L U L U'' L2',
        'UNDEF', 'TWIST', 22, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, 'R E'' R'' U'' R E R'' U ', '8E', 'U82c', 23,
        'R D'' U l'' U'' l U R'' U'' l'' U l R U'' R'' U'' R D R''', NULL, NULL, 2),
       ('U2 R D'' R'' U R D R'' U', 'URD+', 'Pure2a', 'l U M'' U2 M U l'' ', '4M', 'U92b', 23,
        'U2 D2 r2 U2 l'' U l U2 r'' L'' U L U'' r'' D2 U2', NULL, NULL, 3),
       ('l'' U2 R'' D R U2 R'' D'' R l', 'l', 'A92', 'U2 R E'' R'' U R E R'' U ', '8E', 'U82b', 23, NULL, NULL, NULL,
        4),
       ('U'' R U'' R'' U R D'' R'' U'' R D U R'' U', 'URD+', 'Pure2c', 'S R E'' R'' U'' R E R'' U S'' ', '8E', 'U82a',
        23, NULL, NULL, NULL, 5),
       ('R D'' R'' U'' R D R'' U', 'URD', 'Pure2b', 'U R E'' R'' U2 R E R'' U ', '8E', 'U82d', 23, NULL, NULL, NULL, 6),
       ('U'' L U R U'' L'' U R''', 'LUR', 'Pure2b', 'U'' L U M'' U'' L'' U M ', '8M', 'U82h', 23, NULL, NULL, NULL, 7),
       ('U R2 D'' R'' U2 R D R'' U2 R'' U''', 'URD+', 'Column', 'R2 E'' R'' U'' R E R'' U R'' ', '8E', 'U92c', 23, NULL,
        NULL, NULL, 8),
       ('U R D'' R'' U2 R D R'' U', 'URD+', 'Pure2c', 'l R U M'' U2 M U R'' l'' ', '4M', 'U82f', 23, NULL, NULL, NULL,
        9),
       ('R D'' U R D R'' U'' R D'' R'' D R''', 'URD+', 'Pure2a', 'E L'' U L E'' L'' U'' L ', '8E', 'U82h', 23, NULL,
        NULL, NULL, 10),
       ('U2 R2 D'' R'' U R D R'' U'' R'' U2', 'URD+', 'A92', 'M'' U L'' S'' L2 S L'' U'' M', '4S', 'U82d', 23, NULL,
        NULL, NULL, 11),
       ('R D R'' D R U R'' D2 R U'' R'' D R D'' R''', 'URD+', 'Column', 'l'' U'' S U2 S'' U'' l', '4S', 'U82m', 23,
        NULL, NULL, NULL, 12),
       ('R'' D R2 U R'' D R U'' R'' D'' R'' D'' R', 'URD+', 'Pure2b', 'M2 U'' L U M U'' L'' U M ', '8M', 'U82l', 23,
        NULL, NULL, NULL, 13),
       ('D L'' U L D'' L'' U'' L', 'ULD', 'Pure2b', 'u'' R'' E R2 E'' R'' u ', '4E', 'U93', 23, NULL, NULL, NULL, 14),
       ('D2 R2 D'' R'' U'' R D R'' U R'' D2', 'URD+', 'A92', 'S'' R E'' R'' U'' R E R'' U S', '8E', 'U93', 23, NULL,
        NULL, NULL, 15),
       ('D R D2 R'' U'' R D'' R'' U R D'' R'' D''', 'URD+', 'Pure2a', 'u L'' E L2 E'' L'' u'' ', '4E', 'U92b', 23, NULL,
        NULL, NULL, 16),
       ('D2 R U R'' D2 R U'' R''', 'URD', 'Pure2c', 'L'' U S'' U'' L U S U'' ', '?', 'U82a', 23, NULL, NULL, NULL, 17),
       ('R D'' R2 D R U R'' D'' R U'' R D R''', 'URD+', 'Pure2c', 'M U'' L U M2 U'' L'' U M ', '8M', 'U82f', 23, NULL,
        NULL, NULL, 18),
       ('R D'' R'' U'' R D2 R'' U R D'' R''', 'URD+', 'A92', 'u'' l'' U'' M'' U2 M U'' l u ', '4M', 'U92c', 23, NULL,
        NULL, NULL, 19),
       ('D2 R U R'' D R U'' R'' D', 'URD+', 'Pure2a', 'E'' R'' U'' R E R'' U R ', '8E', 'U82l', 23, NULL, NULL, NULL,
        20),
       ('U'' R D'' R'' U R U'' R'' U R D R'' U'' R U R''', 'UNDEF', 'TWIST', 'x'' U M'' U2 M U x ', '4M', 'U82m', 23,
        NULL, NULL, NULL, 21),
       ('R U'' R'' U R D'' R'' U'' R U R'' U'' R D R'' U', 'UNDEF', 'TWIST', 'U2 L l U L'' U'' l'' U2 L U L U'' L2',
        'UNDEF', 'TWIST', 23, NULL, NULL, NULL, 22),
       (NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 23, NULL, NULL, NULL, 23) ON CONFLICT DO NOTHING;
