INSERT INTO "algorithm_mappings"
("action", "corner_algorithm", "corner_technique", "corner_type", "edge_algorithm", "edge_technique", "edge_type",
 "first_sticker", "letter_pair", "object", "parity_algorithm", "parity_technique", "parity_type", "person",
 "second_sticker")
VALUES (NULL, NULL, NULL, NULL, NULL, 'UNDEF', 'NULL', 2, 'RR', NULL, NULL, NULL, NULL, NULL, 2),
       (NULL, NULL, NULL, NULL, 'r U R'' U'' r'' U2 R U R U'' R2 U2 R', 'UNDEF', 'TWIST', 2, 'RS', NULL, NULL, NULL,
        NULL, NULL, 3),
       (NULL, NULL, NULL, NULL, 'M2 U M U2 M'' U M2 ', '4M', 'U101', 2, 'RM', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, NULL, NULL, NULL, 'S'' r U'' r'' S r U r'' ', '8S', 'U81', 2, 'RN', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, NULL, NULL, NULL, 'U M2 U M U2 M'' U M2 U''', '4M', 'U101', 2, 'RÚ', NULL, NULL, NULL, NULL, NULL, 6),
       (NULL, NULL, NULL, NULL, 'r'' U'' R U M'' U'' R'' U R ', '8M', 'U81', 2, 'RU', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, NULL, NULL, NULL, 'U2 R'' U'' R'' U'' R U R U R U', 'R/L,U', 'U92a', 2, 'RF', NULL, NULL, NULL, NULL,
        NULL, 8),
       (NULL, NULL, NULL, NULL, 'U L E'' L'' U L E L'' U2 ', '8E', 'U92a', 2, 'RJ', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, NULL, NULL, NULL, 'U2 L U L U L U'' L'' U'' L'' U', 'R/L,U', 'U82b', 2, 'RK', NULL, NULL, NULL, NULL,
        NULL, 10),
       (NULL, NULL, NULL, NULL, 'U'' R'' E R U R'' E'' R ', '8E', 'U82a', 2, 'RB', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, NULL, NULL, NULL, 'M U2 M U M'' U2 M'' U'' ', 'M,U/D', 'U82d', 2, 'RÍ', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, NULL, NULL, NULL, 'r U'' R'' U M U'' R U R'' ', '8M', 'U82e', 2, 'RI', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, NULL, NULL, NULL, 'U R'' U'' R U R U R U'' R'' U2 ', 'R/L,U', 'U82d', 2, 'RÓ', NULL, NULL, NULL, NULL,
        NULL, 14),
       (NULL, NULL, NULL, NULL, 'U'' R E R'' U R E'' R'' ', '8E', 'U82e', 2, 'RO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, NULL, NULL, NULL, 'U'' L'' U'' L U L U L U'' L'' ', 'R/L,U', 'U82f', 2, 'RÁ', NULL, NULL, NULL, NULL,
        NULL, 16),
       (NULL, NULL, NULL, NULL, 'U L'' E'' L U L'' E L U2 ', '8E', 'U82g', 2, 'RA', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, NULL, NULL, NULL, 'R U R'' U'' M U2 M'' U'' R U'' R'' ', '4M', 'U82f', 2, 'RÉ', NULL, NULL, NULL, NULL,
        NULL, 18),
       (NULL, NULL, NULL, NULL, 'U M U M'' U M U M'' ', 'M,U/D', 'U82g', 2, 'RE', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, NULL, NULL, NULL, 'R U R U R U'' R'' U'' R'' U''', 'R/L,U', 'U82a', 2, 'RD', NULL, NULL, NULL, NULL, NULL,
        20),
       (NULL, NULL, NULL, NULL, 'U L'' E L U L'' E'' L U2 ', '8E', 'U82b', 2, 'RP', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, NULL, NULL, NULL, 'L'' U'' L'' U'' L U L U L U''', 'R/L,U', 'U82c', 2, 'RL', NULL, NULL, NULL, NULL, NULL,
        22),
       (NULL, NULL, NULL, NULL, 'U'' R E'' R'' U R E R'' ', '8E', 'U82c', 2, 'RZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'r U R'' U'' r'' U2 R U R U'' R2 U2 R', 'UNDEF', 'TWIST', 3, 'SR', NULL,
        'U L'' U'' r U r'' U'' L U r U'' r'' L'' U L', NULL, NULL, NULL, 2),
       (NULL, 'R'' D'' R D R'' D'' R U'' R'' D R D'' R'' D R U', 'UNDEF', 'TWIST', 'l'' U l S l'' U'' l S'' ', '8S',
        'U81', 3, 'MX', NULL, 'U'' R U l'' U'' l U R'' U'' l'' U l R U'' R''', NULL, NULL, NULL, 4),
       (NULL, 'U'' R'' D'' R D R'' D'' R U R'' D R D'' R'' D R', 'UNDEF', 'TWIST', 'M U'' M'' U2 M U'' M'' ', '4M',
        'U91a', 3, 'MB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'l R D2 R'' U'' R D2 R'' U l''', 'l', 'A91a', 'U'' M'' U'' M U2 M'' U'' M U ', '4M', 'U91a', 3, 'MR',
        NULL, 'U'' R U R'' U'' l'' U l R U'' R'' U'' R U R'' F'' U', NULL, NULL, NULL, 6),
       (NULL, 'U'' R2 D R'' U R D'' R'' U'' R'' U', 'URD+', 'Pure1b', 'R U R'' U'' M'' U R U'' r'' ', '8M', 'U81', 3,
        'MV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' R'' U2 R'' D'' R U2 R'' D R2 U', 'URD+', 'A91c', 'M'' U'' L E'' L'' U'' L E L'' U2 M', '8E', 'U102c',
        3, 'MP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'R'' D'' U'' R'' D R U'' R'' D'' R D U2 R', 'URD+', 'A91a', 'S'' U L E'' L'' U'' L E L'' S ', '8E',
        'U92a', 3, 'MU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'U'' R2 D R'' U2 R D'' R'' U2 R'' U', 'URD+', 'A91c', 'U'' l'' U'' M U2 M'' U'' l U ', '4M', 'U102a', 3,
        'MN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U'' R'' U'' R'' D'' R U R'' D R2 U', 'URD+', 'Pure1b', 'L'' M U'' M'' U2 M U'' M'' L ', '4M', 'U82b', 3,
        'ML', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'R'' U'' l D2 l'' U R U'' F2 U', '4ins', 'A91b', 'D l'' U l S'' l'' U'' l S D'' ', '8S', 'U82i', 3, 'MI',
        NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D R U'' R'' D'' R U', 'URD', 'Pure1b', 'M2 R U R'' U'' M U R U'' r'' ', '8M', 'U82h', 3, 'MT', NULL,
        NULL, NULL, NULL, NULL, 13),
       (NULL, 'D R'' D'' R U'' R'' D R D'' U', 'URD+', 'Pure1a', 'l'' U l S'' l'' U'' l S ', '8S', 'U82h', 3, 'MC',
        NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'D R D'' R2 D R U'' R'' D'' R U R D R'' D''', 'URD+', 'A91b', 'U'' S'' l U'' l'' S l U l'' U ', '8S',
        'U82i', 3, 'MO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D'' R'' D R U'' R'' D'' R D U', 'URD+', 'Pure1a', 'l'' U l'' S l U'' l'' S'' l2 ', '8S', 'U92c', 3, 'MY',
        NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R'' D'' R U'' R'' D R U', 'URD', 'Pure1b', 'U S r U'' r'' S'' r U r'' U'' ', '8S', 'U82j', 3, 'MJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'R D'' R2 D R U'' R'' D'' R U R D R''', 'URD+', 'Pure2c', 'M R U R'' U'' M2 U R U'' r'' ', '8M', 'U82j',
        3, 'ME', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U'' R D R'' U'' R D'' R'' U2', 'URD+', 'Pure2a', 'M'' U'' M'' U'' M U'' M'' U'' M2 ', 'M,U/D', 'U92c', 3,
        'MK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D'' R'' D'' R U'' R'' D R D U', 'URD+', 'Pure2b', 'U r'' U'' M'' U2 M U'' r U'' ', '4M', 'U102a', 3,
        'MD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R'' D'' R2 U'' R'' D R U R'' D'' R'' D R', 'URD+', 'Pure2c', 'S'' U L'' E L U'' L'' E'' L S ', '8E',
        'U82a', 3, 'MA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'D R'' D R U'' R'' D'' R U D''', 'URD+', 'Pure2b', 'M'' U R E'' R'' U'' R E r'' ', '8E', 'U102b', 3, 'MH',
        NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'U'' R D'' R'' U'' R D R'' U2', 'URD+', 'Pure2a', 'l U'' M'' U2 M U'' l'' ', '4M', 'U92b', 3, 'MZ', NULL,
        NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'M2 U'' M U2 M'' U'' M2 ', '4M', 'U101', 4, 'MR', NULL,
        'r B'' U2 R'' l'' U R U'' l U2 r'' U L U L''', NULL, NULL, NULL, 2),
       (NULL, 'U'' R'' D'' R D R'' D'' R U R'' D R D'' R'' D R', 'UNDEF', 'TWIST', 'S l'' U l S'' l'' U'' l ', '8S',
        'U81', 4, 'XM', NULL, 'U2 R'' F r2 U2 l'' U l U2 r'' L'' U L U'' r'' F'' R U2', NULL, NULL, NULL, 3),
       (NULL, 'R'' D'' R D R'' D'' R U'' R'' D R D'' R'' D R U', 'UNDEF', 'TWIST',
        'l'' U'' L U l U2 L'' U'' L'' U L2 U2 L''', 'UNDEF', 'TWIST', 4, 'XB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'R2 D R'' U2 R D'' R'' U2 R''', 'URD+', 'A91c', 'U'' M2 U'' M U2 M'' U'' M2 U ', '4M', 'U101', 4, 'XR',
        NULL, NULL, NULL, NULL, NULL, 6),
       (NULL, 'R D'' U R'' D'' R U2 R'' D R U D R''', 'URD+', 'A91b', 'l U L'' U'' M'' U L U'' L'' ', '8M', 'U81', 4,
        'XV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'R'' U'' R2 D'' R2 D R2 U R2 D'' R2 D R''', '5ins', 'Cyclic', 'U2 R'' U'' R'' U'' R'' U R U R U''',
        'R/L,U', 'U82b', 4, 'XP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'l'' R'' D2 R U2 R'' D2 R U2 l', 'l', 'A91b', 'U L E'' L'' U'' L E L'' ', '8E', 'U82a', 4, 'XU', NULL,
        NULL, NULL, NULL, NULL, 9),
       (NULL, 'l'' U'' R D'' R'' U2 R D R'' U'' l', 'l', 'A91c', 'U2 L U L U L'' U'' L'' U'' L'' U''', 'R/L,U', 'U92a',
        4, 'XN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'R U R'' D U R D R'' U2 R D'' R'' U D'' R U'' R''', 'URD+', 'Cyclic', 'U'' R'' E R U'' R'' E'' R U2 ',
        '8E', 'U92a', 4, 'XL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'D'' R2 D'' R'' U2 R D R'' U2 R'' D', 'URD+', 'A91b', 'M U2 M U'' M'' U2 M'' U ', 'M,U/D', 'U82d', 4,
        'XI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D F2 D'' R D l'' U2 l D''', '4ins', 'Cyclic', 'l'' U L U'' M U L'' U'' L ', '8M', 'U82e', 4, 'XT',
        NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'R U R'' D R U2 R'' D'' R U R''', 'URD+', 'A91c', 'U R U R'' U'' R'' U'' R'' U R ', 'R/L,U', 'U82f', 4,
        'XC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'R'' D R D2 R U'' R'' D2 R U R2 D'' R', 'URD+', 'Cyclic', 'U'' R E R'' U'' R E'' R'' U2 ', '8E', 'U82g',
        4, 'XO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D'' R'' D F2 D'' R D l'' U2 l', '4ins', 'A91b', 'U'' L U L'' U'' L'' U'' L'' U L U2 ', 'R/L,U', 'U82d',
        4, 'XY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'l'' R'' D'' R U2 R'' D R U2 l', 'l', 'A91c', 'U L'' E'' L U'' L'' E L ', '8E', 'U82e', 4, 'XJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'D R2 D'' R'' U2 R D R'' U2 R'' D''', 'URD+', 'Column', 'L'' U'' L U M U2 M'' U L'' U L ', '4M', 'U82f',
        4, 'XE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'l'' U'' R D R'' U2 R D'' R'' U'' l', 'l', 'A92', 'U'' M U'' M'' U'' M U'' M'' ', 'M,U/D', 'U82g', 4,
        'XK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R U R'' D'' R U2 R'' D R U R''', 'URD+', 'A92', 'R U R U R'' U'' R'' U'' R'' U', 'R/L,U', 'U82c', 4,
        'XD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 D'' R'' U2 R D R'' U2 R''', 'URD+', 'A92', 'U L'' E L U'' L'' E'' L ', '8E', 'U82c', 4, 'XA', NULL,
        NULL, NULL, NULL, NULL, 21),
       (NULL, 'D R'' D F2 D'' R D l'' U2 l D2', '4ins', 'Column', 'L'' U'' L'' U'' L'' U L U L U', 'R/L,U', 'U82a', 4,
        'XH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'l'' R'' D R U2 R'' D'' R U2 l', 'l', 'A92', 'U'' R E'' R'' U'' R E R'' U2 ', '8E', 'U82b', 4, 'XZ', NULL,
        NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'r U'' r'' S'' r U r'' S ', '8S', 'U81', 5, 'NR', NULL,
        'L'' U R'' U'' R L U2 R'' U'' R U2', NULL, NULL, NULL, 2),
       (NULL, 'R'' D'' R D R'' D'' R U'' R'' D R D'' R'' D R U', 'UNDEF', 'TWIST', 'M U M'' U2 M U M'' ', '4M', 'U91a',
        5, 'BM', NULL, 'U2 R2 r2 U2 l'' U l U2 r'' L'' U L U'' r'' R2 U2', NULL, NULL, NULL, 3),
       (NULL, 'U'' R'' D'' R D R'' D'' R U R'' D R D'' R'' D R', 'UNDEF', 'TWIST',
        'l'' U'' L U l U2 L'' U'' L'' U L2 U2 L''', 'UNDEF', 'TWIST', 5, 'BX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'R'' U'' R'' D'' R U R'' D R2', 'URD+', 'Pure1b', 'U M'' U M U2 M'' U M U''', '4M', 'U91a', 5, 'BR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'R'' U L U'' R U L'' U''', 'LUR', 'Pure1a', 'L'' U'' L U M'' U'' L'' U l ', '8M', 'U81', 5, 'BV', NULL,
        NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' R'' D U R D R'' U2 R D'' R'' U D'' R U', 'URD+', 'A91b', 'U r U M U2 M'' U r'' U'' ', '4M', 'U102a',
        5, 'BP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'U'' R D'' U R'' D'' R U2 R'' D R D U R'' U', 'URD+', 'A91b', 'R M U M'' U2 M U M'' R'' ', '4M', 'U82b',
        5, 'BU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'U'' R'' U L U'' R U L''', 'LUR', 'Pure1a', 'M'' U R'' E R U R'' E'' R U2 M', '8E', 'U102c', 5, 'BN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'l U'' R'' D R U R'' D'' x', 'l', 'Pure1b', 'S U'' R'' E R U R'' E'' R S'' ', '8E', 'U92a', 5, 'BL', NULL,
        NULL, NULL, NULL, NULL, 11),
       (NULL, 'U'' R'' U R U'' R'' D R U R'' D'' U'' R U', 'URD+', 'A91a', 'D'' r U'' r'' S r U r'' S'' D ', '8S',
        'U82i', 5, 'BI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' U'' D R U R'' D'' R U'' R'' U R', 'URD+', 'Pure1b', 'M2 L'' U'' L U M U'' L'' U l ', '8M', 'U82h', 5,
        'BT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'D R'' U'' D'' R U R'' D R U'' R'' U R D''', 'URD+', 'A91c', 'r U'' r S'' r'' U r S r2 ', '8S', 'U92c', 5,
        'BC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'R U'' R2 D'' R U2 R'' D R U2 R U R''', 'URD+', 'A91c', 'U'' S'' l'' U l S l'' U'' l U ', '8S', 'U82j', 5,
        'BO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'R U L U'' R'' U L'' U''', 'LUR', 'Pure1b', 'r U'' r'' S r U r'' S'' ', '8S', 'U82h', 5, 'BY', NULL, NULL,
        NULL, NULL, NULL, 16),
       (NULL, 'R'' U'' D'' R U R'' D R U'' R'' U R', 'URD+', 'A91a', 'U S r'' U r S'' r'' U'' r U'' ', '8S', 'U82i', 5,
        'BJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'R U'' R'' D R'' U R D'' R'' U'' R2 U R''', 'URD+', 'Pure2c', 'M L'' U'' L U M2 U'' L'' U l ', '8M',
        'U82j', 5, 'BE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'R'' U'' R'' D'' R U2 R'' D R U'' R', 'URD+', 'Pure2b', 'M'' U M'' U M U M'' U M2 ', 'M,U/D', 'U92c', 5,
        'BK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R2 U2 R D R'' U R D'' R'' U R2', 'URD+', 'Pure2a', 'M'' U'' L'' E L U L'' E'' l ', '8E', 'U102b', 5,
        'BD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 D2 R U'' R'' D R U R'' D R2', 'URD+', 'Pure2a', 'r'' U M'' U2 M U r ', '4M', 'U92b', 5, 'BA', NULL,
        NULL, NULL, NULL, NULL, 21),
       (NULL, 'l U2 R'' D R U2 R'' D'' x', 'l', 'Pure2b', 'U'' l U M'' U2 M U l'' U ', '4M', 'U102a', 5, 'BH', NULL,
        NULL, NULL, NULL, NULL, 22),
       (NULL, 'U'' R U'' D'' R'' U R D R'' U'' R U R'' U', 'URD+', 'Pure2c', 'S U'' R E'' R'' U R E R'' S'' ', '8E',
        'U82a', 5, 'BZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U M2 U'' M U2 M'' U'' M2 U''', '4M', 'U101', 6, 'ÚR', NULL,
        'R U l'' U'' l U R'' U'' l'' U l R U'' R'' U''', NULL, NULL, NULL, 2),
       (NULL, 'l U'' R D2 R'' U R D2 R'' l''', 'l', 'A91a', 'U'' M'' U M U2 M'' U M U ', '4M', 'U91a', 6, 'RM', NULL,
        'S'' U'' R'' U2 R U2 l'' U l U R'' U'' l'' U'' l R S', NULL, NULL, NULL, 3),
       (NULL, 'R U2 R D R'' U2 R D'' R2', 'URD+', 'A91c', 'U'' M2 U M U2 M'' U M2 U', '4M', 'U101', 6, 'RX', NULL,
        'U'' R'' U2 R U2 l'' U l U R'' U'' l'' U'' l R', NULL, NULL, NULL, 4),
       (NULL, 'R2 D'' R U'' R'' D R U R', 'URD+', 'Pure1b', 'U M'' U'' M U2 M'' U'' M U''', '4M', 'U91a', 6, 'RB', NULL,
        NULL, NULL, NULL, NULL, 5),
       (NULL, 'R D R'' D'' R D R'' U'' R D'' R'' D R D'' R'' U', 'UNDEF', 'TWIST', 'M'' U M'' U M'' U2 M U M U M U2',
        'UNDEF', 'TWIST', 6, 'RV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' R D R'' D'' R D R'' U R D'' R'' D R D'' R''', 'UNDEF', 'TWIST', 'R'' U S'' U2 S U R', '4S', 'U82i',
        6, 'RP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'l'' R'' D2 R U R'' D2 R U'' l', 'l', 'A91a', 'U L E'' L'' U2 L E L'' U ', '8E', 'U82d', 6, 'RU', NULL,
        NULL, NULL, NULL, NULL, 9),
       (NULL, 'R U R D R'' U'' R D'' R2', 'URD+', 'Pure1b', 'L U'' S U2 S'' U'' L''', '4S', 'U82i', 6, 'RN', NULL, NULL,
        NULL, NULL, NULL, 10),
       (NULL, 'R2 D'' R U2 R'' D R U2 R', 'URD+', 'A91c', 'U'' R'' E R U2 R'' E'' R U'' ', '8E', 'U82d', 6, 'RL', NULL,
        NULL, NULL, NULL, NULL, 11),
       (NULL, 'x'' D2 R U R'' D2 R U'' l''', 'l', 'Pure2c', 'U2 M'' U2 M ', '4M', 'U82n', 6, 'RI', NULL, NULL, NULL,
        NULL, NULL, 12),
       (NULL, 'R'' D R U R'' D'' R U''', 'URD', 'Pure2b', 'U M U'' M U2 M'' U'' M'' U'' ', '4M', 'U82o', 6, 'RT', NULL,
        NULL, NULL, NULL, NULL, 13),
       (NULL, 'D R'' D'' R U R'' D R U'' D''', 'URD+', 'Pure2a', 'U S'' U2 S U', '4S', 'U82m', 6, 'RC', NULL, NULL,
        NULL, NULL, NULL, 14),
       (NULL, 'U'' R'' D R2 D'' R'' U R D R'' U'' R'' D'' R U', 'URD+', 'A91b', 'U'' R E R'' U2 R E'' R'' U'' ', '8E',
        'U82k', 6, 'RO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D'' R'' D R U R'' D'' R D U''', 'URD+', 'Pure1b', 'U'' S U2 S'' U''', '4S', 'U82m', 6, 'RY', NULL, NULL,
        NULL, NULL, NULL, 16),
       (NULL, 'R'' D'' R U R'' D R U''', 'URD', 'Pure1a', 'U L'' E'' L U2 L'' E L U ', '8E', 'U82k', 6, 'RJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R D'' R'' U'' R'' D R U R'' D'' R2 D R'' U''', 'URD+', 'A91b', 'M U2 M'' U2 ', '4M', 'U82n', 6, 'RE',
        NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U'' R D R'' U R D'' R''', 'URD', 'Pure1a', 'U'' M'' U'' M'' U2 M U'' M U ', '4M', 'U82o', 6, 'RK', NULL,
        NULL, NULL, NULL, NULL, 19),
       (NULL, 'U'' D R D'' R'' U R D R'' D''', 'URD+', 'Pure1b', 'R U S'' U2 S U R''', '4S', 'U82i', 6, 'RD', NULL,
        NULL, NULL, NULL, NULL, 20),
       (NULL, 'l'' U'' R D2 R'' U R D2 x''', 'l', 'Pure2c', 'U L'' E L U2 L'' E'' L U ', '8E', 'U82d', 6, 'RA', NULL,
        NULL, NULL, NULL, NULL, 21),
       (NULL, 'D'' U'' R D R'' U R D'' R'' D', 'URD+', 'Pure2a', 'L'' U'' S U2 S'' U'' L', '4S', 'U82i', 6, 'RH', NULL,
        NULL, NULL, NULL, NULL, 22),
       (NULL, 'U'' R D'' R'' U R D R''', 'URD', 'Pure2b', 'U'' R E'' R'' U2 R E R'' U'' ', '8E', 'U82d', 6, 'RZ', NULL,
        NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'R'' U'' R U M U'' R'' U r ', '8M', 'U81', 7, 'UR', NULL,
        'U R U'' R'' U2 L R U'' R'' U L'' U', NULL, NULL, NULL, 2),
       (NULL, 'U'' R U R D R'' U'' R D'' R2 U', 'URD+', 'Pure1b', 'r U R'' U'' M U R U'' R'' ', '8M', 'U81', 7, 'VM',
        NULL, 'U R'' U r2 U2 l'' U l U2 r'' L'' U L U'' r'' U'' R U''', NULL, NULL, NULL, 3),
       (NULL, 'R D'' U'' R'' D'' R U2 R'' D R U'' D R''', 'URD+', 'A91b', 'L U L'' U'' M U L U'' l'' ', '8M', 'U81', 7,
        'VX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'U L U'' R'' U L'' U'' R', 'LUR', 'Pure1a', 'l'' U'' L U M U'' L'' U L ', '8M', 'U81', 7, 'VB', NULL,
        NULL, NULL, NULL, NULL, 5),
       (NULL, 'U'' R D R'' D'' R D R'' U R D'' R'' D R D'' R''', 'UNDEF', 'TWIST', 'M'' U M'' U M'' U2 M U M U M U2',
        'UNDEF', 'TWIST', 7, 'VR', NULL, NULL, NULL, NULL, NULL, 6),
       (NULL, 'R D R'' D'' R D R'' U'' R D'' R'' D R D'' R'' U', 'UNDEF', 'TWIST', 'U'' R U M U'' R'' U M'' ', '8M',
        'U82h', 7, 'VP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'R'' D U'' R D R'' U2 R D'' R'' U'' D'' R', 'URD+', 'A91b', 'M'' U R U'' M U R'' U'' ', '8M', 'U82e', 7,
        'VU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'U R2 D'' R U'' R'' D R U R U''', 'URD+', 'Pure1b', 'U L'' U'' M U L U'' M'' ', '8M', 'U82h', 7, 'VN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'R U'' L'' U R'' U'' L U', 'LUR', 'Pure1a', 'M'' U'' L'' U M U'' L U ', '8M', 'U82e', 7, 'VL', NULL, NULL,
        NULL, NULL, NULL, 11),
       (NULL, 'r D2 L'' U2 L D2 L'' U2 x''', 'r', 'Pure2c', 'U S l'' U'' l S'' l'' U l U'' ', '8S', 'U82o', 7, 'VI',
        NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D U R U'' R'' D'' R U R'' U'' R', 'URD+', 'Pure2a', 'U'' l'' U'' l S l'' U l S'' U ', '8S', 'U92d',
        7, 'VT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'U L'' U'' R'' U L U'' R', 'LUR', 'Pure2b', 'R'' U'' R'' U M U'' R U r ', '8M', 'U82l', 7, 'VC', NULL,
        NULL, NULL, NULL, NULL, 14),
       (NULL, 'U R'' U'' R U R'' D'' R U'' R'' D U R U''', 'URD+', 'A91c', 'r U R U'' M U R'' U'' R'' ', '8M', 'U82l',
        7, 'VO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D'' R'' U D R U'' R'' D'' R U R'' U'' R D', 'URD+', 'A91a', 'L U L U'' M U L'' U'' l'' ', '8M', 'U82l',
        7, 'VY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R'' D'' U R U'' R'' D R U R'' U'' R', 'URD+', 'Pure1b', 'l'' U'' L'' U M U'' L U L ', '8M', 'U82l', 7,
        'VJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'D R U'' R'' U R D'' R'' U'' R D U R'' D''', 'URD+', 'A91a', 'U S l U l'' S'' l U'' l'' U'' ', '8S',
        'U92d', 7, 'VE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U'' R U D R'' U'' R D'' R'' U R U'' R'' U', 'URD+', 'A91c', 'U'' l U l'' S l U'' l'' S'' U ', '8S',
        'U82o', 7, 'VK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R U'' R'' U R D R'' U'' R U D'' R''', 'URD+', 'Pure1b', 'U'' R'' U M U'' R U M'' ', '8M', 'U82e', 7,
        'VD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R U'' R'' U R D'' R'' U'' R U D R''', 'URD+', 'Pure2a', 'M'' U R'' U'' M U R U'' ', '8M', 'U82h', 7,
        'VA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'x'' U2 L'' D2 L U2 L'' D2 r', 'r', 'Pure2c', 'U L U'' M U L'' U'' M'' ', '8M', 'U82e', 7, 'VH', NULL,
        NULL, NULL, NULL, NULL, 22),
       (NULL, 'R U'' L U R'' U'' L'' U', 'LUR', 'Pure2b', 'M'' U'' L U M U'' L'' U ', '8M', 'U82h', 7, 'VZ', NULL, NULL,
        NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U'' R'' U'' R'' U'' R'' U R U R U2', 'R/L,U', 'U92a', 8, 'FR', NULL,
        'U R'' U R U'' B r'' U L U2 R U'' R'' U x', NULL, NULL, NULL, 2),
       (NULL, 'U'' R2 D'' R U2 R'' D R U2 R U', 'URD+', 'A91c', 'M'' U2 L E'' L'' U L E L'' U M', '8E', 'U102c', 8,
        'PM', NULL, 'U R U F r2 U2 l'' U l U2 r'' L'' U L U'' r'' F'' U'' R'' U''', NULL, NULL, NULL, 3),
       (NULL, 'R D'' R2 D R2 U'' R2 D'' R2 D R2 U R', '5ins', 'Cyclic', 'U R'' U'' R'' U'' R U R U R U2', 'R/L,U',
        'U82b', 8, 'PX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'U'' R'' D U'' R D R'' U2 R D'' R'' U'' D'' R U', 'URD+', 'A91b', 'U r U'' M U2 M'' U'' r'' U'' ', '4M',
        'U102a', 8, 'PB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'R D R'' D'' R D R'' U'' R D'' R'' D R D'' R'' U', 'UNDEF', 'TWIST', 'R'' U'' S'' U2 S U'' R', '4S',
        'U82i', 8, 'PR', NULL, NULL, NULL, NULL, NULL, 6),
       (NULL, 'U'' R D R'' D'' R D R'' U R D'' R'' D R D'' R''', 'UNDEF', 'TWIST', 'M U'' R U M'' U'' R'' U ', '8M',
        'U82h', 8, 'PV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U R D'' U'' R'' D'' R U2 R'' D R U'' D R'' U''', 'URD+', 'A91b', 'R r U R'' U'' r'' U2 R U R U'' R2 U2',
        'UNDEF', 'TWIST', 8, 'PU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'R U R2 D R2 D'' R2 U'' R2 D R2 D'' R', '5ins', 'Cyclic', 'R'' U'' R E R2 E'' R U R ', '4E', 'U91a', 8,
        'PN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U R U2 R D R'' U2 R D'' R2 U''', 'URD+', 'A91c', 'R U'' R'' E R U R'' E'' ', '8E', 'U81', 8, 'PL', NULL,
        NULL, NULL, NULL, NULL, 11),
       (NULL, 'U'' R2 D R U2 R'' D'' R U2 R U', 'URD+', 'Column', 'U R U M'' U2 M U R'' U'' ', '4M', 'U91a', 8, 'PI',
        NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U R U'' R'' D R U2 R'' D'' R U'' R'' U''', 'URD+', 'A92', 'M'' U'' R U M U'' R'' U ', '8M', 'U81', 8,
        'PT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'U D'' R U2 R D'' R'' U2 R D R2 D U''', 'URD+', 'A92', 'U R'' U'' R'' U R U R U R'' U2 ', 'R/L,U', 'U82b',
        8, 'PC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'U l'' U2 l D'' R'' D F2 D'' R D U''', '4ins', 'Cyclic', 'D'' M'' U'' R U M U'' R'' U D ', '8M', 'U102a',
        8, 'PO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'U'' R'' U'' R D R'' U2 R D'' R'' U'' R U', 'URD+', 'A91c', 'U L E'' L2 E L U'' ', '4E', 'U92b', 8, 'PY',
        NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'U'' l U R'' D'' R U2 R'' D R U l'' U', 'l', 'A91b', 'D M'' U'' R U M U'' R'' U D'' ', '8M', 'U102b', 8,
        'PJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'U l'' U R D R'' U2 R D'' R'' U l U''', 'l', 'A91b', 'U R U'' M U2 M'' U'' R'' U'' ', '4M', 'U82j', 8,
        'PE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U R U'' R'' D'' R U2 R'' D R U'' R'' U''', 'URD+', 'A91c', 'U2 M U R U'' M'' U R'' U ', '8M', 'U92c', 8,
        'PK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'U'' D R D'' B2 D R'' D'' l U2 l'' U', '4ins', 'Cyclic', 'U R'' S R2 S'' R'' U'' ', '4S', 'U82i', 8, 'PD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'U'' D R2 D R U2 R'' D'' R U2 R D'' U', 'URD+', 'A92', 'R U'' R'' E'' R U R'' E ', '8E', 'U82h', 8, 'PA',
        NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'U'' R'' U'' R D'' R'' U2 R D R'' U'' R U', 'URD+', 'A92', 'R'' U'' R'' E'' R2 E R'' U R ', '4E', 'U82j',
        8, 'PH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'U R U2 R D'' R'' U2 R D R2 U''', 'URD+', 'Column', 'R U'' R E'' R'' U R E R2 ', '8E', 'U92c', 8, 'PZ',
        NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U2 L E'' L'' U'' L E L'' U'' ', '8E', 'U92a', 9, 'JR', NULL,
        'U2 F R U'' R'' U'' R U l'' U'' l U R'' U'' l'' U l F'' U2', NULL, NULL, NULL, 2),
       (NULL, 'R'' U2 D'' R'' D R U R'' D'' R U D R', 'URD+', 'A91a', 'S'' L E'' L'' U L E L'' U'' S ', '8E', 'U92a', 9,
        'UM', NULL, 'S'' L'' U2 L U2 R U'' L'' U R'' U R U'' L U R'' S', NULL, NULL, NULL, 3),
       (NULL, 'l'' U2 R'' D2 R U2 R'' D2 R l', 'l', 'A91b', 'L E'' L'' U L E L'' U'' ', '8E', 'U82a', 9, 'UX', NULL,
        'L'' U2 L U2 R U'' L'' U R'' U R U'' L U R''', NULL, NULL, NULL, 4),
       (NULL, 'U'' R U'' D'' R'' D'' R U2 R'' D R U'' D R'' U', 'URD+', 'A91b', 'R M U'' M'' U2 M U'' M'' R'' ', '4M',
        'U82b', 9, 'UB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'l'' U R'' D2 R U'' R'' D2 R l', 'l', 'A91a', 'U'' L E'' L'' U2 L E L'' U'' ', '8E', 'U82d', 9, 'UR',
        NULL, 'R U R'' U R U l'' U'' l U R'' U'' l'' U l R U'' R'' U2 R U'' R'' U2', NULL, NULL, NULL, 6),
       (NULL, 'R'' D U R D R'' U2 R D'' R'' U D'' R', 'URD+', 'A91b', 'U R U'' M'' U R'' U'' M ', '8M', 'U82e', 9, 'UV',
        NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U R D'' U R'' D'' R U2 R'' D R U D R'' U''', 'URD+', 'A91b', 'R r U R'' U'' r'' U2 R U R U'' R2 U2',
        'UNDEF', 'TWIST', 9, 'UP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'U2 R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R', 'UNDEF', 'TWIST', 'E'' L'' U L E L'' U'' L ', '8E',
        'U81', 9, 'UN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R U2', 'UNDEF', 'TWIST', 'u'' U2 R S R2 S'' R U2 u', '4S',
        'U101', 9, 'UL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'l D'' l'' U'' R D R'' U2 R D'' R'' U'' l D l''', '2l', 'Special', 'u'' U'' M2 U R'' U'' M2 U R u ', '8M',
        'U101', 9, 'UI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D R U2 R'' D'' R U2', 'URD', 'Pure3', 'M2 U R U'' M U R'' U'' M ', '8M', 'U81', 9, 'UT', NULL, NULL,
        NULL, NULL, NULL, 13),
       (NULL, 'D'' U'' R D'' R'' U2 R D R'' U'' D', 'URD+', 'Pure3', 'u U2 R'' E R2 E'' R'' U2 u'' ', '4E', 'U82b', 9,
        'UC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'R'' D R D'' R'' U R D2 R'' U'' R D'' R'' D'' R', 'URD+', 'Column', 'R'' U'' S U R U'' S'' U ', '?',
        'U82a', 9, 'UO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D U'' R D R'' U2 R D'' R'' U'' D''', 'URD+', 'Pure2c', 'u'' U2 L'' E L2 E'' L'' U2 u ', '4E', 'U82c', 9,
        'UY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R D'' R2 D R U2 R'' D'' R U2 R D R''', 'URD+', 'Special', 'M U R U'' M2 U R'' U'' M ', '8M', 'U82f', 9,
        'UE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U'' R D R'' U2 R D'' R'' U''', 'URD+', 'Pure3', 'U M U'' L E'' L'' U L E l'' U'' ', '8E', 'U82g', 9,
        'UK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D U'' R D'' R'' U2 R D R'' U'' D''', 'URD+', 'Pure3', 'E R'' U'' R E'' R'' U R ', '8E', 'U82e', 9, 'UD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 D'' B2 D R'' D'' l U2 l'' D R''', '4ins', 'Column', 'M'' U'' R'' S R2 S'' R'' U M', '4S', 'U82d', 9,
        'UA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'D'' U'' R D R'' U2 R D'' R'' U'' D', 'URD+', 'Pure2c', 'L2 E'' L'' U L E L'' U'' L'' ', '8E', 'U82g', 9,
        'UH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'U'' R D'' R'' U2 R D R'' U''', 'URD+', 'Pure2c', 'l R U'' M'' U2 M U'' R'' l'' ', '4M', 'U82f', 9, 'UZ',
        NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U'' L U L U L'' U'' L'' U'' L'' U2', 'R/L,U', 'U82b', 10, 'KR', NULL,
        'U R'' U'' R U l'' U'' l U R'' U'' l'' U l R U2', NULL, NULL, NULL, 2),
       (NULL, 'U'' R U2 R D R'' U2 R D'' R2 U', 'URD+', 'A91c', 'U'' l'' U M U2 M'' U l U ', '4M', 'U102a', 10, 'NM',
        NULL, 'U2 R'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' R U2', NULL, NULL, NULL, 3),
       (NULL, 'l'' U R D'' R'' U2 R D R'' U l', 'l', 'A91c', 'U L U L U L U'' L'' U'' L'' U2', 'R/L,U', 'U92a', 10,
        'NX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'L U'' R'' U L'' U'' R U', 'LUR', 'Pure1a', 'M'' U2 R'' E R U'' R'' E'' R U'' M', '8E', 'U102c', 10, 'NB',
        NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'R2 D R'' U R D'' R'' U'' R''', 'URD+', 'Pure1b', 'L U S U2 S'' U L''', '4S', 'U82i', 10, 'NR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'U R'' U'' R'' D'' R U R'' D R2 U''', 'URD+', 'Pure1b', 'M U L'' U'' M'' U L U'' ', '8M', 'U82h', 10,
        'NV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'R'' D R2 D'' R2 U R2 D R2 D'' R2 U'' R''', '5ins', 'Cyclic', 'R'' U'' R'' E R2 E'' R'' U R ', '4E',
        'U91a', 10, 'NP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R U2', 'UNDEF', 'TWIST', 'L'' U L E'' L'' U'' L E ', '8E',
        'U81', 10, 'NU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'U2 R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R', 'UNDEF', 'TWIST',
        'L'' l'' U'' L U l U2 L'' U'' L'' U L2 U2', 'UNDEF', 'TWIST', 10, 'NL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'D'' R2 D'' R'' U R D R'' U'' R'' D', 'URD+', 'Pure3', 'U'' L'' U'' M'' U2 M U'' L U ', '4M', 'U91a', 10,
        'NI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U R'' U'' R'' D R U R'' D'' R2 U''', 'URD+', 'Pure3', 'M'' U L'' U'' M U L U'' ', '8M', 'U81', 10, 'NT',
        NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'R U R'' D R U R'' D'' R U2 R''', 'URD+', 'Orth', 'U'' R'' E R2 E'' R'' U ', '4E', 'U92b', 10, 'NC', NULL,
        NULL, NULL, NULL, NULL, 14),
       (NULL, 'R'' D'' R U2 R'' D R U2', 'URD', 'Pure2c', 'S L E'' L'' U L E L'' U'' S''', '8E', 'U82c', 9, 'UJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'D2 R2 D'' R'' U R D R'' U'' R'' D2', 'URD+', 'A92', 'D'' M'' U L'' U'' M U L U'' D ', '8M', 'U102b', 10,
        'NO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'R U R2 D'' R U'' R'' D R U R U'' R''', 'URD+', 'Pure2b', 'U'' L U L U'' L'' U'' L'' U'' L U2 ', 'R/L,U',
        'U82b', 10, 'NY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'l'' D2 R U R'' D2 R U'' x''', 'l', 'Pure2a', 'D M'' U L'' U'' M U L U'' D'' ', '8M', 'U102a', 10, 'NJ',
        NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'D R2 D'' R'' U R D R'' U'' R'' D''', 'URD+', 'Pure3', 'U'' L'' U M U2 M'' U L U ', '4M', 'U82j', 10,
        'NE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U'' R2 U'' R'' D'' R U R'' D R'' U', 'URD+', 'Pure3', 'U2 M U'' L'' U M'' U'' L U'' ', '8M', 'U92c', 10,
        'NK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R U R'' D'' R U R'' D R U2 R''', 'URD+', 'Orth', 'R U'' R'' E R2 E'' R'' U R'' ', '4E', 'U82j', 10, 'ND',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 D'' R'' U R D R'' U'' R''', 'URD+', 'Pure2b', 'L'' U L'' E L U'' L'' E'' L2 ', '8E', 'U92c', 10, 'NA',
        NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'U D R'' U'' R'' D R U R'' D'' R2 D'' U''', 'URD+', 'A92', 'U'' L S'' L2 S L U ', '4S', 'U82i', 10, 'NH',
        NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'R D'' R D R'' U R D'' R'' U'' D R''', 'URD+', 'Pure2a', 'L'' U L E L'' U'' L E'' ', '8E', 'U82h', 10,
        'NZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'R'' E R U'' R'' E'' R U ', '8E', 'U82a', 11, 'BR', NULL,
        'L U L'' U'' r U r'' U'' L U r U'' r'' L'' U', NULL, NULL, NULL, 2),
       (NULL, 'U'' R2 D'' R U'' R'' D R U R U', 'URD+', 'Pure1b', 'L'' M U M'' U2 M U M'' L ', '4M', 'U82b', 11, 'LM',
        NULL, 'U R2 U r2 U2 l'' U l U2 r'' L'' U L U'' r'' U'' R2 U''', NULL, NULL, NULL, 3),
       (NULL, 'R U R'' D U'' R D R'' U2 R D'' R'' U'' D'' R U'' R''', 'URD+', 'Cyclic', 'U2 R'' E R U R'' E'' R U ',
        '8E', 'U92a', 11, 'LX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'x'' D R U'' R'' D'' R U l''', 'l', 'Pure1b', 'S R'' E R U'' R'' E'' R U S'' ', '8E', 'U92a', 11, 'LB',
        NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'R'' U2 R'' D'' R U2 R'' D R2', 'URD+', 'A91c', 'U R'' E R U2 R'' E'' R U ', '8E', 'U82d', 11, 'LR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'U'' L'' U R U'' L U R''', 'LUR', 'Pure1a', 'U'' L'' U M'' U'' L U M ', '8M', 'U82e', 11, 'LV', NULL,
        NULL, NULL, NULL, NULL, 7),
       (NULL, 'U R2 D R'' U2 R D'' R'' U2 R'' U''', 'URD+', 'A91c', 'E R U'' R'' E'' R U R'' ', '8E', 'U81', 11, 'LP',
        NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'U2 R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R', 'UNDEF', 'TWIST', 'u'' U2 R'' S R2 S'' R'' U2 u', '4S',
        'U101', 11, 'LU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'R'' D R D'' R'' D R U2 R'' D'' R D R'' D'' R U2', 'UNDEF', 'TWIST',
        'L'' l'' U'' L U l U2 L'' U'' L'' U L2 U2', 'UNDEF', 'TWIST', 11, 'LN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U'' R2 D R U'' R'' D'' R U R U', 'URD+', 'Pure3', 'u'' U'' M2 U R U'' M2 U R'' u ', '8M', 'U101', 11,
        'LI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'D R2 U R D R'' U'' R D'' R D''', 'URD+', 'Pure3', 'u U2 R E'' R2 E R U2 u'' ', '4E', 'U82c', 11, 'LC',
        NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'U'' D'' R2 D R U'' R'' D'' R U R D U', 'URD+', 'A92', 'S'' R'' E R U'' R'' E'' R U S', '8E', 'U82c', 11,
        'LO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'U'' R'' U'' R D R'' U'' R D'' R'' U2 R U', 'URD+', 'Pure2a', 'u'' U2 L E'' L2 E L U2 u ', '4E', 'U82b',
        11, 'LY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R2 U R D R'' U'' R D'' R', 'URD+', 'Pure2b', 'L U S'' U'' L'' U S U'' ', '?', 'U82a', 11, 'LJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R D'' R U'' R'' D R U R2 U''', 'URD+', 'Pure3', 'M U'' L'' U M2 U'' L U M ', '8M', 'U82f', 11, 'LE',
        NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'R'' U2 R'' D'' R U'' R'' D R U'' R', 'URD+', 'Orth', 'U'' M U R'' E R U'' R'' E'' r U ', '8E', 'U82g',
        11, 'LK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D'' R2 U R D R'' U'' R D'' R D', 'URD+', 'Pure3', 'R2 E R U'' R'' E'' R U R ', '8E', 'U82g', 11, 'LD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 U D'' R'' U'' R D R'' U R U'' R2', 'URD+', 'Pure2b', 'r'' L'' U M'' U2 M U L r ', '4M', 'U82f', 11,
        'LA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'x'' U L'' D2 L U'' L'' D2 r', 'r', 'Pure2a', 'E'' L U L'' E L U'' L'' ', '8E', 'U82e', 11, 'LH', NULL,
        NULL, NULL, NULL, NULL, 22),
       (NULL, 'U2 R U R D'' R'' U'' R D R2 U2', 'URD+', 'A92', 'M'' U L S'' L2 S L U'' M', '4S', 'U82d', 11, 'LZ', NULL,
        NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U M U2 M U'' M'' U2 M'' ', 'M,U/D', 'U82d', 12, 'ÍR', NULL,
        'U'' F2 l2 U R U'' l U2 r'' U L U', NULL, NULL, NULL, 2),
       (NULL, 'U'' F2 U R'' U'' l D2 l'' U R', '4ins', 'A91b', 'D S'' l'' U l S l'' U'' l D'' ', '8S', 'U82i', 12, 'IM',
        NULL, 'U2 F'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' F U2', NULL, NULL, NULL, 3),
       (NULL, 'D'' R U2 R D'' R'' U2 R D R2 D', 'URD+', 'A91b', 'U'' M U2 M U M'' U2 M'' ', 'M,U/D', 'U82d', 12, 'IX',
        NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'U'' R'' U D R U'' R'' D'' R U R'' U'' R U', 'URD+', 'A91a', 'D'' S r U'' r'' S'' r U r'' D ', '8S',
        'U82i', 12, 'IB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'l U R'' D2 R U'' R'' D2 x', 'l', 'Pure2c', 'M'' U2 M U2 ', '4M', 'U82n', 12, 'IR', NULL, NULL, NULL,
        NULL, NULL, 6),
       (NULL, 'x U2 L D2 L'' U2 L D2 r''', 'r', 'Pure2c', 'U l'' U'' l S l'' U l S'' U'' ', '8S', 'U82o', 12, 'IV',
        NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' R'' U2 R'' D R U2 R'' D'' R2 U', 'URD+', 'Column', 'U R U'' M'' U2 M U'' R'' U'' ', '4M', 'U91a', 12,
        'IP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'l D'' l'' U R D R'' U2 R D'' R'' U l D l''', '2l', 'Special', 'u'' R'' U'' M2 U R U'' M2 U u ', '8M',
        'U101', 12, 'IU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'D'' R U R D'' R'' U'' R D R2 D', 'URD+', 'Pure3', 'U'' L'' U M'' U2 M U L U ', '4M', 'U91a', 12, 'IN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U'' R'' U'' R'' D R U R'' D'' R2 U', 'URD+', 'Pure3', 'u'' R U'' M2 U R'' U'' M2 U u ', '8M', 'U101', 12,
        'IL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'R'' D R U R'' U'' R U R'' D'' R U'' R'' U R U''', 'UNDEF', 'TWIST', 'U M U M U2 M'' U M'' U M'' U2 M',
        'UNDEF', 'TWIST', 12, 'IT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'U R'' U'' R U R'' D R U'' R'' U R U'' R'' D'' R', 'UNDEF', 'TWIST', 'l'' U l S'' l'' U2 l S l'' U l ',
        '8S', 'U82d', 12, 'IC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'U'' R'' U R D R U'' R'' D'' R U R2 U'' R U', 'URD+', 'A91b', 'l'' U'' S'' U2 S U'' l', '4S', 'U82i', 12,
        'IO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'l D2 l'' U R U'' F2 U R'' U''', '4ins', 'A91b', 'r U'' r'' S r U2 r'' S'' r U'' r'' ', '8S', 'U82d', 12,
        'IY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R D R'' D'' R U R'' D R U'' D'' R''', 'URD+', 'A91a', 'r U S U2 S'' U r''', '4S', 'U82i', 12, 'IJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'R U'' R'' D2 R'' U R D2 R'' U'' R2 U R''', '4ins', 'Special', 'D2 M D2 M'' ', '4M', 'U82n', 12, 'IE',
        NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U'' R'' U R'' D R U'' R'' D'' R2 U', 'URD+', 'Pure3', 'D'' S'' l D l'' S l D'' l'' D ', '8S', 'U82o', 12,
        'IK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D'' R U'' R D'' R'' U R D R2 D', 'URD+', 'Pure3', 'U R'' U'' M'' U2 M U'' R U'' ', '4M', 'U82k', 12,
        'ID', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'x U2 L D L'' U2 L D'' r''', 'r', 'Pure2c', 'r U'' S'' U2 S U'' r''', '4S', 'U82m', 12, 'IA', NULL, NULL,
        NULL, NULL, NULL, 21),
       (NULL, 'l U2 R'' D2 R U2 R'' D2 x', 'l', 'Pure2c', 'U'' L U M'' U2 M U L'' U ', '4M', 'U82k', 12, 'IH', NULL,
        NULL, NULL, NULL, NULL, 22),
       (NULL, 'R D R'' D'' R U R'' D2 R U'' R'' D'' R D'' R''', 'URD+', 'Column', 'l'' U S U2 S'' U l', '4S', 'U82m',
        12, 'IZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'R U'' R'' U M'' U'' R U r'' ', '8M', 'U82e', 13, 'IR', NULL,
        'D U R U'' R U l'' U'' l U R'' U'' l'' U l R U'' R2 U'' D''', NULL, NULL, NULL, 2),
       (NULL, 'U'' R'' D R U R'' D'' R', 'URD', 'Pure1b', 'r U R'' U'' M'' U R U'' R'' M2 ', '8M', 'U82h', 13, 'TM',
        NULL, 'U2 D2 R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' D2 U2', NULL, NULL, NULL, 3),
       (NULL, 'D l'' U2 l D'' R'' D F2 D'' R', '4ins', 'Cyclic', 'L'' U L U'' M'' U L'' U'' l ', '8M', 'U82e', 13, 'TX',
        NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'R'' U'' R U R'' D R U'' R'' D'' U R', 'URD+', 'Pure1b', 'l'' U'' L U M'' U'' L'' U L M2 ', '8M', 'U82h',
        13, 'TB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'U R'' D R U'' R'' D'' R', 'URD', 'Pure2b', 'U M U M U2 M'' U M'' U'' ', '4M', 'U82o', 13, 'TR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'R'' U R U'' R'' D R U R'' U'' D'' R', 'URD+', 'Pure2a', 'U'' S l'' U'' l S'' l'' U l U ', '8S', 'U92d',
        13, 'TV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U R U R'' D R U2 R'' D'' R U R'' U''', 'URD+', 'A92', 'U'' R U M'' U'' R'' U M ', '8M', 'U81', 13, 'TP',
        NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'U2 R'' D R U2 R'' D'' R', 'URD', 'Pure3', 'M'' U R U'' M'' U R'' U'' M2 ', '8M', 'U81', 13, 'TU', NULL,
        NULL, NULL, NULL, NULL, 9),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 11, 'LL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'l U'' l'' U R'' D R U'' R'' D'' R l U l''', 'URD+', 'Orth', 'M2 U'' L'' U M U'' L U M ', '8M', 'U81', 11,
        'LT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'U R2 D R U'' R'' D'' R U R U''', 'URD+', 'Pure3', 'U L'' U'' M'' U L U'' M ', '8M', 'U81', 13, 'TN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U R'' U'' R U R'' D R U'' R'' U R U'' R'' D'' R', 'UNDEF', 'TWIST', 'U M U M U2 M'' U M'' U M'' U2 M',
        'UNDEF', 'TWIST', 13, 'TI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D R U R'' U'' R U R'' D'' R U'' R'' U R U''', 'UNDEF', 'TWIST', 'R U'' R U M'' U'' R'' U r'' ', '8M',
        'U82h', 13, 'TC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'R'' D R D2 R U R'' D2 R U'' R2 D'' R', 'URD+', 'A91c', 'U'' S'' l'' U'' l S l'' U l U ', '8S', 'U82e',
        13, 'TO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D U R U'' R'' D'' R U R'' U''', 'URD+', 'Pure1a', 'L'' U L'' U'' M'' U L U'' l ', '8M', 'U82h', 13, 'TY',
        NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'U R'' D R U'' R'' D2 R U R'' D R U''', 'URD+', 'A91c', 'U S r U r'' S'' r U'' r'' U'' ', '8S', 'U82e',
        13, 'TJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R D R U'' R'' D'' R U R2 U''', 'URD+', 'Pure3', 'D l D l'' S'' l D'' l'' S D'' ', '8S', 'U92d', 13,
        'TE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U D R U'' R'' D2 R U R'' D U''', 'URD+', 'Pure3', 'U M'' U'' M U2 M U M'' U ', 'M,U/D', 'U82o', 13, 'TK',
        NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R'' D R'' U'' R D R'' U R D2 R', 'URD+', 'Orth', 'U'' R'' U M'' U'' R U M ', '8M', 'U82l', 13, 'TD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'D U R U'' F2 U R'' U'' l D2 l'' D''', '4ins', 'A92', 'M'' U R'' U'' M'' U R U'' M2 ', '8M', 'U82l', 13,
        'TA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'U L'' U'' L D L'' U L D'' U''', 'ULD+', 'Pure2a', 'U L U'' M'' U L'' U'' M ', '8M', 'U82l', 13, 'TH',
        NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'R'' D R D R U R'' D'' R U'' R2 D'' R', 'URD+', 'Pure2b', 'M'' U'' L U M'' U'' L'' U M2 ', '8M', 'U82l',
        13, 'TZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U2 R U R'' U'' R'' U'' R'' U R U'' ', 'R/L,U', 'U82d', 14, 'ÓR', NULL,
        'L'' U L'' U'' r U r'' U'' L U r U'' r'' L'' U L2', NULL, NULL, NULL, 2),
       (NULL, 'U'' D R'' D'' R U R'' D R D''', 'URD+', 'Pure1a', 'S'' l'' U l S l'' U'' l ', '8S', 'U82h', 14, 'CM',
        NULL, 'U2 D r2 U2 l'' U l U2 r'' L'' U L U'' r'' D'' U2', NULL, NULL, NULL, 3),
       (NULL, 'R U'' R'' D R U2 R'' D'' R U'' R''', 'URD+', 'A91c', 'R'' U'' R U R U R U'' R'' U'' ', 'R/L,U', 'U82f',
        14, 'CX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'D R'' U'' R U R'' D'' R U'' R'' D U R D''', 'URD+', 'A91c', 'r2 S'' r'' U'' r S r'' U r'' ', '8S',
        'U92c', 14, 'CB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'D U R'' D'' R U'' R'' D R D''', 'URD+', 'Pure2a', 'U'' S'' U2 S U''', '4S', 'U82m', 14, 'CR', NULL, NULL,
        NULL, NULL, NULL, 6),
       (NULL, 'R'' U L'' U'' R U L U''', 'LUR', 'Pure2b', 'r'' U'' R'' U M'' U'' R U R ', '8M', 'U82l', 14, 'CV', NULL,
        NULL, NULL, NULL, NULL, 7),
       (NULL, 'U D'' R2 D'' R'' U2 R D R'' U2 R'' D U''', 'URD+', 'A92', 'U2 R U'' R'' U'' R'' U'' R U R U'' ', 'R/L,U',
        'U82b', 14, 'CP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'D'' U R D'' R'' U2 R D R'' U D', 'URD+', 'Pure3', 'u U2 R E R2 E'' R U2 u'' ', '4E', 'U82b', 14, 'CU',
        NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'R U2 R'' D R U'' R'' D'' R U'' R''', 'URD+', 'Orth', 'U'' R E R2 E'' R U ', '4E', 'U92b', 14, 'CN', NULL,
        NULL, NULL, NULL, NULL, 10),
       (NULL, 'D R'' D R'' U R D'' R'' U'' R2 D''', 'URD+', 'Pure3', 'u U2 R'' E'' R2 E R'' U2 u'' ', '4E', 'U82c', 14,
        'CL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'R'' D R U R'' U'' R U R'' D'' R U'' R'' U R U''', 'UNDEF', 'TWIST',
        'l'' U'' l S'' l'' U2 l S l'' U'' l ', '8S', 'U82d', 14, 'CI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U R'' U'' R U R'' D R U'' R'' U R U'' R'' D'' R', 'UNDEF', 'TWIST', 'r U'' R U M U'' R'' U R'' ', '8M',
        'U82h', 14, 'CT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'R U'' R2 D R U2 R'' D'' R U2 R U R''', 'URD+', 'Cyclic', 'D'' U M U M U2 M'' U M'' U M'' U2 M D',
        'UNDEF', 'TWIST', 14, 'CO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'R U L'' U'' R'' U L U''', 'LUR', 'Pure1b', 'D M D2 M'' D ', '4M', 'U82m', 14, 'CY', NULL, NULL, NULL,
        NULL, NULL, 16),
       (NULL, 'D R U R'' D'' R U'' R''', 'URD', 'Pure1b', 'S r'' D'' r S'' r'' D r ', '8S', 'U82l', 14, 'CJ', NULL,
        NULL, NULL, NULL, NULL, 17),
       (NULL, 'D R2 D'' R'' U'' R D R'' U R'' D''', 'URD+', 'Pure3', 'U R2 U'' M U2 M'' U'' R2 U'' ', '4M', 'U82f', 14,
        'CE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'L'' U L D2 L'' U'' L D2', 'ULD', 'Pure3', 'R'' U R U R U R'' U'' R'' U'' ', 'R/L,U', 'U82c', 14, 'CD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'l'' D R'' D'' R U'' R'' D R U D'' l', 'l', 'Pure2a', 'u'' R'' E'' R2 E R'' u ', '4E', 'U92b', 14, 'CA',
        NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'D'' R D'' R'' U'' R D2 R'' U R D'' R'' D', 'URD+', 'A92', 'U'' R'' E'' R2 E R'' U ', '4E', 'U93', 14,
        'CH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'L'' U L D L'' U'' L D''', 'ULD', 'Pure2b', 'u'' R E R2 E'' R u ', '4E', 'U93', 14, 'CZ', NULL, NULL,
        NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'R E R'' U'' R E'' R'' U ', '8E', 'U82e', 15, 'OR', NULL,
        'D'' U'' F2 l2 U R U'' l U2 r'' U L U D', NULL, NULL, NULL, 2),
       (NULL, 'D R D'' R'' U'' R'' D R U R'' D'' R2 D R'' D''', 'URD+', 'A91b', 'U'' l U'' l'' S'' l U l'' S U ', '8S',
        'U82i', 15, 'OM', NULL, 'U2 F'' R'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' R F U2', NULL, NULL, NULL, 3),
       (NULL, 'R'' D R2 U'' R'' D2 R U R'' D2 R'' D'' R', 'URD+', 'Cyclic', 'U2 R E R'' U R E'' R'' U ', '8E', 'U82g',
        15, 'OX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'R U'' R'' U2 R'' D'' R U2 R'' D R2 U R''', 'URD+', 'A91c', 'U'' l'' U l S'' l'' U'' l S U ', '8S',
        'U82j', 15, 'OB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'U'' R'' D R U R D'' R'' U'' R D R2 D'' R U', 'URD+', 'A91b', 'U R E R'' U2 R E'' R'' U ', '8E', 'U82k',
        15, 'OR', NULL, NULL, NULL, NULL, NULL, 6),
       (NULL, 'U R'' U'' D'' R U R'' D R U'' R'' U R U''', 'URD+', 'A91c', 'R U R U'' M'' U R'' U'' r'' ', '8M', 'U82l',
        15, 'OV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U D'' R'' D F2 D'' R D l'' U2 l U''', '4ins', 'Cyclic', 'D'' U'' R U M'' U'' R'' U M D ', '8M', 'U102a',
        15, 'OP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'R'' D R D R'' U R D2 R'' U'' R D R'' D'' R', 'URD+', 'Column', 'U'' S U R'' U'' S'' U R ', '?', 'U82a',
        15, 'OU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'D2 R U R D'' R'' U'' R D R2 D2', 'URD+', 'A92', 'D'' U L'' U'' M'' U L U'' M D ', '8M', 'U102b', 15,
        'ON', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U'' D'' R'' U'' R'' D R U R'' D'' R2 D U', 'URD+', 'A92', 'S'' U'' R'' E R U R'' E'' R S', '8E', 'U82c',
        15, 'OL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'U'' R'' U R2 U'' R'' D R U R'' D'' R'' U'' R U', 'URD+', 'A91b', 'l'' U S'' U2 S U l', '4S', 'U82i', 15,
        'OI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D R2 U R'' D2 R U'' R'' D2 R'' D'' R', 'URD+', 'A91c', 'U'' l'' U'' l S'' l'' U l S U ', '8S',
        'U82e', 15, 'OT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'R U'' R'' U2 R'' D R U2 R'' D'' R2 U R''', 'URD+', 'Cyclic', 'D'' U M U M U2 M'' U M'' U M'' U2 M D',
        'UNDEF', 'TWIST', 15, 'OC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'R'' D'' R U R'' U'' R U R'' D R U'' R'' U R U''', 'UNDEF', 'TWIST', 'l D l'' S'' l D'' l'' S ', '8S',
        'U82l', 15, 'OY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'U R'' U'' R U R'' D'' R U'' R'' U R U'' R'' D R', 'UNDEF', 'TWIST', 'M'' D'' M'' D2 M D'' M ', '4M',
        'U82k', 15, 'OJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'D R U'' R2 U R D'' R'' U'' R D R U R'' D''', 'URD+', 'A91b', 'U'' S l'' D l S'' l'' D'' l U ', '8S',
        'U82j', 15, 'OE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'D'' l D2 l'' U R U'' F2 U R'' U'' D', '4ins', 'Cyclic', 'M D'' M'' D'' M D'' M'' D'' ', 'M,U/D', 'U82g',
        15, 'OK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D'' R D R'' D'' R U R'' D R U'' D'' R'' D', 'URD+', 'A91c', 'D'' U'' R'' U M'' U'' R U M D ', '8M',
        'U102b', 15, 'OD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R U'' R'' U R D'' R'' U2 R D R'' U R U R''', 'URD+', 'Column', 'U'' S U R U'' S'' U R'' ', '?', 'U82a',
        15, 'OA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'D'' U'' R'' U R'' D R U'' R'' D'' R2 U D', 'URD+', 'A92', 'D'' U L U'' M'' U L'' U'' M D ', '8M', 'U103',
        15, 'OH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, NULL, NULL, NULL, 'L U L'' U'' L'' U'' L'' U L U ', 'R/L,U', 'U82f', 16, 'ÁR', NULL,
        'U R U'' R U l'' U'' l U R'' U'' l'' U l R U'' R2 U''', NULL, NULL, NULL, 2),
       (NULL, 'U'' D'' R'' D R U R'' D'' R D', 'URD+', 'Pure1a', 'l2 S l U l'' S'' l U'' l ', '8S', 'U92c', 16, 'YM',
        NULL, 'U2 D R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' D'' U2', NULL, NULL, NULL, 3),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 13, 'TT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'l U'' l'' R'' D R U R'' D'' R U'' l U l''', 'URD+', 'Orth', 'M'' U'' L'' U M'' U'' L U M2 ', '8M', 'U81',
        13, 'TL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'l'' U2 l D'' R'' D F2 D'' R D', '4ins', 'A91b', 'U2 L'' U'' L U L U L U'' L'' U ', 'R/L,U', 'U82d', 16,
        'YX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'U L U'' R U L'' U'' R''', 'LUR', 'Pure1b', 'S r U'' r'' S'' r U r'' ', '8S', 'U82h', 16, 'YB', NULL,
        NULL, NULL, NULL, NULL, 5),
       (NULL, 'U D'' R'' D R U'' R'' D'' R D', 'URD+', 'Pure1b', 'U S U2 S'' U', '4S', 'U82m', 16, 'YR', NULL, NULL,
        NULL, NULL, NULL, 6),
       (NULL, 'D'' R'' U R U'' R'' D R U R'' D'' U'' R D', 'URD+', 'A91a', 'l U L U'' M'' U L'' U'' L'' ', '8M', 'U82l',
        16, 'YV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' R'' U R D R'' U2 R D'' R'' U R U', 'URD+', 'A91c', 'U L'' E'' L2 E L'' U'' ', '4E', 'U92b', 16, 'YP',
        NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'D U R D R'' U2 R D'' R'' U D''', 'URD+', 'Pure2c', 'u'' U2 L E L2 E'' L U2 u ', '4E', 'U82c', 16, 'YU',
        NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'R U R'' U'' R'' D'' R U R'' D R2 U'' R''', 'URD+', 'Pure2b', 'U2 L'' U L U L U L'' U'' L'' U ', 'R/L,U',
        'U82b', 16, 'YN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U'' R'' U2 R D R'' U R D'' R'' U R U', 'URD+', 'Pure2a', 'u'' U2 L'' E'' L2 E L'' U2 u ', '4E', 'U82b',
        16, 'YL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'U R U'' F2 U R'' U'' l D2 l''', '4ins', 'A91b', 'r U r'' S r U2 r'' S'' r U r'' ', '8S', 'U82d', 16,
        'YI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U R U'' R'' D R U R'' U'' D''', 'URD+', 'Pure1a', 'l'' U L'' U'' M U L U'' L ', '8M', 'U82h', 16, 'YT',
        NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'U L'' U'' R U L U'' R''', 'LUR', 'Pure1b', 'D'' M D2 M'' D'' ', '4M', 'U82m', 16, 'YC', NULL, NULL, NULL,
        NULL, NULL, 14),
       (NULL, 'U R'' U'' R U R'' D'' R U'' R'' U R U'' R'' D R', 'UNDEF', 'TWIST', 'S'' l D l'' S l D'' l'' ', '8S',
        'U82l', 16, 'YO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'R'' D'' R U R'' U'' R U R'' D R U'' R'' U R U''', 'UNDEF', 'TWIST',
        'D U M U M U2 M'' U M'' U M'' U2 M D''', 'UNDEF', 'TWIST', 16, 'YJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R U'' D'' R'' D R U R'' D'' R D R'' U''', 'URD+', 'A91a', 'U'' L2 U M U2 M'' U L2 U ', '4M', 'U82f',
        16, 'YE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U R U'' R'' D'' R U R'' D U''', 'URD+', 'Pure1b', 'U2 M U'' L2 U M'' U'' L2 U'' ', '8M', 'U92c', 16,
        'YK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D R D R'' U'' R D2 R'' U R D R'' D''', 'URD+', 'A91c', 'U L E L2 E'' L U'' ', '4E', 'U93', 16, 'YD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R'' D'' R2 U R'' D R U'' R'' D'' R'' D R', 'URD+', 'Pure2b', 'u L'' E'' L2 E L'' u'' ', '4E', 'U93', 16,
        'YA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'U D'' L'' U'' L D2 L'' U L D'' U''', 'ULD+', 'Pure2c', 'L U'' L'' U'' L'' U'' L U L U ', 'R/L,U', 'U82c',
        16, 'YH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'D R D R'' U'' R D R'' U R D2 R'' D''', 'URD+', 'Pure2a', 'u L E L2 E'' L u'' ', '4E', 'U92b', 16, 'YZ',
        NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U2 L'' E'' L U'' L'' E L U'' ', '8E', 'U82g', 17, 'AR', NULL,
        'U2 R U'' R'' U'' R U l'' U'' l U R'' U'' l'' U l U2', NULL, NULL, NULL, 2),
       (NULL, 'U'' R'' D'' R U R'' D R', 'URD', 'Pure1b', 'U r U'' r'' S r U r'' S'' U'' ', '8S', 'U82j', 17, 'JM',
        NULL, 'U2 r2 U2 l'' U l U2 r'' L'' U L U'' r'' U2', NULL, NULL, NULL, 3),
       (NULL, 'l'' U2 R'' D'' R U2 R'' D R l', 'l', 'A91c', 'L'' E'' L U L'' E L U'' ', '8E', 'U82e', 17, 'JX', NULL,
        NULL, NULL, NULL, NULL, 4),
       (NULL, 'R'' U'' R U R'' D'' R U'' R'' D U R', 'URD+', 'A91a', 'U r'' U r S r'' U'' r S'' U'' ', '8S', 'U82i', 17,
        'JB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'U R'' D'' R U'' R'' D R', 'URD', 'Pure1a', 'U'' L'' E'' L U2 L'' E L U'' ', '8E', 'U82k', 17, 'JR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'R'' U R U'' R'' D'' R U R'' U'' D R', 'URD+', 'Pure1b', 'L'' U'' L'' U M'' U'' L U l ', '8M', 'U82l', 17,
        'JV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' l U'' R'' D'' R U2 R'' D R U'' l'' U', 'l', 'A91b', 'D U'' R U M'' U'' R'' U M D'' ', '8M', 'U102b',
        17, 'JP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'x U R'' D2 R U'' R'' D2 l', 'l', 'Pure2a', 'D U L'' U'' M'' U L U'' M D'' ', '8M', 'U102a', 17, 'JN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'R'' D R'' U R D'' R'' U'' R2', 'URD+', 'Pure2b', 'U S'' U'' L U S U'' L'' ', '?', 'U82a', 17, 'JL', NULL,
        NULL, NULL, NULL, NULL, 11),
       (NULL, 'R D U R'' D'' R U'' R'' D R D'' R''', 'URD+', 'A91a', 'r U'' S U2 S'' U'' r''', '4S', 'U82i', 17, 'JI',
        NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U R'' D'' R U'' R'' D2 R U R'' D'' R U''', 'URD+', 'A91c', 'U r U r'' S r U'' r'' S'' U'' ', '8S',
        'U82e', 17, 'JT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'R U R'' D R U'' R'' D''', 'URD', 'Pure1b', 'r'' D'' r S r'' D r S'' ', '8S', 'U82l', 17, 'JC', NULL,
        NULL, NULL, NULL, NULL, 14),
       (NULL, 'R'' D'' R U R'' U'' R U R'' D R U'' R'' U R U''', 'UNDEF', 'TWIST', 'M'' D M'' D2 M D M ', '4M', 'U82k',
        17, 'JO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'U R'' U'' R U R'' D'' R U'' R'' U R U'' R'' D R', 'UNDEF', 'TWIST',
        'D U M U M U2 M'' U M'' U M'' U2 M D''', 'UNDEF', 'TWIST', 17, 'JY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'D l'' D'' R U R'' D2 R U'' R'' D'' l D''', 'l', 'A91b', 'U S'' r D'' r'' S r D r'' U'' ', '8S', 'U82j',
        17, 'JE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'R D'' U R'' D R U'' R'' D'' R D R''', 'URD+', 'Pure1b', 'M D M'' D M D M'' D ', 'M,U/D', 'U82g', 17,
        'JK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R U R'' D'' R U'' R'' D', 'URD', 'Pure1a', 'D U'' R'' U M'' U'' R U M D'' ', '8M', 'U103', 17, 'JD',
        NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 D'' R'' U'' R D R'' U R''', 'URD+', 'Pure2b', 'S U L'' E L U'' L'' E'' L S''', '8E', 'U93', 17, 'JA',
        NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'l U2 R'' D'' R U2 R'' D x', 'l', 'Pure2a', 'D U L U'' M'' U L'' U'' M D'' ', '8M', 'U102b', 17, 'JH',
        NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'R U R'' D2 R U'' R'' D2', 'URD', 'Pure2c', 'U S'' U'' L'' U S U'' L ', '?', 'U82a', 17, 'JZ', NULL, NULL,
        NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'R U R'' U M U2 M'' U R U'' R'' ', '4M', 'U82f', 18, 'ÉR', NULL,
        'U R2 U'' R U l'' U'' l U R'' U'' l'' U l R U'' R U''', NULL, NULL, NULL, 2),
       (NULL, 'R D'' R'' U'' R'' D R U R'' D'' R2 D R''', 'URD+', 'Pure2c', 'r U R'' U'' M2 U R U'' R'' M'' ', '8M',
        'U82j', 18, 'EM', NULL, 'U2 R2 F r2 U2 l'' U l U2 r'' L'' U L U'' r'' F'' R2 U2', NULL, NULL, NULL, 3),
       (NULL, 'D R U2 R D'' R'' U2 R D R2 D''', 'URD+', 'Column', 'L'' U'' L U'' M U2 M'' U'' L'' U L ', '4M', 'U82f',
        18, 'EX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'R U'' R2 U R D R'' U'' R D'' R U R''', 'URD+', 'Pure2c', 'l'' U'' L U M2 U'' L'' U L M'' ', '8M', 'U82j',
        18, 'EB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'U R D'' R2 D R U'' R'' D'' R U R D R'' U''', 'URD+', 'A91b', 'U2 M U2 M'' ', '4M', 'U82n', 18, 'ER',
        NULL, NULL, NULL, NULL, NULL, 6),
       (NULL, 'D R U'' D'' R'' U R D R'' U'' R U R'' D''', 'URD+', 'A91a', 'U l U l'' S l U'' l'' S'' U'' ', '8S',
        'U92d', 18, 'EV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U l'' U'' R D R'' U2 R D'' R'' U'' l U''', 'l', 'A91b', 'U R U M U2 M'' U R'' U'' ', '4M', 'U82j', 18,
        'EP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'R D'' R'' U2 R'' D R U2 R'' D'' R2 D R''', 'URD+', 'Special', 'M'' U R U'' M2 U R'' U'' M'' ', '8M',
        'U82f', 18, 'EU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'D R U R D'' R'' U'' R D R2 D''', 'URD+', 'Pure3', 'U'' L'' U'' M U2 M'' U'' L U ', '4M', 'U82j', 18,
        'EN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U R2 U'' R'' D'' R U R'' D R'' U''', 'URD+', 'Pure3', 'M'' U'' L'' U M2 U'' L U M'' ', '8M', 'U82f', 18,
        'EL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'R U'' R2 U R D2 R'' U'' R D2 R U R''', '4ins', 'Special', 'M D2 M'' D2 ', '4M', 'U82n', 18, 'EI', NULL,
        NULL, NULL, NULL, NULL, 12),
       (NULL, 'U R2 U'' R'' D R U R'' D'' R'' U''', 'URD+', 'Pure3', 'D S'' l D l'' S l D'' l'' D'' ', '8S', 'U92d', 18,
        'ET', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'D R U'' R D'' R'' U R D R2 D''', 'URD+', 'Pure3', 'U R2 U M U2 M'' U R2 U'' ', '4M', 'U82f', 18, 'EC',
        NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'D R U'' R'' D'' R'' U R D R'' U'' R2 U R'' D''', 'URD+', 'A91b', 'U'' l'' D l S l'' D'' l S'' U ', '8S',
        'U82j', 18, 'EO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'U R D'' R'' D R U'' R'' D'' R D U R'' U''', 'URD+', 'A91a', 'U'' L2 U'' M U2 M'' U'' L2 U ', '4M',
        'U82f', 18, 'EY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'D l'' D R U R'' D2 R U'' R'' D l D''', 'l', 'A91b', 'U r D'' r'' S'' r D r'' S U'' ', '8S', 'U82j', 18,
        'EJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R U'' R'' D'' R U R'' U'' R U R'' D R U'' R''', 'UNDEF', 'TWIST',
        'U'' M'' U M'' U2 M U M U M U2 M'' U2', 'UNDEF', 'TWIST', 18, 'EK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'R U R'' D'' R U'' R'' U R U'' R'' D R U R'' U''', 'UNDEF', 'TWIST', 'U R'' U M U2 M'' U R U'' ', '4M',
        'U82j', 18, 'ED', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R U'' R2 U R D'' R'' U'' R D R U R''', 'URD+', 'Pure2c', 'M'' U R'' U'' M2 U R U'' M'' ', '8M', 'U82f',
        18, 'EA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'U2 R'' D'' R U2 R'' D R', 'URD', 'Pure2c', 'S U L E'' L'' U'' L E L'' S''', '8E', 'U82c', 17, 'JU', NULL,
        NULL, NULL, NULL, NULL, 9),
       (NULL, 'U R2 U'' R'' D2 R U R'' D2 R'' U''', 'URD+', 'Column', 'U'' L U'' M U2 M'' U'' L'' U ', '4M', 'U82j', 18,
        'EH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'R D'' R'' U R'' D R U'' R'' D'' R2 D R''', 'URD+', 'Pure2c', 'M'' U'' L U M2 U'' L'' U M'' ', '8M',
        'U82f', 18, 'EZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'M U'' M'' U'' M U'' M'' U'' ', 'M,U/D', 'U82g', 19, 'ER', NULL,
        'U2 R2 U'' R'' U'' R U l'' U'' l U R'' U'' R'' F U2', NULL, NULL, NULL, 2),
       (NULL, 'U2 R D R'' U R D'' R'' U', 'URD+', 'Pure2a', 'M2 U M U M'' U M U M ', 'M,U/D', 'U92c', 19, 'KM', NULL,
        'U2 R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' U2', NULL, NULL, NULL, 3),
       (NULL, 'l'' U R D R'' U2 R D'' R'' U l', 'l', 'A92', 'M U M'' U M U M'' U ', 'M,U/D', 'U82g', 19, 'KX', NULL,
        NULL, NULL, NULL, NULL, 4),
       (NULL, 'R'' U R'' D'' R U2 R'' D R U R', 'URD+', 'Pure2b', 'M2 U'' M U'' M'' U'' M U'' M ', 'M,U/D', 'U92c', 19,
        'KB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'R D R'' U'' R D'' R'' U', 'URD', 'Pure1a', 'U'' M'' U M'' U2 M U M U ', '4M', 'U82o', 19, 'KR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'U'' R U R'' U'' R D R'' U R D'' U'' R'' U', 'URD+', 'A91c', 'U'' S l U l'' S'' l U'' l'' U ', '8S',
        'U82o', 19, 'KV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U R U R'' D'' R U2 R'' D R U R'' U''', 'URD+', 'A91c', 'U'' R U'' M U R'' U'' M'' U2 ', '8M', 'U92c', 19,
        'KP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'U R D R'' U2 R D'' R'' U', 'URD+', 'Pure3', 'U l E'' L'' U'' L E L'' U M'' U'' ', '8E', 'U82g', 19, 'KU',
        NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'U'' R D'' R U'' R'' D R U R2 U', 'URD+', 'Pure3', 'U L'' U M U'' L U M'' U2 ', '8M', 'U92c', 19, 'KN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'R'' U R'' D'' R U R'' D R U2 R', 'URD+', 'Orth', 'U'' r'' E R U R'' E'' R U'' M'' U ', '8E', 'U82g', 19,
        'KL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'U'' R2 D R U R'' D'' R U'' R U', 'URD+', 'Pure3', 'D'' l D l'' S'' l D'' l'' S D ', '8S', 'U82o', 19,
        'KI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U D'' R U'' R'' D2 R U R'' D'' U''', 'URD+', 'Pure3', 'U'' M U'' M'' U2 M'' U M U'' ', 'M,U/D', 'U82o',
        19, 'KT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'D'' U R U'' F2 U R'' U'' l D2 l'' D', '4ins', 'Cyclic', 'D M D M'' D M D M'' ', 'M,U/D', 'U82g', 19,
        'KO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'U D'' R U'' R'' D R U R'' U''', 'URD+', 'Pure1b', 'U L2 U M U'' L2 U M'' U2 ', '8M', 'U92c', 19, 'KY',
        NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R D'' R'' D R U R'' D'' R U'' D R''', 'URD+', 'Pure1b', 'D'' M D'' M'' D'' M D'' M'' ', 'M,U/D', 'U82g',
        19, 'KJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'R U R'' D'' R U'' R'' U R U'' R'' D R U R'' U''', 'UNDEF', 'TWIST',
        'U'' M'' U M'' U2 M U M U M U2 M'' U2', 'UNDEF', 'TWIST', 19, 'KE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'U R U'' R'' D'' R U R'' U'' R U R'' D R U'' R''', 'UNDEF', 'TWIST', 'U'' R'' U'' M U R U'' M'' U2 ',
        '8M', 'U82g', 19, 'KD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'R2 D2 R U R'' D R U'' R'' D R2', 'URD+', 'Pure2a', 'u r U'' M'' U2 M U'' r'' u'' ', '4M', 'U92c', 19,
        'KA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'U'' R'' U'' R D'' R'' U R U D', 'URD+', 'Pure2b', 'U L U M U'' L'' U M'' U2 ', '8M', 'U82g', 19, 'KH',
        NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'R D R'' U'' R D2 R'' U R D R''', 'URD+', 'A92', 'u'' l'' U M'' U2 M U l u ', '4M', 'U92c', 19, 'KZ',
        NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U R U R U R'' U'' R'' U'' R''', 'R/L,U', 'U82a', 20, 'DR', NULL,
        'D R D'' U l'' U'' l U R'' U'' l'' U l R U'' R'' U'' R D R'' D''', NULL, NULL, NULL, 2),
       (NULL, 'U'' D'' R'' D'' R U R'' D R D', 'URD+', 'Pure2b', 'U r'' U M'' U2 M U r U'' ', '4M', 'U102a', 20, 'DM',
        NULL, 'U2 D'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' D U2', NULL, NULL, NULL, 3),
       (NULL, 'R U'' R'' D'' R U2 R'' D R U'' R''', 'URD+', 'A92', 'U'' R U R U R U'' R'' U'' R''', 'R/L,U', 'U82c', 20,
        'DX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'R2 U'' R D R'' U'' R D'' R'' U2 R2', 'URD+', 'Pure2a', 'l'' E L U'' L'' E'' L U M ', '8E', 'U102b', 20,
        'DB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'D R D'' R'' U'' R D R'' D'' U', 'URD+', 'Pure1b', 'R U'' S'' U2 S U'' R''', '4S', 'U82i', 20, 'DR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'R D U'' R'' U R D'' R'' U'' R U R''', 'URD+', 'Pure1b', 'M U'' R'' U M'' U'' R U ', '8M', 'U82e', 20,
        'DV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' l U2 l'' D R D'' B2 D R'' D'' U', '4ins', 'Cyclic', 'U R S R2 S'' R U'' ', '4S', 'U82i', 20, 'DP',
        NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'D U R D'' R'' U2 R D R'' U D''', 'URD+', 'Pure3', 'R'' U'' R E R'' U R E'' ', '8E', 'U82e', 20, 'DU',
        NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'R U2 R'' D'' R U'' R'' D R U'' R''', 'URD+', 'Orth', 'R U'' R E R2 E'' R U R'' ', '4E', 'U82j', 20, 'DN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'D'' R'' D R'' U R D'' R'' U'' R2 D', 'URD+', 'Pure3', 'R'' U'' R'' E R U R'' E'' R2 ', '8E', 'U82g', 20,
        'DL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'D'' R2 D'' R'' U'' R D R'' U R'' D', 'URD+', 'Pure3', 'U R'' U M'' U2 M U R U'' ', '4M', 'U82k', 20,
        'DI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D2 R'' U'' R D'' R'' U R D'' R', 'URD+', 'Orth', 'M'' U'' R'' U M U'' R U ', '8M', 'U82l', 20, 'DT',
        NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'D2 L'' U L D2 L'' U'' L', 'ULD', 'Pure3', 'U R U R U'' R'' U'' R'' U'' R ', 'R/L,U', 'U82c', 20, 'DC',
        NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'D'' R D U R'' D'' R U'' R'' D R D'' R'' D', 'URD+', 'A91c', 'D'' M'' U'' R'' U M U'' R U D ', '8M',
        'U102b', 20, 'DO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'D R D'' R'' U'' R D2 R'' U R D'' R'' D''', 'URD+', 'A91c', 'U L'' E L2 E'' L'' U'' ', '4E', 'U93', 20,
        'DY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'D'' R U R'' D R U'' R''', 'URD', 'Pure1a', 'D M'' U'' R'' U M U'' R U D'' ', '8M', 'U103', 20, 'DJ',
        NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R U'' R'' D'' R U R'' U'' R U R'' D R U'' R''', 'UNDEF', 'TWIST', 'U R'' U'' M U2 M'' U'' R U'' ',
        '4M', 'U82j', 20, 'DE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'R U R'' D'' R U'' R'' U R U'' R'' D R U R'' U''', 'UNDEF', 'TWIST', 'U2 M U R'' U'' M'' U R U ', '8M',
        'U82g', 20, 'DK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'l'' D'' R U R'' D2 R U'' R'' D'' l', 'l', 'A92', 'U2 R'' r'' U'' R U r U2 R'' U'' R'' U R2', 'UNDEF',
        'TWIST', 20, 'DA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'x'' U'' L'' D2 L U L'' D2 r', 'r', 'Pure2b', 'R U'' R'' E'' R2 E R'' U R'' ', '4E', 'U82k', 20, 'DH',
        NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'D'' R U R'' D'' R U'' R'' D2', 'URD+', 'Pure2a', 'R'' U'' R E'' R'' U R E ', '8E', 'U82l', 20, 'DZ',
        NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U2 L'' E L U'' L'' E'' L U'' ', '8E', 'U82b', 21, 'PR', NULL,
        'D U'' F2 l2 U R U'' l U2 r'' U L U D''', NULL, NULL, NULL, 2),
       (NULL, 'R'' D'' R D R U'' R'' D'' R U R2 D R', 'URD+', 'Pure2c', 'S'' L'' E L U L'' E'' L U'' S ', '8E', 'U82a',
        21, 'AM', NULL, 'U2 D F'' r2 U2 l'' U l U2 r'' L'' U L U'' r'' F D'' U2', NULL, NULL, NULL, 3),
       (NULL, 'R U2 R D'' R'' U2 R D R2', 'URD+', 'A92', 'L'' E L U L'' E'' L U'' ', '8E', 'U82c', 21, 'AX', NULL, NULL,
        NULL, NULL, NULL, 4),
       (NULL, 'R2 D'' R U'' R'' D'' R U R'' D2 R2', 'URD+', 'Pure2a', 'r'' U'' M'' U2 M U'' r ', '4M', 'U92b', 21, 'AB',
        NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'x D2 R'' U'' R D2 R'' U l', 'l', 'Pure2c', 'U'' L'' E L U2 L'' E'' L U'' ', '8E', 'U82d', 21, 'AR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'R D'' U'' R'' U R D R'' U'' R U R''', 'URD+', 'Pure2a', 'U R'' U'' M'' U R U'' M ', '8M', 'U82h', 21,
        'AV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' D R'' U2 R'' D R U2 R'' D'' R2 D'' U', 'URD+', 'A92', 'E'' R U'' R'' E R U R'' ', '8E', 'U82h', 21,
        'AP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'R D'' l U2 l'' D R D'' B2 D R2', '4ins', 'Column', 'M'' U'' R S R2 S'' R U M ', '4S', 'U82d', 21, 'AU',
        NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'R U R D'' R'' U'' R D R2', 'URD+', 'Pure2b', 'L2 E L U L'' E'' L U'' L ', '8E', 'U92c', 21, 'AN', NULL,
        NULL, NULL, NULL, NULL, 10),
       (NULL, 'R2 U R'' U'' R D'' R'' U R D U'' R2', 'URD+', 'Pure2b', 'r'' L'' U'' M'' U2 M U'' L r ', '4M', 'U82f',
        21, 'AL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'r D L'' U2 L D'' L'' U2 x''', 'r', 'Pure2c', 'r U S'' U2 S U r''', '4S', 'U82m', 21, 'AI', NULL, NULL,
        NULL, NULL, NULL, 12),
       (NULL, 'D l D2 l'' U R U'' F2 U R'' U'' D''', '4ins', 'A92', 'M2 U R'' U'' M U R U'' M ', '8M', 'U82l', 21, 'AT',
        NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'l'' D U'' R'' D'' R U R'' D R D'' l', 'l', 'Pure2a', 'u'' R E'' R2 E R u ', '4E', 'U92b', 21, 'AC', NULL,
        NULL, NULL, NULL, NULL, 14),
       (NULL, 'R U'' R'' U'' R D'' R'' U2 R D R'' U'' R U R''', 'URD+', 'Column', 'R U'' S U R'' U'' S'' U ', '?',
        'U82a', 21, 'AO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'R'' D'' R D R U R'' D'' R U'' R2 D R', 'URD+', 'Pure2b', 'u L E'' L2 E L u'' ', '4E', 'U93', 21, 'AY',
        NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'R D R'' U'' R D R'' U R D2 R''', 'URD+', 'Orth', 'U'' R2 U'' M U R2 U'' M'' U2 ', '8M', 'U92c', 19, 'KC',
        NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, 'R U'' R D'' R'' U R D R2', 'URD+', 'Pure2b', 'S L'' E L U L'' E'' L U'' S''', '8E', 'U93', 21, 'AJ',
        NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'R U'' R'' D'' R'' U R D R'' U'' R2 U R''', 'URD+', 'Pure2c', 'M U R'' U'' M2 U R U'' M ', '8M', 'U82f',
        21, 'AE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'R2 D'' R U R'' D'' R U'' R'' D2 R2', 'URD+', 'Pure2a', 'u r U M'' U2 M U r'' u'' ', '4M', 'U92c', 21,
        'AK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'l'' D R U R'' D2 R U'' R'' D l', 'l', 'A92', 'U2 R'' r'' U'' R U r U2 R'' U'' R'' U R2', 'UNDEF',
        'TWIST', 21, 'AD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, 'U'' R D'' R'' U R U'' R'' U R D R'' U'' R U R''', 'UNDEF', 'TWIST', 'E L U L'' E'' L U'' L'' ', '8E',
        'U82l', 21, 'AH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'R U'' R'' U R D'' R'' U'' R U R'' U'' R D R'' U', 'UNDEF', 'TWIST', 'x'' U'' M'' U2 M U'' x ', '4M',
        'U82m', 21, 'AZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'U L'' U'' L'' U'' L'' U L U L', 'R/L,U', 'U82c', 22, 'LR', NULL,
        'D'' R D U l'' U'' l U R'' U'' l'' U l R U'' R'' U'' R D'' R'' D', NULL, NULL, NULL, 2),
       (NULL, 'D U'' R'' D R U R'' D'' R D''', 'URD+', 'Pure2b', 'r E'' R'' U R E R'' U'' M ', '8E', 'U102b', 22, 'HM',
        NULL, 'U2 D'' R r2 U2 l'' U l U2 r'' L'' U L U'' r'' R'' D U2', NULL, NULL, NULL, 3),
       (NULL, 'D2 l'' U2 l D'' R'' D F2 D'' R D''', '4ins', 'Column', 'U'' L'' U'' L'' U'' L U L U L', 'R/L,U', 'U82a',
        22, 'HX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, 'x'' D R U2 R'' D'' R U2 l''', 'l', 'Pure2b', 'U'' l U'' M'' U2 M U'' l'' U ', '4M', 'U102a', 22, 'HB',
        NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'D'' R D R'' U'' R D'' R'' U D', 'URD+', 'Pure2a', 'L'' U S U2 S'' U L', '4S', 'U82i', 22, 'HR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'r'' D2 L U2 L'' D2 L U2 x', 'r', 'Pure2c', 'M U L U'' M'' U L'' U'' ', '8M', 'U82e', 22, 'HV', NULL,
        NULL, NULL, NULL, NULL, 7),
       (NULL, 'U'' R'' U R D'' R'' U2 R D R'' U R U', 'URD+', 'A92', 'R'' U'' R E'' R2 E R U R ', '4E', 'U82j', 22,
        'HP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'D'' U R D R'' U2 R D'' R'' U D', 'URD+', 'Pure2c', 'L U L E'' L'' U'' L E L2 ', '8E', 'U82g', 22, 'HU',
        NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, 'U D R2 D R U'' R'' D'' R U R D'' U''', 'URD+', 'A92', 'U'' L'' S'' L2 S L'' U ', '4S', 'U82i', 22, 'HN',
        NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'r'' D2 L U L'' D2 L U'' x', 'r', 'Pure2a', 'L U L'' E'' L U'' L'' E ', '8E', 'U82e', 22, 'HL', NULL,
        NULL, NULL, NULL, NULL, 11),
       (NULL, 'x'' D2 R U2 R'' D2 R U2 l''', 'l', 'Pure2c', 'U'' L U'' M'' U2 M U'' L'' U ', '4M', 'U82k', 22, 'HI',
        NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'U D L'' U'' L D'' L'' U L U''', 'ULD+', 'Pure2a', 'M'' U L U'' M U L'' U'' ', '8M', 'U82l', 22, 'HT',
        NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'D'' R D R'' U'' R D2 R'' U R D R'' D', 'URD+', 'A92', 'U'' R E'' R2 E R U ', '4E', 'U93', 22, 'HC', NULL,
        NULL, NULL, NULL, NULL, 14),
       (NULL, 'D'' U'' R2 D R U R'' D'' R U'' R U D', 'URD+', 'A92', 'D'' M'' U L U'' M U L'' U'' D ', '8M', 'U103', 22,
        'HO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, 'U D L'' U'' L D2 L'' U L D U''', 'ULD+', 'Pure2c', 'U'' L'' U'' L'' U L U L U L'' ', 'R/L,U', 'U82c', 22,
        'HY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'x'' D'' R U2 R'' D R U2 l''', 'l', 'Pure2a', 'D M'' U L U'' M U L'' U'' D'' ', '8M', 'U102b', 22, 'HJ',
        NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, 'U R D2 R U'' R'' D2 R U R2 U''', 'URD+', 'Column', 'U'' L U M U2 M'' U L'' U ', '4M', 'U82j', 22, 'HE',
        NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'D'' U'' R'' U'' R D R'' U R U', 'URD+', 'Pure2b', 'U2 M U'' L U M'' U'' L'' U'' ', '8M', 'U82g', 22,
        'HK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'r'' D2 L U'' L'' D2 L U x', 'r', 'Pure2b', 'R U'' R E'' R2 E R U R'' ', '4E', 'U82k', 22, 'HD', NULL,
        NULL, NULL, NULL, NULL, 20),
       (NULL, 'R U'' R'' U R D'' R'' U'' R U R'' U'' R D R'' U', 'UNDEF', 'TWIST', 'L U L'' E L U'' L'' E'' ', '8E',
        'U82l', 22, 'HA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 22, 'HH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, 'U'' R D'' R'' U R U'' R'' U R D R'' U'' R U R''', 'UNDEF', 'TWIST',
        'U2 L l U L'' U'' l'' U2 L U L U'' L2', 'UNDEF', 'TWIST', 22, 'HZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, NULL, NULL, NULL, 'R E'' R'' U'' R E R'' U ', '8E', 'U82c', 23, 'ZR', NULL,
        'R D'' U l'' U'' l U R'' U'' l'' U l R U'' R'' U'' R D R''', NULL, NULL, NULL, 2),
       (NULL, 'U2 R D'' R'' U R D R'' U', 'URD+', 'Pure2a', 'l U M'' U2 M U l'' ', '4M', 'U92b', 23, 'ZM', NULL,
        'U2 D2 r2 U2 l'' U l U2 r'' L'' U L U'' r'' D2 U2', NULL, NULL, NULL, 3),
       (NULL, 'l'' U2 R'' D R U2 R'' D'' R l', 'l', 'A92', 'U2 R E'' R'' U R E R'' U ', '8E', 'U82b', 23, 'ZX', NULL,
        NULL, NULL, NULL, NULL, 4),
       (NULL, 'U'' R U'' R'' U R D'' R'' U'' R D U R'' U', 'URD+', 'Pure2c', 'S R E'' R'' U'' R E R'' U S'' ', '8E',
        'U82a', 23, 'ZB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, 'R D'' R'' U'' R D R'' U', 'URD', 'Pure2b', 'U R E'' R'' U2 R E R'' U ', '8E', 'U82d', 23, 'ZR', NULL,
        NULL, NULL, NULL, NULL, 6),
       (NULL, 'U'' L U R U'' L'' U R''', 'LUR', 'Pure2b', 'U'' L U M'' U'' L'' U M ', '8M', 'U82h', 23, 'ZV', NULL,
        NULL, NULL, NULL, NULL, 7),
       (NULL, 'U R2 D'' R'' U2 R D R'' U2 R'' U''', 'URD+', 'Column', 'R2 E'' R'' U'' R E R'' U R'' ', '8E', 'U92c', 23,
        'ZP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, 'U R D'' R'' U2 R D R'' U', 'URD+', 'Pure2c', 'l R U M'' U2 M U R'' l'' ', '4M', 'U82f', 23, 'ZU', NULL,
        NULL, NULL, NULL, NULL, 9),
       (NULL, 'R D'' U R D R'' U'' R D'' R'' D R''', 'URD+', 'Pure2a', 'E L'' U L E'' L'' U'' L ', '8E', 'U82h', 23,
        'ZN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, 'U2 R2 D'' R'' U R D R'' U'' R'' U2', 'URD+', 'A92', 'M'' U L'' S'' L2 S L'' U'' M', '4S', 'U82d', 23,
        'ZL', NULL, NULL, NULL, NULL, NULL, 11),
       (NULL, 'R D R'' D R U R'' D2 R U'' R'' D R D'' R''', 'URD+', 'Column', 'l'' U'' S U2 S'' U'' l', '4S', 'U82m',
        23, 'ZI', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, 'R'' D R2 U R'' D R U'' R'' D'' R'' D'' R', 'URD+', 'Pure2b', 'M2 U'' L U M U'' L'' U M ', '8M', 'U82l',
        23, 'ZT', NULL, NULL, NULL, NULL, NULL, 13),
       (NULL, 'D L'' U L D'' L'' U'' L', 'ULD', 'Pure2b', 'u'' R'' E R2 E'' R'' u ', '4E', 'U93', 23, 'ZC', NULL, NULL,
        NULL, NULL, NULL, 14),
       (NULL, 'D R D2 R'' U'' R D'' R'' U R D'' R'' D''', 'URD+', 'Pure2a', 'u L'' E L2 E'' L'' u'' ', '4E', 'U92b', 23,
        'ZY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, 'D2 R U R'' D2 R U'' R''', 'URD', 'Pure2c', 'L'' U S'' U'' L U S U'' ', '?', 'U82a', 23, 'ZJ', NULL, NULL,
        NULL, NULL, NULL, 17),
       (NULL, 'R D'' R2 D R U R'' D'' R U'' R D R''', 'URD+', 'Pure2c', 'M U'' L U M2 U'' L'' U M ', '8M', 'U82f', 23,
        'ZE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, 'R D'' R'' U'' R D2 R'' U R D'' R''', 'URD+', 'A92', 'u'' l'' U'' M'' U2 M U'' l u ', '4M', 'U92c', 23,
        'ZK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D2 R U R'' D R U'' R'' D', 'URD+', 'Pure2a', 'E'' R'' U'' R E R'' U R ', '8E', 'U82l', 23, 'ZD', NULL,
        NULL, NULL, NULL, NULL, 20),
       (NULL, 'U'' R D'' R'' U R U'' R'' U R D R'' U'' R U R''', 'UNDEF', 'TWIST', 'x'' U M'' U2 M U x ', '4M', 'U82m',
        23, 'ZA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'R U'' R'' U R D'' R'' U'' R U R'' U'' R D R'' U', 'UNDEF', 'TWIST',
        'U2 L l U L'' U'' l'' U2 L U L U'' L2', 'UNDEF', 'TWIST', 23, 'ZH', NULL, NULL, NULL, NULL, NULL, 22),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 3, 'MM', NULL,
        'S'' U'' R U l'' U'' l U R'' U'' l'' U l R U'' R'' S', NULL, NULL, NULL, 3),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 4, 'XX', NULL, NULL, NULL, NULL, NULL, 4),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 5, 'BB', NULL, NULL, NULL, NULL, NULL, 5),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 6, 'RR', NULL,
        'R'' U'' F'' R U R'' U'' l'' U l R U'' R'' U'' R U R'' U R', NULL, NULL, NULL, 6),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 7, 'VV', NULL, NULL, NULL, NULL, NULL, 7),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 8, 'PP', NULL, NULL, NULL, NULL, NULL, 8),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 9, 'UU', NULL, NULL, NULL, NULL, NULL, 9),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 10, 'NN', NULL, NULL, NULL, NULL, NULL, 10),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 12, 'II', NULL, NULL, NULL, NULL, NULL, 12),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 14, 'CC', NULL, NULL, NULL, NULL, NULL, 14),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 15, 'OO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 16, 'YY', NULL, NULL, NULL, NULL, NULL, 16),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 17, 'JJ', NULL, NULL, NULL, NULL, NULL, 17),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 18, 'EE', NULL, NULL, NULL, NULL, NULL, 18),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 19, 'KK', NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 20, 'DD', NULL, NULL, NULL, NULL, NULL, 20),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 21, 'AA', NULL, NULL, NULL, NULL, NULL, 21),
       (NULL, 'D2 R2 D'' R'' U'' R D R'' U R'' D2', 'URD+', 'A92', 'S'' R E'' R'' U'' R E R'' U S', '8E', 'U93', 23,
        'ZO', NULL, NULL, NULL, NULL, NULL, 15),
       (NULL, NULL, 'UNDEF', 'NULL', NULL, 'UNDEF', 'NULL', 23, 'ZZ', NULL, NULL, NULL, NULL, NULL, 23),
       (NULL, 'R D2 R'' U'' R D'' R'' U R D'' R''', 'URD+', 'Orth', 'U2 M U R2 U'' M'' U R2 U ', '8M', 'U92c', 14, 'CK',
        NULL, NULL, NULL, NULL, NULL, 19),
       (NULL, 'D2 R U'' R D'' R'' U R D R2 D2', 'URD+', 'A92', 'S'' U'' R E'' R'' U R E R'' S', '8E', 'U93', 15, 'OZ',
        NULL, NULL, NULL, NULL, NULL, 23) ON CONFLICT DO NOTHING;
